In [58]:
import numpy as np
import pandas as pd

import string
import re

#### Read CSV file
- pd.read_csv(path, delimiter='\t)
- with open()

In [59]:
with open("./businessCard.txt", mode = 'r', encoding = 'utf8', errors = 'ignore') as f:
    text = f.read()

In [4]:
text

'id\ttext\ttag\n000.jpeg\t \tO\n000.jpeg\t.\tO\n000.jpeg\t040-4852\tB-PHONE\n000.jpeg\t"8881,"\tI-PHONE\n000.jpeg\t90309\tB-PHONE\n000.jpeg\t52549\tI-PHONE\n000.jpeg\tFi\tO\n000.jpeg\t/laurelsoverseaseducation\tO\n000.jpeg\t@:\tO\n000.jpeg\tLAURELS\tB-ORG\n000.jpeg\tOVERSEAS\tI-ORG\n000.jpeg\tEDUCATIONAL\tI-ORG\n000.jpeg\tCONSULTANCY\tI-ORG\n000.jpeg\tPVT.\tI-ORG\n000.jpeg\tLTD.\tI-ORG\n000.jpeg\tSea\tO\n000.jpeg\t|\tO\n000.jpeg\tU.K\tO\n000.jpeg\tAUSTRALIA\tO\n000.jpeg\tCANADA\tO\n000.jpeg\tIRELAND\tO\n000.jpeg\t \tO\n000.jpeg\t \tO\n000.jpeg\t \tO\n000.jpeg\t \tO\n000.jpeg\t \tO\n000.jpeg\t \tO\n000.jpeg\twww.laurelseducation.com\tB-WEB\n000.jpeg\t)%info@laurelseducation.com\tB-EMAIL\n000.jpeg\t \tO\n001.jpeg\tjohn\tB-NAME\n001.jpeg\tsmith\tI-NAME\n001.jpeg\tmarketing\tB-DES\n001.jpeg\tmanager\tI-DES\n001.jpeg\tweb:\tO\n001.jpeg\twww.psdgraphics.com\tB-WEB\n001.jpeg\tphone:\tO\n001.jpeg\t123-456-7890\tB-PHONE\n001.jpeg\tmail:\tO\n001.jpeg\temail@psdgraphics.com\tB-EMAIL\n002.jpeg\t    \tO\n002.jpeg\t   \tO\n002.jpeg\tSau\tO\n002.jpeg\t0\tO\n002.jpeg\t98489\tB-PHONE\n002.jpeg\t24441\tI-PHONE\n002.jpeg\tdy\tO\n002.jpeg\t"08672,"\tO\n002.jpeg\t224441\tO\n002.jpeg\t/ENKATESWAPA\tB-ORG\n002.jpeg\t&\tO\n002.jpeg\twie\tO\n002.jpeg\t \tO\n002.jpeg\t=\tO\n002.jpeg\t \tO\n003.jpeg\tPrasad\tB-NAME\n003.jpeg\t@\tO\n003.jpeg\t"9,96,31,73,53,59,49,04,00,000"\tO\n003.jpeg\t  \tO\n003.jpeg\t   \tO\n003.jpeg\ti\tO\n003.jpeg\tFlex\tO\n003.jpeg\tDesign\tO\n003.jpeg\t#\tO\n003.jpeg\tAlbum\tO\n003.jpeg\tDesign\tO\n003.jpeg\t\tO\n003.jpeg\tVisiting\tO\n003.jpeg\tCards\tO\n003.jpeg\tDTP\tO\n003.jpeg\tWorks\tO\n003.jpeg\t(Telugu\tO\n003.jpeg\t&\tO\n003.jpeg\tEnglish)\tO\n003.jpeg\t \tO\n003.jpeg\t \tO\n003.jpeg\t \tO\n003.jpeg\t \tO\n004.jpeg\t<=>\tO\n004.jpeg\tMadison\tB-ORG\n004.jpeg\tYacht\tI-ORG\n004.jpeg\tSales\tI-ORG\n004.jpeg\tPaul\tB-NAME\n004.jpeg\tMadison\tI-NAME\n004.jpeg\tYacht\tB-DES\n004.jpeg\tBroker\tI-DES\n004.jpeg\t-\tO\n004.jpeg\tNortheast\tO\n004.jpeg\tRegion\tO\n004.jpeg\t   \tO\n004.jpeg\t  \tO\n004.jpeg\t \tO\n004.jpeg\tFax:\tO\n004.jpeg\t718-444-1206\tB-PHONE\n004.jpeg\t  \tO\n007.jpeg\twww\tB-WEB\n007.jpeg\tphototomics.com\tI-WEB\n007.jpeg\tPHOTOT\tB-ORG\n007.jpeg\tThomas\tB-NAME\n007.jpeg\tAtkins\tI-NAME\n007.jpeg\tPhotographer\tB-DES\n007.jpeg\tand\tI-DES\n007.jpeg\tDigital\tI-DES\n007.jpeg\tArtist\tI-DES\n007.jpeg\ttatkins@phototomics.com\tB-EMAIL\n007.jpeg\tPhototomics\tO\n007.jpeg\t3419\tO\n007.jpeg\tVia\tO\n007.jpeg\tLido\tO\n007.jpeg\t#340\tO\n007.jpeg\tNewport\tO\n007.jpeg\tBeach\tO\n007.jpeg\tCA\tO\n007.jpeg\t-\tO\n007.jpeg\tCalifornia\tO\n007.jpeg\t92663\tO\n007.jpeg\t \tO\n008.jpeg\t \tO\n008.jpeg\tReddy\tO\n008.jpeg\t9866186785\tB-PHONE\n008.jpeg\t   \tO\n008.jpeg\t \tO\n008.jpeg\tOpp\tO\n008.jpeg\tRamakrishna\tO\n008.jpeg\t"Theatre,Main"\tO\n008.jpeg\tRoad\tO\n008.jpeg\t"Peddapalli,"\tO\n008.jpeg\tDist\tO\n008.jpeg\t:\tO\n008.jpeg\t"Karimnagar,"\tO\n008.jpeg\tTelangana\tO\n008.jpeg\t-\tO\n008.jpeg\t505172\tO\n008.jpeg\temail\tO\n008.jpeg\t:\tO\n008.jpeg\tsrihithaads.pdpl@\tB-EMAIL\n008.jpeg\tgmail.com\tI-EMAIL\n008.jpeg\t \tO\n009.jpeg\tSaja\tB-NAME\n009.jpeg\t(Vik):\tO\n009.jpeg\t990083000\tB-PHONE\n009.jpeg\tG.S.M.\tB-ORG\n009.jpeg\tBOOSTER\tI-ORG\n009.jpeg\t1)\tO\n009.jpeg\tAll\tO\n009.jpeg\tTypes\tO\n009.jpeg\tof\tO\n009.jpeg\tMobile\tO\n009.jpeg\t"Repair,"\tO\n009.jpeg\t\tO\n009.jpeg\tData\tO\n009.jpeg\tTransfer\tO\n009.jpeg\t-\tO\n009.jpeg\tGame\tO\n009.jpeg\t&\tO\n009.jpeg\tApplication\tO\n009.jpeg\tLed\tO\n009.jpeg\tTouch\tO\n009.jpeg\tGlass\tO\n009.jpeg\t"Change,"\tO\n009.jpeg\tAll\tO\n009.jpeg\tMobile\tO\n009.jpeg\tLed\tO\n009.jpeg\t"Fitting,"\tO\n009.jpeg\tMobile\tO\n009.jpeg\tRepair\tO\n009.jpeg\tTraining\tO\n009.jpeg\t"loor,"\tO\n009.jpeg\tCity\tO\n009.jpeg\tCentre\tO\n009.jpeg\t"Mall,"\tO\n009.jpeg\tOpp.\tO\n009.jpeg\t"mbai-Central,"\tO\n009.jpeg\tMumbai\tO\n009.jpeg\t-\tO\n009.jpeg\t400\tO\n009.jpeg\t8\tO\n009.jpeg\t  \tO\n009.jpeg\t \tO\n009.jpeg\t  \tO\n009.jpeg\t   \tO\n009.jpeg\t  \tO\n009.jpeg\t  \tO\n009.jpeg\t_Ӊ_B:E:S.T.\tO\n010.jpeg\tDr.\tB-NAME\n010.jpeg\tMichael\tI-NAME\n010.jpeg\tDean\tI-NAME\n010.jpeg\tClarinet\tO\n010.jpeg\tPerforming\tO\n010.jpeg\tTeaching\tB-DES\n010.jpeg\tand\tI-DES\n010.jpeg\tConsulting\tI-DES\n010.jpeg\t682.888.7639\tB-PHONE\n010.jpeg\tclarinetmike.com\tB-WEB\n010.jpeg\tclarinetmike.wordpress.com\tB-WEB\n010.jpeg\tclarinetmiketexas@\tB-EMAIL\n010.jpeg\tyahoo.com\tI-EMAIL\n010.jpeg\t \tO\n011.jpeg\ta\tO\n011.jpeg\t:\tO\n011.jpeg\tCell\tO\n011.jpeg\t:\tO\n011.jpeg\t9885050228\tB-PHONE\n011.jpeg\tKrishna\tB-NAME\n011.jpeg\t3257779\tB-PHONE\n011.jpeg\t\\\tO\n011.jpeg\t9393937799\tB-PHONE\n011.jpeg\t \tO\n011.jpeg\t    \tO\n011.jpeg\t \tO\n011.jpeg\t \tO\n011.jpeg\tD.No.\tO\n011.jpeg\t"27-33-19,"\tO\n011.jpeg\tSatnam\tO\n011.jpeg\t"Towers,"\tO\n011.jpeg\tOpp:\tO\n011.jpeg\tBuckingham\tO\n011.jpeg\tPost\tO\n011.jpeg\t"Office,"\tO\n011.jpeg\tGudavallivari\tO\n011.jpeg\t"St.,"\tO\n011.jpeg\t"Governorpeta,"\tO\n011.jpeg\tVijayawada.\tO\n011.jpeg\tat\tO\n012.jpeg\tCell:\tO\n012.jpeg\t7396379143\tB-PHONE\n012.jpeg\t \tO\n013.jpeg\tMobile:73963791\tB-PHONE\n013.jpeg\t43\tO\n013.jpeg\tFLEX.\tO\n013.jpeg\tPRINT\tO\n013.jpeg\taz\tO\n013.jpeg\tDesigning\tO\n013.jpeg\t&\tO\n013.jpeg\tPrinting\tO\n013.jpeg\t \tO\n013.jpeg\t   \tO\n013.jpeg\tCL\tO\n013.jpeg\t \tO\n013.jpeg\tEL\tO\n013.jpeg\t   \tO\n013.jpeg\t \tO\n014.jpeg\tMob:-8445790640\tB-PHONE\n014.jpeg\tSiyalg\tO\n014.jpeg\tAll\tO\n014.jpeg\tKind\tO\n014.jpeg\t"Charger,"\tO\n014.jpeg\t"Earphones,"\tO\n014.jpeg\tMobile\tO\n014.jpeg\t"Photostate,"\tO\n014.jpeg\t&Anygkindlof\tO\n014.jpeg\tOnline\tO\n014.jpeg\tWorks.\tO\n014.jpeg\t \tO\n014.jpeg\t \tO\n015.jpeg\t \tO\n015.jpeg\t4!\tO\n015.jpeg\tShri\tO\n015.jpeg\tGaneshay\tO\n015.jpeg\tNamah\tO\n015.jpeg\t!t\tO\n015.jpeg\tM.\tO\n015.jpeg\t70147-98128\tB-PHONE\n015.jpeg\t \tO\n015.jpeg\tBAJA\tO\n015.jpeg\tDeals\tO\n015.jpeg\tin\tO\n015.jpeg\t:\tO\n015.jpeg\tAll\tO\n015.jpeg\tKinds\tO\n015.jpeg\tof\tO\n015.jpeg\tNew\tO\n015.jpeg\tMobile\tO\n015.jpeg\t"Handset,"\tO\n015.jpeg\tTempered\tO\n015.jpeg\tGlass\tO\n015.jpeg\tFINSERV\tO\n015.jpeg\tFancy\tO\n015.jpeg\t"Covers,"\tO\n015.jpeg\tAccessories\tO\n015.jpeg\tAvailable\tO\n015.jpeg\tHere\tO\n015.jpeg\t \tO\n015.jpeg\tSAMSUNG\tO\n015.jpeg\tOPPO\tO\n015.jpeg\tVivo\tO\n015.jpeg\tJenovo\tO\n015.jpeg\t@\tO\n015.jpeg\tiPhone\tO\n015.jpeg\tmobile\tO\n015.jpeg\tGIONEE\tO\n015.jpeg\t  \tO\n015.jpeg\t \tO\n016.jpeg\t    \tO\n016.jpeg\t91\tB-PHONE\n016.jpeg\t9087253526\tI-PHONE\n016.jpeg\t91\tB-PHONE\n016.jpeg\t9087252666\tI-PHONE\n016.jpeg\toe\tO\n016.jpeg\traghuvijayan104@gmail.com\tB-EMAIL\n017.jpeg\tY-Wireless\tB-ORG\n017.jpeg\tRepair\tI-ORG\n017.jpeg\t \tO\n017.jpeg\t \tO\n017.jpeg\t \tO\n017.jpeg\t \tO\n017.jpeg\t \tO\n017.jpeg\t \tO\n017.jpeg\teee\tO\n017.jpeg\tCertified\tO\n017.jpeg\tTechnician\tO\n017.jpeg\tPhone\tO\n017.jpeg\t\tO\n017.jpeg\tTablet\tO\n017.jpeg\t-\tO\n017.jpeg\tElectronic\tO\n017.jpeg\tRepairs\tO\n017.jpeg\tCall\tO\n017.jpeg\tus\tO\n017.jpeg\t330-270-5060\tB-PHONE\n017.jpeg\tfacebook.com/YoungstownWirelessRepair\tO\n018.jpeg\t \tO\n018.jpeg\tCell\tO\n018.jpeg\tPhone\tB-ORG\n018.jpeg\tRepair\tI-ORG\n018.jpeg\tCenter\tI-ORG\n018.jpeg\t6795\tO\n018.jpeg\tWilson\tO\n018.jpeg\t"Blvd,"\tO\n018.jpeg\tSuite\tO\n018.jpeg\t26\tO\n018.jpeg\tBUY\tO\n018.jpeg\t-\tO\n018.jpeg\tSELL\tO\n018.jpeg\t-\tO\n018.jpeg\tTRADE\tO\n018.jpeg\tFalls\tO\n018.jpeg\t"Church,"\tO\n018.jpeg\tVA\tO\n018.jpeg\t22044\tO\n018.jpeg\tTEL:\tO\n018.jpeg\t571\tB-PHONE\n018.jpeg\t606\tI-PHONE\n018.jpeg\t6636\tI-PHONE\n018.jpeg\t/\tO\n018.jpeg\t571606\tI-PHONE\n018.jpeg\t3445\tI-PHONE\n018.jpeg\t-\tO\n018.jpeg\t"iPhone,"\tO\n018.jpeg\tiPad\tO\n018.jpeg\t02-03-2004\tO\n018.jpeg\t-\tO\n018.jpeg\tHTC\tO\n018.jpeg\tRepair\tO\n018.jpeg\team\tO\n018.jpeg\t-\tO\n018.jpeg\tSamsung\tO\n018.jpeg\tRepair\tO\n018.jpeg\t-\tO\n018.jpeg\tTrackball\tO\n018.jpeg\tRepair\tO\n018.jpeg\thtc\tO\n018.jpeg\t-\tO\n018.jpeg\tCracked\tO\n018.jpeg\tScreens\tO\n018.jpeg\t-\tO\n018.jpeg\tWater\tO\n018.jpeg\tDamage\tO\n018.jpeg\t\tO\n018.jpeg\t-\tO\n018.jpeg\tSpeakers\tO\n018.jpeg\t-\tO\n018.jpeg\tCharger\tO\n018.jpeg\tPort\tO\n018.jpeg\t-\tO\n018.jpeg\tSoftware\tO\n018.jpeg\tUpdate\tO\n018.jpeg\tNOKIA\tO\n018.jpeg\t-\tO\n018.jpeg\tPassword\tO\n018.jpeg\tReset\tO\n018.jpeg\t..and\tO\n018.jpeg\talmost\tO\n018.jpeg\tany\tO\n018.jpeg\thardware\tO\n018.jpeg\tor\tO\n018.jpeg\tsoftware\tO\n018.jpeg\tissue!\tO\n018.jpeg\tEden\tO\n018.jpeg\tCenter\tO\n018.jpeg\t-\tO\n018.jpeg\tSeven\tO\n018.jpeg\tCorner\tO\n018.jpeg\t-\tO\n018.jpeg\tRoute\tO\n018.jpeg\t50\tO\n018.jpeg\t \tO\n020.jpeg\tMOBILE\tB-ORG\n020.jpeg\tREPAIR\tI-ORG\n020.jpeg\tCENTRE\tI-ORG\n020.jpeg\tON-SITE\tO\n020.jpeg\tREPAIRS\tO\n020.jpeg\tWHILE\tO\n020.jpeg\tYOU\tO\n020.jpeg\tWAIT\tO\n020.jpeg\tINSTANT\tO\n020.jpeg\tUNLOCKING\tO\n020.jpeg\tSOLUTIONS\tO\n020.jpeg\tDAMAGED\tO\n020.jpeg\tLCD\tO\n020.jpeg\tSCREENS\tO\n020.jpeg\tREPLACED\tO\n020.jpeg\tWATERILIQUID\tO\n020.jpeg\tDAMAGED\tO\n020.jpeg\tPHONES\tO\n020.jpeg\t"CHARGING,"\tO\n020.jpeg\tAUDIO\tO\n020.jpeg\t&\tO\n020.jpeg\tSIGNAL\tO\n020.jpeg\tPROBLEMS\tO\n020.jpeg\tSOFTWARE\tO\n020.jpeg\tPROBLEMS\tO\n020.jpeg\tREPLACEMENT\tO\n020.jpeg\tLOAN\tO\n020.jpeg\tPHONES\tO\n020.jpeg\tAVAILABLE\tO\n020.jpeg\tWHILE\tO\n020.jpeg\tYOUR\tO\n020.jpeg\tPHONE\tO\n020.jpeg\tIS\tO\n020.jpeg\tBEING\tO\n020.jpeg\tREPAIRED\tO\n020.jpeg\tNO-FIX\tO\n020.jpeg\tNO-FEE\tO\n020.jpeg\t  \tO\n020.jpeg\t  \tO\n020.jpeg\t20\tB-PHONE\n020.jpeg\t87499933\tI-PHONE\n020.jpeg\tWWW.MPRC.CO\tB-WEB\n021.jpeg\tEzy\tB-ORG\n021.jpeg\tFit\tI-ORG\n021.jpeg\t \tO\n021.jpeg\t \tO\n021.jpeg\t  \tO\n021.jpeg\t   \tO\n021.jpeg\t    \tO\n021.jpeg\t  \tO\n021.jpeg\t \tO\n021.jpeg\t+\tO\n021.jpeg\tSenice\tO\n021.jpeg\t+\tO\n021.jpeg\tBrakes\tO\n021.jpeg\t \tO\n021.jpeg\t91\tO\n021.jpeg\tPortland\tO\n021.jpeg\t"Rd,"\tO\n021.jpeg\tHucknall\tO\n021.jpeg\tTiming\tO\n021.jpeg\tBelts\tO\n021.jpeg\tNG15\tO\n021.jpeg\t7DS\tO\n021.jpeg\t+\tO\n021.jpeg\tSuspension\tO\n021.jpeg\tOpp\tO\n021.jpeg\tSandicliffe\tO\n021.jpeg\tFord\tO\n021.jpeg\t+\tO\n021.jpeg\tDiagnostics\tO\n021.jpeg\t+\tO\n021.jpeg\tBatteries\tO\n021.jpeg\tFree\tO\n021.jpeg\tBrake\tO\n021.jpeg\tCheck\tO\n021.jpeg\t \tO\n021.jpeg\t \tO\n021.jpeg\tEmail:\tO\n021.jpeg\tco.uk\tO\n021.jpeg\tWeb:\tO\n021.jpeg\twww.ezyfitautocentre.co.uk\tB-WEB\n022.jpeg\tDale\tB-NAME\n022.jpeg\tSteffen\tI-NAME\n022.jpeg\tClub\tB-DES\n022.jpeg\tManager\tI-DES\n022.jpeg\t \tO\n022.jpeg\tPLANET\tO\n022.jpeg\tFITNESS\tO\n022.jpeg\t|\tO\n022.jpeg\tHOME\tO\n022.jpeg\tof\tO\n022.jpeg\tthe\tO\n022.jpeg\tJUDGEMENT\tO\n022.jpeg\tFREE\tO\n022.jpeg\tZONE\tO\n022.jpeg\t9652\tO\n022.jpeg\tS.\tO\n022.jpeg\tRoberts\tO\n022.jpeg\tRd.\tO\n022.jpeg\t|\tO\n022.jpeg\tHickory\tO\n022.jpeg\t"Hills,"\tO\n022.jpeg\tIL\tO\n022.jpeg\t60457\tO\n022.jpeg\tAyes\tO\n022.jpeg\tP:\tO\n022.jpeg\t708.598.1010\tB-PHONE\n022.jpeg\tplanetfitness.com\tB-WEB\n023.jpeg\tHilton\tB-ORG\n023.jpeg\tOak\tI-ORG\n023.jpeg\tLawn\tI-ORG\n023.jpeg\tHeather\tB-NAME\n023.jpeg\tStevens\tI-NAME\n023.jpeg\tCatering\tB-DES\n023.jpeg\tManager\tI-DES\n023.jpeg\t9333\tO\n023.jpeg\tSouth\tO\n023.jpeg\tCicero\tO\n023.jpeg\tAvenue\tO\n023.jpeg\tOak\tO\n023.jpeg\t"Lawn,"\tO\n023.jpeg\tIL\tO\n023.jpeg\t60453\tO\n023.jpeg\tTel:\tO\n023.jpeg\t708\tB-PHONE\n023.jpeg\t425\tI-PHONE\n023.jpeg\t7800\tI-PHONE\n023.jpeg\tDirect\tO\n023.jpeg\tLine:\tO\n023.jpeg\t708\tO\n023.jpeg\t229\tO\n023.jpeg\t8859\tO\n023.jpeg\tFax:\tO\n023.jpeg\t708\tO\n023.jpeg\t229\tO\n023.jpeg\t8858\tO\n023.jpeg\temail:\tO\n023.jpeg\theather.stevens@hilton.com\tB-EMAIL\n023.jpeg\tHONORS\tO\n023.jpeg\tHILTON\tO\n023.jpeg\tofficial\tO\n023.jpeg\tSponsor\tO\n024.jpeg\t-\tO\n024.jpeg\tMobile:\tB-ORG\n024.jpeg\tlimited\tI-ORG\n024.jpeg\tMarian\tB-NAME\n024.jpeg\tPiontek\tI-NAME\n024.jpeg\t-708\tB-PHONE\n024.jpeg\t890-8911\tI-PHONE\n024.jpeg\t7884\tO\n024.jpeg\tN\tO\n024.jpeg\tMilwaukee\tO\n024.jpeg\tAve\tO\n024.jpeg\t"Niles,"\tO\n024.jpeg\tIL\tO\n024.jpeg\t60714\tO\n024.jpeg\tmpiontek@neptunemobile.com\tB-EMAIL\n025.jpeg\tFURNITURE\tO\n025.jpeg\t \tO\n025.jpeg\tVictor\tB-NAME\n025.jpeg\tHarris\tI-NAME\n025.jpeg\tJr\tI-NAME\n025.jpeg\tSales\tB-DES\n025.jpeg\tAssociate\tB-DES\n025.jpeg\ttel\tO\n025.jpeg\t630.783.2346\tB-PHONE\n025.jpeg\tfax\tO\n025.jpeg\t630.783.1175\tO\n025.jpeg\tAshley\tB-ORG\n025.jpeg\tFurniture\tI-ORG\n025.jpeg\tHomeStore\tI-ORG\n025.jpeg\t875\tO\n025.jpeg\tE\tO\n025.jpeg\tBoughton\tO\n025.jpeg\tRoad\tO\n025.jpeg\t"Bolingbrook,"\tO\n025.jpeg\tIL\tO\n025.jpeg\t60440\tO\n025.jpeg\twww.ashleyfurniturehomestore.com\tB-EMAIL\n027.jpeg\tWALT\tB-ORG\n027.jpeg\tDISNEY\tI-ORG\n027.jpeg\tPRODUCTIONS\tO\n027.jpeg\tKee۪\tO\n027.jpeg\tJohn\tB-NAME\n027.jpeg\tF.\tI-NAME\n027.jpeg\tCurry\tI-NAME\n027.jpeg\tDirector\tB-DES\n027.jpeg\t2%)\tO\n027.jpeg\tHotel\tO\n027.jpeg\tDivision\tO\n027.jpeg\tams\tO\n027.jpeg\t-213\tB-PHONE\n027.jpeg\t245-8951\tI-PHONE\n027.jpeg\t500\tO\n027.jpeg\tSO.\tO\n027.jpeg\tBUENA\tO\n027.jpeg\tVISTA\tO\n027.jpeg\tST.\tO\n027.jpeg\t+\tO\n027.jpeg\t"BURBANK,"\tO\n027.jpeg\tCALIFORNIA\tO\n027.jpeg\t91503\tO\n028.jpeg\tKUNUNURRA\tO\n028.jpeg\tRachell\tB-NAME\n028.jpeg\tFewster\tI-NAME\n028.jpeg\tShop\tO\n028.jpeg\t112b\tO\n028.jpeg\tCoolibah\tO\n028.jpeg\tDrive\tO\n028.jpeg\t418\tO\n028.jpeg\t894\tO\n028.jpeg\t400\tO\n028.jpeg\tKununurrra\tO\n028.jpeg\tWA\tO\n028.jpeg\t6743\tO\n028.jpeg\tPhone:\tO\n028.jpeg\t-8\tB-PHONE\n028.jpeg\t9168\tI-PHONE\n028.jpeg\t1737\tI-PHONE\n028.jpeg\tFax:\tO\n028.jpeg\t-8\tO\n028.jpeg\t9169\tO\n028.jpeg\t3940\tO\n028.jpeg\tEmail:\tO\n028.jpeg\tinfo@subwaykununurra.com.au\tB-EMAIL\n028.jpeg\t \tO\n030.jpeg\th\tO\n030.jpeg\tManaging\tB-DES\n030.jpeg\tDirector\tI-DES\n030.jpeg\tmail:\tO\n030.jpeg\tcustomercare@sho|\tB-EMAIL\n030.jpeg\t4reebok.com\tI-EMAIL\n030.jpeg\tShreshth\tB-NAME\n030.jpeg\tParekh\tI-NAME\n030.jpeg\tto\tO\n030.jpeg\thead\tO\n030.jpeg\tIndian\tO\n030.jpeg\toperations\tO\n030.jpeg\tReebok\tO\n030.jpeg\t \tO\n030.jpeg\tadd;\tO\n030.jpeg\t"326,"\tO\n030.jpeg\tThird\tO\n030.jpeg\t"Floor,"\tO\n030.jpeg\tChintamani\tO\n030.jpeg\t"Plaza,"\tO\n030.jpeg\t"Bewing,"\tO\n030.jpeg\tAndheri\tO\n030.jpeg\t"Chakala,"\tO\n030.jpeg\tMumbai\tO\n030.jpeg\tReebok\tB-ORG\n030.jpeg\tIndia\tI-ORG\n030.jpeg\tLtd.\tI-ORG\n031.jpeg\tGeneral\tB-DES\n031.jpeg\tManager\tI-DES\n031.jpeg\tDomino\'s\tB-ORG\n031.jpeg\t54321\tO\n031.jpeg\tCaesar\tO\n031.jpeg\tBlvd.\tO\n031.jpeg\tGardena\tO\n031.jpeg\t"Fresh,"\tO\n031.jpeg\tCA\tO\n031.jpeg\t92337\tO\n031.jpeg\tMordan\tO\n031.jpeg\tPisa\tO\n031.jpeg\tStore:\tO\n031.jpeg\t562-543-7689\tO\n031.jpeg\tCell:\tO\n031.jpeg\t562-456-3210\tB-PHONE\n031.jpeg\tmpisa@dominos.com\tB-EMAIL\n032.jpeg\t \tO\n032.jpeg\t \tO\n032.jpeg\tae\tO\n032.jpeg\tBe\tO\n032.jpeg\t3\tO\n032.jpeg\t \tO\n033.jpeg\t \tO\n033.jpeg\tPRAKASH\tB-NAME\n033.jpeg\tKHEDKAR\tI-NAME\n033.jpeg\t(Sales\tB-DES\n033.jpeg\tOfficer)\tI-DES\n033.jpeg\tM.\tO\n033.jpeg\t9227576803\tO\n033.jpeg\ta\tO\n033.jpeg\tLOAN\tO\n033.jpeg\tAGAINST\tO\n033.jpeg\tPROPERTY\tO\n033.jpeg\tBHAVYA\tB-ORG\n033.jpeg\tFINANCIAL\tI-ORG\n033.jpeg\tSERVICES\tI-ORG\n033.jpeg\tHDFC\tO\n033.jpeg\tBANK\tO\n033.jpeg\t"ASSOCIATE,"\tO\n033.jpeg\tMORTGAGE\tO\n033.jpeg\tLOANS\tO\n033.jpeg\t"1009-1010,"\tO\n033.jpeg\tCity\tO\n033.jpeg\tCentre\tO\n033.jpeg\t"Market,"\tO\n033.jpeg\tOpp.\tO\n033.jpeg\tA.V.\tO\n033.jpeg\t"Sons,"\tO\n033.jpeg\tGhod\tO\n033.jpeg\tDod\tO\n033.jpeg\t"Road,"\tO\n033.jpeg\tParle\tO\n033.jpeg\t"Point,"\tO\n033.jpeg\t"Surat-395007,"\tO\n033.jpeg\tPh.\tO\n033.jpeg\t261\tB-PHONE\n033.jpeg\t2210142\tI-PHONE\n033.jpeg\te\tO\n033.jpeg\tmail\tO\n033.jpeg\t:-\tO\n033.jpeg\tpykhedkar07@yahoo.com.\tB-EMAIL\n034.jpeg\t \tO\n034.jpeg\t   \tO\n034.jpeg\t \tO\n034.jpeg\t \tO\n034.jpeg\t \tO\n034.jpeg\t \tO\n034.jpeg\t \tO\n034.jpeg\t  \tO\n034.jpeg\t  \tO\n034.jpeg\t  \tO\n034.jpeg\t \tO\n034.jpeg\tJ\tO\n034.jpeg\t"laptop,"\tO\n034.jpeg\tComputer\tO\n034.jpeg\t&\tO\n034.jpeg\tPrinter\tO\n034.jpeg\tSales\tO\n034.jpeg\tJ\tO\n034.jpeg\tLaptop\tO\n034.jpeg\t&\tO\n034.jpeg\tComputer\tO\n034.jpeg\tService\tO\n034.jpeg\tJ\tO\n034.jpeg\tData\tO\n034.jpeg\tRecovery\tO\n034.jpeg\t&\tO\n034.jpeg\tNetworking\tO\n034.jpeg\t/\tO\n034.jpeg\tAMC\tO\n034.jpeg\t&\tO\n034.jpeg\tHouse\tO\n034.jpeg\tRepairs\tO\n034.jpeg\tService\tO\n034.jpeg\tJ\tO\n034.jpeg\tPrinter\tO\n034.jpeg\tRepairs\tO\n034.jpeg\t@\tO\n034.jpeg\tToner\tO\n034.jpeg\tRefiling\tO\n034.jpeg\tJ\tO\n034.jpeg\tAll\tO\n034.jpeg\tType\tO\n034.jpeg\tof\tO\n034.jpeg\tAccessories\tO\n034.jpeg\t/\tO\n034.jpeg\tCCTv.\tO\n034.jpeg\tCamera\tO\n034.jpeg\t/\tO\n034.jpeg\tWeb\tO\n034.jpeg\tHosting\tO\n034.jpeg\t&\tO\n034.jpeg\tDomain\tO\n034.jpeg\tRegister\tO\n034.jpeg\tJ\tO\n034.jpeg\tInstant\tO\n034.jpeg\tWeb\tO\n034.jpeg\tDevelopment\tO\n034.jpeg\t/\tO\n034.jpeg\tSoftware\tO\n034.jpeg\tDevelopment\tO\n034.jpeg\t \tO\n034.jpeg\tinfoTech\tO\n034.jpeg\tDo\tO\n034.jpeg\tSomething\tO\n034.jpeg\tBig\tO\n034.jpeg\t9898\tB-PHONE\n034.jpeg\t24\tI-PHONE\n034.jpeg\t4020\tI-PHONE\n034.jpeg\t9033\tI-PHONE\n034.jpeg\t25\tI-PHONE\n034.jpeg\t1418\tI-PHONE\n034.jpeg\t\tO\n034.jpeg\tperfectinfotech2013@gmail.com\tB-EMAIL\n034.jpeg\t@\tO\n034.jpeg\t"124,"\tO\n034.jpeg\tGurukrupa\tO\n034.jpeg\t"Complex,"\tO\n034.jpeg\tTalod-Majara\tO\n034.jpeg\tRoad\tO\n034.jpeg\t"Beside,"\tO\n034.jpeg\tMamlatdar\tO\n034.jpeg\t"Kacheri,"\tO\n034.jpeg\tTalod.\tO\n034.jpeg\t \tO\n035.jpeg\tCraig\tB-NAME\n035.jpeg\tForman\tI-NAME\n035.jpeg\tdi.\tO\n035.jpeg\tService\tB-ORG\n035.jpeg\tMax\tI-ORG\n035.jpeg\tLLC\tI-ORG\n035.jpeg\t25\tO\n035.jpeg\tPine\tO\n035.jpeg\tStreet\tO\n035.jpeg\t-\tO\n035.jpeg\tSuite\tO\n035.jpeg\t8\tO\n035.jpeg\tFacility\tO\n035.jpeg\tMaintenance\tO\n035.jpeg\t&\tO\n035.jpeg\tJanitorial\tO\n035.jpeg\tand\tO\n035.jpeg\tSupplies\tO\n035.jpeg\tRockaway\tO\n035.jpeg\tNJ\tO\n035.jpeg\t7866\tO\n035.jpeg\tOffice\tO\n035.jpeg\t-973\tO\n035.jpeg\t627-9292\tO\n035.jpeg\tFax\tO\n035.jpeg\t-973\tO\n035.jpeg\t210-9160\tO\n035.jpeg\tCell\tO\n035.jpeg\t-973\tB-PHONE\n035.jpeg\t876-8402\tI-PHONE\n035.jpeg\tcraig@servicemaxnj.com\tB-EMAIL\n035.jpeg\twww.servicemaxnj.com\tB-WEB\n035.jpeg\t \tO\n036.jpeg\t \tO\n036.jpeg\t8\tO\n036.jpeg\tStanford\tO\n036.jpeg\tStanford\tB-ORG\n036.jpeg\tMEDICINE\tI-ORG\n036.jpeg\tCardiovascular\tI-ORG\n036.jpeg\tInstitute\tI-ORG\n036.jpeg\tJoseph\tB-NAME\n036.jpeg\tC.\tI-NAME\n036.jpeg\t"Wu,"\tI-NAME\n036.jpeg\t"MD,"\tO\n036.jpeg\tPhD\tO\n036.jpeg\t"Director,"\tB-DES\n036.jpeg\tStanford\tO\n036.jpeg\tCardiovascular\tO\n036.jpeg\tInstitute\tO\n036.jpeg\tProfessor\tO\n036.jpeg\tMedicine\tO\n036.jpeg\t(Cardiology)\tO\n036.jpeg\t&\tO\n036.jpeg\tRadiology\tO\n036.jpeg\t265\tO\n036.jpeg\tCampus\tO\n036.jpeg\t"Drive,"\tO\n036.jpeg\tG-1120B\tO\n036.jpeg\tTel:\tO\n036.jpeg\t-650\tB-PHONE\n036.jpeg\t736-2246\tI-PHONE\n036.jpeg\t"Stanford,"\tO\n036.jpeg\tCA\tO\n036.jpeg\t"94305,"\tO\n036.jpeg\tMC-5454\tO\n036.jpeg\tFax:\tO\n036.jpeg\t-650\tO\n036.jpeg\t736-0234\tO\n036.jpeg\thttp://wulab.stanfordedu\tB-WEB\n036.jpeg\tCVI:\tO\n036.jpeg\t-650\tO\n036.jpeg\t725-7964\tO\n036.jpeg\te-mail:\tO\n036.jpeg\tjoewu@stanford.edu\tB-EMAIL\n036.jpeg\thet\tO\n036.jpeg\t \tO\n036.jpeg\t://evi.stanford.edu\tO\n036.jpeg\t \tO\n037.jpeg\t8281604684\tB-PHONE\n037.jpeg\t9061825334\tB-PHONE\n037.jpeg\t9544851506\tB-PHONE\n037.jpeg\t|\tO\n037.jpeg\tyou\tO\n037.jpeg\tdream\tO\n037.jpeg\t"it,"\tO\n037.jpeg\twe\tO\n037.jpeg\tmake\tO\n037.jpeg\tit\tO\n037.jpeg\tSGRAPHICS\tO\n037.jpeg\tManathala\tO\n037.jpeg\tIsons\tO\n037.jpeg\t"Arcade,"\tO\n037.jpeg\tAbove\tO\n037.jpeg\tFedaral\tO\n037.jpeg\t"Bank,"\tO\n037.jpeg\tPerumanoorkulam\tO\n037.jpeg\t"Jn.,"\tO\n037.jpeg\tManarcad-Kottayam\tO\n037.jpeg\tTel\tO\n037.jpeg\t:\tO\n037.jpeg\t481\tO\n037.jpeg\t2373840\tO\n037.jpeg\tvibrantgraphicz@gmail.com\tO\n037.jpeg\t  \tO\n037.jpeg\tSHE\tO\n037.jpeg\tFLEX\tO\n037.jpeg\t&\tO\n037.jpeg\tVINYL\tO\n037.jpeg\tPRINTING\tO\n037.jpeg\tCLOTH\tO\n037.jpeg\tPRINTING\tO\n037.jpeg\tFLEX\tO\n037.jpeg\tBOARDS\tO\n037.jpeg\tLIGHT\tO\n037.jpeg\tBOARDS\tO\n037.jpeg\tWEDDING\tO\n037.jpeg\tCARDS\tO\n037.jpeg\tVISITING\tO\n037.jpeg\tCARDS\tO\n037.jpeg\tSTICKER\tO\n037.jpeg\tCUTTING\tO\n037.jpeg\t"NOTICE,"\tO\n037.jpeg\

In [60]:
print(text)

id	text	tag
000.jpeg	 	O
000.jpeg	.	O
000.jpeg	040-4852	B-PHONE
000.jpeg	"8881,"	I-PHONE
000.jpeg	90309	B-PHONE
000.jpeg	52549	I-PHONE
000.jpeg	Fi	O
000.jpeg	/laurelsoverseaseducation	O
000.jpeg	@:	O
000.jpeg	LAURELS	B-ORG
000.jpeg	OVERSEAS	I-ORG
000.jpeg	EDUCATIONAL	I-ORG
000.jpeg	CONSULTANCY	I-ORG
000.jpeg	PVT.	I-ORG
000.jpeg	LTD.	I-ORG
000.jpeg	Sea	O
000.jpeg	|	O
000.jpeg	U.K	O
000.jpeg	AUSTRALIA	O
000.jpeg	CANADA	O
000.jpeg	IRELAND	O
000.jpeg	 	O
000.jpeg	 	O
000.jpeg	 	O
000.jpeg	 	O
000.jpeg	 	O
000.jpeg	 	O
000.jpeg	www.laurelseducation.com	B-WEB
000.jpeg	)%info@laurelseducation.com	B-EMAIL
000.jpeg	 	O
001.jpeg	john	B-NAME
001.jpeg	smith	I-NAME
001.jpeg	marketing	B-DES
001.jpeg	manager	I-DES
001.jpeg	web:	O
001.jpeg	www.psdgraphics.com	B-WEB
001.jpeg	phone:	O
001.jpeg	123-456-7890	B-PHONE
001.jpeg	mail:	O
001.jpeg	email@psdgraphics.com	B-EMAIL
002.jpeg	    	O
002.jpeg	   	O
002.jpeg	Sau	O
002.jpeg	0	O
002.jpeg	98489	B-PHONE
002.jpeg	24441	I-PHONE
002.jpeg	dy	O
002.jpeg	"08672,"	O
002.jpeg	224441	O
002.jpeg	/ENKATESWAPA	B-ORG
002.jpeg	&	O
002.jpeg	wie	O
002.jpeg	 	O
002.jpeg	=	O
002.jpeg	 	O
003.jpeg	Prasad	B-NAME
003.jpeg	@	O
003.jpeg	"9,96,31,73,53,59,49,04,00,000"	O
003.jpeg	  	O
003.jpeg	   	O
003.jpeg	i	O
003.jpeg	Flex	O
003.jpeg	Design	O
003.jpeg	#	O
003.jpeg	Album	O
003.jpeg	Design	O
003.jpeg		O
003.jpeg	Visiting	O
003.jpeg	Cards	O
003.jpeg	DTP	O
003.jpeg	Works	O
003.jpeg	(Telugu	O
003.jpeg	&	O
003.jpeg	English)	O
003.jpeg	 	O
003.jpeg	 	O
003.jpeg	 	O
003.jpeg	 	O
004.jpeg	<=>	O
004.jpeg	Madison	B-ORG
004.jpeg	Yacht	I-ORG
004.jpeg	Sales	I-ORG
004.jpeg	Paul	B-NAME
004.jpeg	Madison	I-NAME
004.jpeg	Yacht	B-DES
004.jpeg	Broker	I-DES
004.jpeg	-	O
004.jpeg	Northeast	O
004.jpeg	Region	O
004.jpeg	   	O
004.jpeg	  	O
004.jpeg	 	O
004.jpeg	Fax:	O
004.jpeg	718-444-1206	B-PHONE
004.jpeg	  	O
007.jpeg	www	B-WEB
007.jpeg	phototomics.com	I-WEB
007.jpeg	PHOTOT	B-ORG
007.jpeg	Thomas	B-NAME
007.jpeg	Atkins	I-NAME
007.jpeg	Photographer	B-DES
007.jpeg	and	I-DES
007.jpeg	Digital	I-DES
007.jpeg	Artist	I-DES
007.jpeg	tatkins@phototomics.com	B-EMAIL
007.jpeg	Phototomics	O
007.jpeg	3419	O
007.jpeg	Via	O
007.jpeg	Lido	O
007.jpeg	#340	O
007.jpeg	Newport	O
007.jpeg	Beach	O
007.jpeg	CA	O
007.jpeg	-	O
007.jpeg	California	O
007.jpeg	92663	O
007.jpeg	 	O
008.jpeg	 	O
008.jpeg	Reddy	O
008.jpeg	9866186785	B-PHONE
008.jpeg	   	O
008.jpeg	 	O
008.jpeg	Opp	O
008.jpeg	Ramakrishna	O
008.jpeg	"Theatre,Main"	O
008.jpeg	Road	O
008.jpeg	"Peddapalli,"	O
008.jpeg	Dist	O
008.jpeg	:	O
008.jpeg	"Karimnagar,"	O
008.jpeg	Telangana	O
008.jpeg	-	O
008.jpeg	505172	O
008.jpeg	email	O
008.jpeg	:	O
008.jpeg	srihithaads.pdpl@	B-EMAIL
008.jpeg	gmail.com	I-EMAIL
008.jpeg	 	O
009.jpeg	Saja	B-NAME
009.jpeg	(Vik):	O
009.jpeg	990083000	B-PHONE
009.jpeg	G.S.M.	B-ORG
009.jpeg	BOOSTER	I-ORG
009.jpeg	1)	O
009.jpeg	All	O
009.jpeg	Types	O
009.jpeg	of	O
009.jpeg	Mobile	O
009.jpeg	"Repair,"	O
009.jpeg		O
009.jpeg	Data	O
009.jpeg	Transfer	O
009.jpeg	-	O
009.jpeg	Game	O
009.jpeg	&	O
009.jpeg	Application	O
009.jpeg	Led	O
009.jpeg	Touch	O
009.jpeg	Glass	O
009.jpeg	"Change,"	O
009.jpeg	All	O
009.jpeg	Mobile	O
009.jpeg	Led	O
009.jpeg	"Fitting,"	O
009.jpeg	Mobile	O
009.jpeg	Repair	O
009.jpeg	Training	O
009.jpeg	"loor,"	O
009.jpeg	City	O
009.jpeg	Centre	O
009.jpeg	"Mall,"	O
009.jpeg	Opp.	O
009.jpeg	"mbai-Central,"	O
009.jpeg	Mumbai	O
009.jpeg	-	O
009.jpeg	400	O
009.jpeg	8	O
009.jpeg	  	O
009.jpeg	 	O
009.jpeg	  	O
009.jpeg	   	O
009.jpeg	  	O
009.jpeg	  	O
009.jpeg	_Ӊ_B:E:S.T.	O
010.jpeg	Dr.	B-NAME
010.jpeg	Michael	I-NAME
010.jpeg	Dean	I-NAME
010.jpeg	Clarinet	O
010.jpeg	Performing	O
010.jpeg	Teaching	B-DES
010.jpeg	and	I-DES
010.jpeg	Consulting	I-DES
010.jpeg	682.888.7639	B-PHONE
010.jpeg	clarinetmike.com	B-WEB
010.jpeg	clarinetmike.wordpress.com	B-WEB
010.jpeg	clarinetmiketexas@	B-EMAIL
010.jpeg	yahoo.com	I-EMAIL
010.jpeg	 	O
011.jpeg	a	O
011.jpeg	:	O
011.jpeg	Cell	O
011.jpeg	:	O
011.jpeg	9885050228	B-PHONE
011.jpeg	Krishna	B-NAME
011.jpeg	3257779	B-PHONE
011.jpeg	\	O
011.jpeg	9393937799	B-PHONE
011.jpeg	 	O
011.jpeg	    	O
011.jpeg	 	O
011.jpeg	 	O
011.jpeg	D.No.	O
011.jpeg	"27-33-19,"	O
011.jpeg	Satnam	O
011.jpeg	"Towers,"	O
011.jpeg	Opp:	O
011.jpeg	Buckingham	O
011.jpeg	Post	O
011.jpeg	"Office,"	O
011.jpeg	Gudavallivari	O
011.jpeg	"St.,"	O
011.jpeg	"Governorpeta,"	O
011.jpeg	Vijayawada.	O
011.jpeg	at	O
012.jpeg	Cell:	O
012.jpeg	7396379143	B-PHONE
012.jpeg	 	O
013.jpeg	Mobile:73963791	B-PHONE
013.jpeg	43	O
013.jpeg	FLEX.	O
013.jpeg	PRINT	O
013.jpeg	az	O
013.jpeg	Designing	O
013.jpeg	&	O
013.jpeg	Printing	O
013.jpeg	 	O
013.jpeg	   	O
013.jpeg	CL	O
013.jpeg	 	O
013.jpeg	EL	O
013.jpeg	   	O
013.jpeg	 	O
014.jpeg	Mob:-8445790640	B-PHONE
014.jpeg	Siyalg	O
014.jpeg	All	O
014.jpeg	Kind	O
014.jpeg	"Charger,"	O
014.jpeg	"Earphones,"	O
014.jpeg	Mobile	O
014.jpeg	"Photostate,"	O
014.jpeg	&Anygkindlof	O
014.jpeg	Online	O
014.jpeg	Works.	O
014.jpeg	 	O
014.jpeg	 	O
015.jpeg	 	O
015.jpeg	4!	O
015.jpeg	Shri	O
015.jpeg	Ganeshay	O
015.jpeg	Namah	O
015.jpeg	!t	O
015.jpeg	M.	O
015.jpeg	70147-98128	B-PHONE
015.jpeg	 	O
015.jpeg	BAJA	O
015.jpeg	Deals	O
015.jpeg	in	O
015.jpeg	:	O
015.jpeg	All	O
015.jpeg	Kinds	O
015.jpeg	of	O
015.jpeg	New	O
015.jpeg	Mobile	O
015.jpeg	"Handset,"	O
015.jpeg	Tempered	O
015.jpeg	Glass	O
015.jpeg	FINSERV	O
015.jpeg	Fancy	O
015.jpeg	"Covers,"	O
015.jpeg	Accessories	O
015.jpeg	Available	O
015.jpeg	Here	O
015.jpeg	 	O
015.jpeg	SAMSUNG	O
015.jpeg	OPPO	O
015.jpeg	Vivo	O
015.jpeg	Jenovo	O
015.jpeg	@	O
015.jpeg	iPhone	O
015.jpeg	mobile	O
015.jpeg	GIONEE	O
015.jpeg	  	O
015.jpeg	 	O
016.jpeg	    	O
016.jpeg	91	B-PHONE
016.jpeg	9087253526	I-PHONE
016.jpeg	91	B-PHONE
016.jpeg	9087252666	I-PHONE
016.jpeg	oe	O
016.jpeg	raghuvijayan104@gmail.com	B-EMAIL
017.jpeg	Y-Wireless	B-ORG
017.jpeg	Repair	I-ORG
017.jpeg	 	O
017.jpeg	 	O
017.jpeg	 	O
017.jpeg	 	O
017.jpeg	 	O
017.jpeg	 	O
017.jpeg	eee	O
017.jpeg	Certified	O
017.jpeg	Technician	O
017.jpeg	Phone	O
017.jpeg		O
017.jpeg	Tablet	O
017.jpeg	-	O
017.jpeg	Electronic	O
017.jpeg	Repairs	O
017.jpeg	Call	O
017.jpeg	us	O
017.jpeg	330-270-5060	B-PHONE
017.jpeg	facebook.com/YoungstownWirelessRepair	O
018.jpeg	 	O
018.jpeg	Cell	O
018.jpeg	Phone	B-ORG
018.jpeg	Repair	I-ORG
018.jpeg	Center	I-ORG
018.jpeg	6795	O
018.jpeg	Wilson	O
018.jpeg	"Blvd,"	O
018.jpeg	Suite	O
018.jpeg	26	O
018.jpeg	BUY	O
018.jpeg	-	O
018.jpeg	SELL	O
018.jpeg	-	O
018.jpeg	TRADE	O
018.jpeg	Falls	O
018.jpeg	"Church,"	O
018.jpeg	VA	O
018.jpeg	22044	O
018.jpeg	TEL:	O
018.jpeg	571	B-PHONE
018.jpeg	606	I-PHONE
018.jpeg	6636	I-PHONE
018.jpeg	/	O
018.jpeg	571606	I-PHONE
018.jpeg	3445	I-PHONE
018.jpeg	-	O
018.jpeg	"iPhone,"	O
018.jpeg	iPad	O
018.jpeg	02-03-2004	O
018.jpeg	-	O
018.jpeg	HTC	O
018.jpeg	Repair	O
018.jpeg	eam	O
018.jpeg	-	O
018.jpeg	Samsung	O
018.jpeg	Repair	O
018.jpeg	-	O
018.jpeg	Trackball	O
018.jpeg	Repair	O
018.jpeg	htc	O
018.jpeg	-	O
018.jpeg	Cracked	O
018.jpeg	Screens	O
018.jpeg	-	O
018.jpeg	Water	O
018.jpeg	Damage	O
018.jpeg		O
018.jpeg	-	O
018.jpeg	Speakers	O
018.jpeg	-	O
018.jpeg	Charger	O
018.jpeg	Port	O
018.jpeg	-	O
018.jpeg	Software	O
018.jpeg	Update	O
018.jpeg	NOKIA	O
018.jpeg	-	O
018.jpeg	Password	O
018.jpeg	Reset	O
018.jpeg	..and	O
018.jpeg	almost	O
018.jpeg	any	O
018.jpeg	hardware	O
018.jpeg	or	O
018.jpeg	software	O
018.jpeg	issue!	O
018.jpeg	Eden	O
018.jpeg	Center	O
018.jpeg	-	O
018.jpeg	Seven	O
018.jpeg	Corner	O
018.jpeg	-	O
018.jpeg	Route	O
018.jpeg	50	O
018.jpeg	 	O
020.jpeg	MOBILE	B-ORG
020.jpeg	REPAIR	I-ORG
020.jpeg	CENTRE	I-ORG
020.jpeg	ON-SITE	O
020.jpeg	REPAIRS	O
020.jpeg	WHILE	O
020.jpeg	YOU	O
020.jpeg	WAIT	O
020.jpeg	INSTANT	O
020.jpeg	UNLOCKING	O
020.jpeg	SOLUTIONS	O
020.jpeg	DAMAGED	O
020.jpeg	LCD	O
020.jpeg	SCREENS	O
020.jpeg	REPLACED	O
020.jpeg	WATERILIQUID	O
020.jpeg	DAMAGED	O
020.jpeg	PHONES	O
020.jpeg	"CHARGING,"	O
020.jpeg	AUDIO	O
020.jpeg	&	O
020.jpeg	SIGNAL	O
020.jpeg	PROBLEMS	O
020.jpeg	SOFTWARE	O
020.jpeg	PROBLEMS	O
020.jpeg	REPLACEMENT	O
020.jpeg	LOAN	O
020.jpeg	PHONES	O
020.jpeg	AVAILABLE	O
020.jpeg	WHILE	O
020.jpeg	YOUR	O
020.jpeg	PHONE	O
020.jpeg	IS	O
020.jpeg	BEING	O
020.jpeg	REPAIRED	O
020.jpeg	NO-FIX	O
020.jpeg	NO-FEE	O
020.jpeg	  	O
020.jpeg	  	O
020.jpeg	20	B-PHONE
020.jpeg	87499933	I-PHONE
020.jpeg	WWW.MPRC.CO	B-WEB
021.jpeg	Ezy	B-ORG
021.jpeg	Fit	I-ORG
021.jpeg	 	O
021.jpeg	 	O
021.jpeg	  	O
021.jpeg	   	O
021.jpeg	    	O
021.jpeg	  	O
021.jpeg	 	O
021.jpeg	+	O
021.jpeg	Senice	O
021.jpeg	+	O
021.jpeg	Brakes	O
021.jpeg	 	O
021.jpeg	91	O
021.jpeg	Portland	O
021.jpeg	"Rd,"	O
021.jpeg	Hucknall	O
021.jpeg	Timing	O
021.jpeg	Belts	O
021.jpeg	NG15	O
021.jpeg	7DS	O
021.jpeg	+	O
021.jpeg	Suspension	O
021.jpeg	Opp	O
021.jpeg	Sandicliffe	O
021.jpeg	Ford	O
021.jpeg	+	O
021.jpeg	Diagnostics	O
021.jpeg	+	O
021.jpeg	Batteries	O
021.jpeg	Free	O
021.jpeg	Brake	O
021.jpeg	Check	O
021.jpeg	 	O
021.jpeg	 	O
021.jpeg	Email:	O
021.jpeg	co.uk	O
021.jpeg	Web:	O
021.jpeg	www.ezyfitautocentre.co.uk	B-WEB
022.jpeg	Dale	B-NAME
022.jpeg	Steffen	I-NAME
022.jpeg	Club	B-DES
022.jpeg	Manager	I-DES
022.jpeg	 	O
022.jpeg	PLANET	O
022.jpeg	FITNESS	O
022.jpeg	|	O
022.jpeg	HOME	O
022.jpeg	of	O
022.jpeg	the	O
022.jpeg	JUDGEMENT	O
022.jpeg	FREE	O
022.jpeg	ZONE	O
022.jpeg	9652	O
022.jpeg	S.	O
022.jpeg	Roberts	O
022.jpeg	Rd.	O
022.jpeg	|	O
022.jpeg	Hickory	O
022.jpeg	"Hills,"	O
022.jpeg	IL	O
022.jpeg	60457	O
022.jpeg	Ayes	O
022.jpeg	P:	O
022.jpeg	708.598.1010	B-PHONE
022.jpeg	planetfitness.com	B-WEB
023.jpeg	Hilton	B-ORG
023.jpeg	Oak	I-ORG
023.jpeg	Lawn	I-ORG
023.jpeg	Heather	B-NAME
023.jpeg	Stevens	I-NAME
023.jpeg	Catering	B-DES
023.jpeg	Manager	I-DES
023.jpeg	9333	O
023.jpeg	South	O
023.jpeg	Cicero	O
023.jpeg	Avenue	O
023.jpeg	Oak	O
023.jpeg	"Lawn,"	O
023.jpeg	IL	O
023.jpeg	60453	O
023.jpeg	Tel:	O
023.jpeg	708	B-PHONE
023.jpeg	425	I-PHONE
023.jpeg	7800	I-PHONE
023.jpeg	Direct	O
023.jpeg	Line:	O
023.jpeg	708	O
023.jpeg	229	O
023.jpeg	8859	O
023.jpeg	Fax:	O
023.jpeg	708	O
023.jpeg	229	O
023.jpeg	8858	O
023.jpeg	email:	O
023.jpeg	heather.stevens@hilton.com	B-EMAIL
023.jpeg	HONORS	O
023.jpeg	HILTON	O
023.jpeg	official	O
023.jpeg	Sponsor	O
024.jpeg	-	O
024.jpeg	Mobile:	B-ORG
024.jpeg	limited	I-ORG
024.jpeg	Marian	B-NAME
024.jpeg	Piontek	I-NAME
024.jpeg	-708	B-PHONE
024.jpeg	890-8911	I-PHONE
024.jpeg	7884	O
024.jpeg	N	O
024.jpeg	Milwaukee	O
024.jpeg	Ave	O
024.jpeg	"Niles,"	O
024.jpeg	IL	O
024.jpeg	60714	O
024.jpeg	mpiontek@neptunemobile.com	B-EMAIL
025.jpeg	FURNITURE	O
025.jpeg	 	O
025.jpeg	Victor	B-NAME
025.jpeg	Harris	I-NAME
025.jpeg	Jr	I-NAME
025.jpeg	Sales	B-DES
025.jpeg	Associate	B-DES
025.jpeg	tel	O
025.jpeg	630.783.2346	B-PHONE
025.jpeg	fax	O
025.jpeg	630.783.1175	O
025.jpeg	Ashley	B-ORG
025.jpeg	Furniture	I-ORG
025.jpeg	HomeStore	I-ORG
025.jpeg	875	O
025.jpeg	E	O
025.jpeg	Boughton	O
025.jpeg	Road	O
025.jpeg	"Bolingbrook,"	O
025.jpeg	IL	O
025.jpeg	60440	O
025.jpeg	www.ashleyfurniturehomestore.com	B-EMAIL
027.jpeg	WALT	B-ORG
027.jpeg	DISNEY	I-ORG
027.jpeg	PRODUCTIONS	O
027.jpeg	Kee۪	O
027.jpeg	John	B-NAME
027.jpeg	F.	I-NAME
027.jpeg	Curry	I-NAME
027.jpeg	Director	B-DES
027.jpeg	2%)	O
027.jpeg	Hotel	O
027.jpeg	Division	O
027.jpeg	ams	O
027.jpeg	-213	B-PHONE
027.jpeg	245-8951	I-PHONE
027.jpeg	500	O
027.jpeg	SO.	O
027.jpeg	BUENA	O
027.jpeg	VISTA	O
027.jpeg	ST.	O
027.jpeg	+	O
027.jpeg	"BURBANK,"	O
027.jpeg	CALIFORNIA	O
027.jpeg	91503	O
028.jpeg	KUNUNURRA	O
028.jpeg	Rachell	B-NAME
028.jpeg	Fewster	I-NAME
028.jpeg	Shop	O
028.jpeg	112b	O
028.jpeg	Coolibah	O
028.jpeg	Drive	O
028.jpeg	418	O
028.jpeg	894	O
028.jpeg	400	O
028.jpeg	Kununurrra	O
028.jpeg	WA	O
028.jpeg	6743	O
028.jpeg	Phone:	O
028.jpeg	-8	B-PHONE
028.jpeg	9168	I-PHONE
028.jpeg	1737	I-PHONE
028.jpeg	Fax:	O
028.jpeg	-8	O
028.jpeg	9169	O
028.jpeg	3940	O
028.jpeg	Email:	O
028.jpeg	info@subwaykununurra.com.au	B-EMAIL
028.jpeg	 	O
030.jpeg	h	O
030.jpeg	Managing	B-DES
030.jpeg	Director	I-DES
030.jpeg	mail:	O
030.jpeg	customercare@sho|	B-EMAIL
030.jpeg	4reebok.com	I-EMAIL
030.jpeg	Shreshth	B-NAME
030.jpeg	Parekh	I-NAME
030.jpeg	to	O
030.jpeg	head	O
030.jpeg	Indian	O
030.jpeg	operations	O
030.jpeg	Reebok	O
030.jpeg	 	O
030.jpeg	add;	O
030.jpeg	"326,"	O
030.jpeg	Third	O
030.jpeg	"Floor,"	O
030.jpeg	Chintamani	O
030.jpeg	"Plaza,"	O
030.jpeg	"Bewing,"	O
030.jpeg	Andheri	O
030.jpeg	"Chakala,"	O
030.jpeg	Mumbai	O
030.jpeg	Reebok	B-ORG
030.jpeg	India	I-ORG
030.jpeg	Ltd.	I-ORG
031.jpeg	General	B-DES
031.jpeg	Manager	I-DES
031.jpeg	Domino's	B-ORG
031.jpeg	54321	O
031.jpeg	Caesar	O
031.jpeg	Blvd.	O
031.jpeg	Gardena	O
031.jpeg	"Fresh,"	O
031.jpeg	CA	O
031.jpeg	92337	O
031.jpeg	Mordan	O
031.jpeg	Pisa	O
031.jpeg	Store:	O
031.jpeg	562-543-7689	O
031.jpeg	Cell:	O
031.jpeg	562-456-3210	B-PHONE
031.jpeg	mpisa@dominos.com	B-EMAIL
032.jpeg	 	O
032.jpeg	 	O
032.jpeg	ae	O
032.jpeg	Be	O
032.jpeg	3	O
032.jpeg	 	O
033.jpeg	 	O
033.jpeg	PRAKASH	B-NAME
033.jpeg	KHEDKAR	I-NAME
033.jpeg	(Sales	B-DES
033.jpeg	Officer)	I-DES
033.jpeg	M.	O
033.jpeg	9227576803	O
033.jpeg	a	O
033.jpeg	LOAN	O
033.jpeg	AGAINST	O
033.jpeg	PROPERTY	O
033.jpeg	BHAVYA	B-ORG
033.jpeg	FINANCIAL	I-ORG
033.jpeg	SERVICES	I-ORG
033.jpeg	HDFC	O
033.jpeg	BANK	O
033.jpeg	"ASSOCIATE,"	O
033.jpeg	MORTGAGE	O
033.jpeg	LOANS	O
033.jpeg	"1009-1010,"	O
033.jpeg	City	O
033.jpeg	Centre	O
033.jpeg	"Market,"	O
033.jpeg	Opp.	O
033.jpeg	A.V.	O
033.jpeg	"Sons,"	O
033.jpeg	Ghod	O
033.jpeg	Dod	O
033.jpeg	"Road,"	O
033.jpeg	Parle	O
033.jpeg	"Point,"	O
033.jpeg	"Surat-395007,"	O
033.jpeg	Ph.	O
033.jpeg	261	B-PHONE
033.jpeg	2210142	I-PHONE
033.jpeg	e	O
033.jpeg	mail	O
033.jpeg	:-	O
033.jpeg	pykhedkar07@yahoo.com.	B-EMAIL
034.jpeg	 	O
034.jpeg	   	O
034.jpeg	 	O
034.jpeg	 	O
034.jpeg	 	O
034.jpeg	 	O
034.jpeg	 	O
034.jpeg	  	O
034.jpeg	  	O
034.jpeg	  	O
034.jpeg	 	O
034.jpeg	J	O
034.jpeg	"laptop,"	O
034.jpeg	Computer	O
034.jpeg	&	O
034.jpeg	Printer	O
034.jpeg	Sales	O
034.jpeg	J	O
034.jpeg	Laptop	O
034.jpeg	&	O
034.jpeg	Computer	O
034.jpeg	Service	O
034.jpeg	J	O
034.jpeg	Data	O
034.jpeg	Recovery	O
034.jpeg	&	O
034.jpeg	Networking	O
034.jpeg	/	O
034.jpeg	AMC	O
034.jpeg	&	O
034.jpeg	House	O
034.jpeg	Repairs	O
034.jpeg	Service	O
034.jpeg	J	O
034.jpeg	Printer	O
034.jpeg	Repairs	O
034.jpeg	@	O
034.jpeg	Toner	O
034.jpeg	Refiling	O
034.jpeg	J	O
034.jpeg	All	O
034.jpeg	Type	O
034.jpeg	of	O
034.jpeg	Accessories	O
034.jpeg	/	O
034.jpeg	CCTv.	O
034.jpeg	Camera	O
034.jpeg	/	O
034.jpeg	Web	O
034.jpeg	Hosting	O
034.jpeg	&	O
034.jpeg	Domain	O
034.jpeg	Register	O
034.jpeg	J	O
034.jpeg	Instant	O
034.jpeg	Web	O
034.jpeg	Development	O
034.jpeg	/	O
034.jpeg	Software	O
034.jpeg	Development	O
034.jpeg	 	O
034.jpeg	infoTech	O
034.jpeg	Do	O
034.jpeg	Something	O
034.jpeg	Big	O
034.jpeg	9898	B-PHONE
034.jpeg	24	I-PHONE
034.jpeg	4020	I-PHONE
034.jpeg	9033	I-PHONE
034.jpeg	25	I-PHONE
034.jpeg	1418	I-PHONE
034.jpeg		O
034.jpeg	perfectinfotech2013@gmail.com	B-EMAIL
034.jpeg	@	O
034.jpeg	"124,"	O
034.jpeg	Gurukrupa	O
034.jpeg	"Complex,"	O
034.jpeg	Talod-Majara	O
034.jpeg	Road	O
034.jpeg	"Beside,"	O
034.jpeg	Mamlatdar	O
034.jpeg	"Kacheri,"	O
034.jpeg	Talod.	O
034.jpeg	 	O
035.jpeg	Craig	B-NAME
035.jpeg	Forman	I-NAME
035.jpeg	di.	O
035.jpeg	Service	B-ORG
035.jpeg	Max	I-ORG
035.jpeg	LLC	I-ORG
035.jpeg	25	O
035.jpeg	Pine	O
035.jpeg	Street	O
035.jpeg	-	O
035.jpeg	Suite	O
035.jpeg	8	O
035.jpeg	Facility	O
035.jpeg	Maintenance	O
035.jpeg	&	O
035.jpeg	Janitorial	O
035.jpeg	and	O
035.jpeg	Supplies	O
035.jpeg	Rockaway	O
035.jpeg	NJ	O
035.jpeg	7866	O
035.jpeg	Office	O
035.jpeg	-973	O
035.jpeg	627-9292	O
035.jpeg	Fax	O
035.jpeg	-973	O
035.jpeg	210-9160	O
035.jpeg	Cell	O
035.jpeg	-973	B-PHONE
035.jpeg	876-8402	I-PHONE
035.jpeg	craig@servicemaxnj.com	B-EMAIL
035.jpeg	www.servicemaxnj.com	B-WEB
035.jpeg	 	O
036.jpeg	 	O
036.jpeg	8	O
036.jpeg	Stanford	O
036.jpeg	Stanford	B-ORG
036.jpeg	MEDICINE	I-ORG
036.jpeg	Cardiovascular	I-ORG
036.jpeg	Institute	I-ORG
036.jpeg	Joseph	B-NAME
036.jpeg	C.	I-NAME
036.jpeg	"Wu,"	I-NAME
036.jpeg	"MD,"	O
036.jpeg	PhD	O
036.jpeg	"Director,"	B-DES
036.jpeg	Stanford	O
036.jpeg	Cardiovascular	O
036.jpeg	Institute	O
036.jpeg	Professor	O
036.jpeg	Medicine	O
036.jpeg	(Cardiology)	O
036.jpeg	&	O
036.jpeg	Radiology	O
036.jpeg	265	O
036.jpeg	Campus	O
036.jpeg	"Drive,"	O
036.jpeg	G-1120B	O
036.jpeg	Tel:	O
036.jpeg	-650	B-PHONE
036.jpeg	736-2246	I-PHONE
036.jpeg	"Stanford,"	O
036.jpeg	CA	O
036.jpeg	"94305,"	O
036.jpeg	MC-5454	O
036.jpeg	Fax:	O
036.jpeg	-650	O
036.jpeg	736-0234	O
036.jpeg	http://wulab.stanfordedu	B-WEB
036.jpeg	CVI:	O
036.jpeg	-650	O
036.jpeg	725-7964	O
036.jpeg	e-mail:	O
036.jpeg	joewu@stanford.edu	B-EMAIL
036.jpeg	het	O
036.jpeg	 	O
036.jpeg	://evi.stanford.edu	O
036.jpeg	 	O
037.jpeg	8281604684	B-PHONE
037.jpeg	9061825334	B-PHONE
037.jpeg	9544851506	B-PHONE
037.jpeg	|	O
037.jpeg	you	O
037.jpeg	dream	O
037.jpeg	"it,"	O
037.jpeg	we	O
037.jpeg	make	O
037.jpeg	it	O
037.jpeg	SGRAPHICS	O
037.jpeg	Manathala	O
037.jpeg	Isons	O
037.jpeg	"Arcade,"	O
037.jpeg	Above	O
037.jpeg	Fedaral	O
037.jpeg	"Bank,"	O
037.jpeg	Perumanoorkulam	O
037.jpeg	"Jn.,"	O
037.jpeg	Manarcad-Kottayam	O
037.jpeg	Tel	O
037.jpeg	:	O
037.jpeg	481	O
037.jpeg	2373840	O
037.jpeg	vibrantgraphicz@gmail.com	O
037.jpeg	  	O
037.jpeg	SHE	O
037.jpeg	FLEX	O
037.jpeg	&	O
037.jpeg	VINYL	O
037.jpeg	PRINTING	O
037.jpeg	CLOTH	O
037.jpeg	PRINTING	O
037.jpeg	FLEX	O
037.jpeg	BOARDS	O
037.jpeg	LIGHT	O
037.jpeg	BOARDS	O
037.jpeg	WEDDING	O
037.jpeg	CARDS	O
037.jpeg	VISITING	O
037.jpeg	CARDS	O
037.jpeg	STICKER	O
037.jpeg	CUTTING	O
037.jpeg	"NOTICE,"	O
037.jpeg	POSTER	O
037.jpeg	BROCHURES	O
037.jpeg	GRAPHIC	O
037.jpeg	DESIGNING	O
037.jpeg	and	O
037.jpeg	all	O
037.jpeg	other	O
037.jpeg	advertisement	O
037.jpeg	Works	O
038.jpeg	In	O
038.jpeg	association	O
038.jpeg	with	O
038.jpeg	LOBO	O
038.jpeg	ASSOCIATES	O
038.jpeg	tel	O
038.jpeg	91	B-PHONE
038.jpeg	481	I-PHONE
038.jpeg	2424398	I-PHONE
038.jpeg	/	O
038.jpeg	7034641404	B-PHONE
038.jpeg	Door	O
038.jpeg	No.	O
038.jpeg	"XXII/32,"	O
038.jpeg	Parel	O
038.jpeg	Church	O
038.jpeg	"Road,"	O
038.jpeg	"Kurisummodu,"	O
038.jpeg	"686104,"	O
038.jpeg	"Changanacherry,"	O
038.jpeg	Kottayam.	O
038.jpeg	www.aramex.com	B-WEB
038.jpeg	Manuel	B-NAME
038.jpeg	Joseph	I-NAME
038.jpeg	Lobo	O
038.jpeg	aramexchry@gmail.com	B-EMAIL
038.jpeg	 	O
039.jpeg	Burger	B-ORG
039.jpeg	King	I-ORG
039.jpeg	Canada	I-ORG
039.jpeg	Inc.	I-ORG
039.jpeg	Manager:	B-DES
039.jpeg	Jatheepa	B-NAME
039.jpeg	Sathananthan	I-NAME
039.jpeg	&	O
039.jpeg	"Maa,"	O
039.jpeg	Nicole	B-NAME
039.jpeg	White	I-NAME
039.jpeg	1490	O
039.jpeg	Dixie	O
039.jpeg	"Rd,"	O
039.jpeg	B	O
039.jpeg	K	O
039.jpeg	"Mississauga,ON"	O
039.jpeg	LSE	O
039.jpeg	3.00E+05	O
039.jpeg	BURGER	B-ORG
039.jpeg	KING	I-ORG
039.jpeg	905-274-1607	B-PHONE
039.jpeg	burger@king.com	B-EMAIL
039.jpeg	www.burgerking.com	B-WEB
040.jpeg	ALAMO	B-ORG
040.jpeg	PRODUCTIONS	I-ORG
040.jpeg	434136	O
040.jpeg	Sierra	O
040.jpeg	"Hwy.,"	O
040.jpeg	Canyon	O
040.jpeg	"Country,"	O
040.jpeg	CA	O
040.jpeg	94359	O
040.jpeg	-805	B-PHONE
040.jpeg	252-6157	I-PHONE
040.jpeg	Te	O
040.jpeg	Pree	O
041.jpeg	 	O
041.jpeg	 	O
041.jpeg	Cell	O
041.jpeg	:	O
041.jpeg	8099948528	B-PHONE
041.jpeg	ce)	O
041.jpeg	8466045457	B-PHONE
041.jpeg	email	O
041.jpeg	:	O
041.jpeg	lictsrikant@gmail.com	B-EMAIL
041.jpeg	LIFE	B-ORG
041.jpeg	INSURANCE	I-ORG
041.jpeg	CORPORATION	I-ORG
041.jpeg	OF	I-ORG
041.jpeg	INDIA	I-ORG
041.jpeg	seosrika	B-EMAIL
041.jpeg	ntht@gmail	I-EMAIL
041.jpeg	.com	I-EMAIL
041.jpeg	THATHINENI	B-NAME
041.jpeg	SRIKANTH	I-NAME
041.jpeg	Insurance	B-DES
041.jpeg	Advisor	I-DES
041.jpeg	Agent	O
041.jpeg	Code	O
041.jpeg	No.	O
041.jpeg	0316164Y	O
041.jpeg	LIFE	B-ORG
041.jpeg	INSURANCE	I-ORG
041.jpeg	CORPORATION	I-ORG
041.jpeg	OF	I-ORG
041.jpeg	INDIA	I-ORG
041.jpeg	Br.	O
041.jpeg	Off.	O
041.jpeg	LIC	O
041.jpeg	"Office,"	O
041.jpeg	"Trimulgherry,"	O
041.jpeg	Sec۪bad	O
041.jpeg	-	O
041.jpeg	500	O
041.jpeg	16	O
041.jpeg	Add.	O
041.jpeg	"Borabanda,"	O
041.jpeg	Hyderabad	O
041.jpeg	-	O
041.jpeg	500	O
041.jpeg	18	O
041.jpeg	"lictsrikant8099948528.blogspot.in,"	B-WEB
041.jpeg	interviewsinhyderabad.blogspot.in	B-WEB
041.jpeg	"facebook.com/lictsrikant8099948528,"	O
041.jpeg	facebook.com/thathineni.srikanth.9	O
041.jpeg	Promote	O
041.jpeg	your	O
041.jpeg	business	O
041.jpeg	online	O
041.jpeg	(PYBO)	O
041.jpeg	 	O
041.jpeg	 	O
042.jpeg	John	B-NAME
042.jpeg	Best	I-NAME

#### Split by newline(\n)

In [6]:
text.split('\n')

['id\ttext\ttag',
 '000.jpeg\t \tO',
 '000.jpeg\t.\tO',
 '000.jpeg\t040-4852\tB-PHONE',
 '000.jpeg\t"8881,"\tI-PHONE',
 '000.jpeg\t90309\tB-PHONE',
 '000.jpeg\t52549\tI-PHONE',
 '000.jpeg\tFi\tO',
 '000.jpeg\t/laurelsoverseaseducation\tO',
 '000.jpeg\t@:\tO',
 '000.jpeg\tLAURELS\tB-ORG',
 '000.jpeg\tOVERSEAS\tI-ORG',
 '000.jpeg\tEDUCATIONAL\tI-ORG',
 '000.jpeg\tCONSULTANCY\tI-ORG',
 '000.jpeg\tPVT.\tI-ORG',
 '000.jpeg\tLTD.\tI-ORG',
 '000.jpeg\tSea\tO',
 '000.jpeg\t|\tO',
 '000.jpeg\tU.K\tO',
 '000.jpeg\tAUSTRALIA\tO',
 '000.jpeg\tCANADA\tO',
 '000.jpeg\tIRELAND\tO',
 '000.jpeg\t \tO',
 '000.jpeg\t \tO',
 '000.jpeg\t \tO',
 '000.jpeg\t \tO',
 '000.jpeg\t \tO',
 '000.jpeg\t \tO',
 '000.jpeg\twww.laurelseducation.com\tB-WEB',
 '000.jpeg\t)%info@laurelseducation.com\tB-EMAIL',
 '000.jpeg\t \tO',
 '001.jpeg\tjohn\tB-NAME',
 '001.jpeg\tsmith\tI-NAME',
 '001.jpeg\tmarketing\tB-DES',
 '001.jpeg\tmanager\tI-DES',
 '001.jpeg\tweb:\tO',
 '001.jpeg\twww.psdgraphics.com\tB-WEB',
 '001.jpeg\tphone:\tO',
 '001.jpeg\t123-456-7890\tB-PHONE',
 '001.jpeg\tmail:\tO',
 '001.jpeg\temail@psdgraphics.com\tB-EMAIL',
 '002.jpeg\t    \tO',
 '002.jpeg\t   \tO',
 '002.jpeg\tSau\tO',
 '002.jpeg\t0\tO',
 '002.jpeg\t98489\tB-PHONE',
 '002.jpeg\t24441\tI-PHONE',
 '002.jpeg\tdy\tO',
 '002.jpeg\t"08672,"\tO',
 '002.jpeg\t224441\tO',
 '002.jpeg\t/ENKATESWAPA\tB-ORG',
 '002.jpeg\t&\tO',
 '002.jpeg\twie\tO',
 '002.jpeg\t \tO',
 '002.jpeg\t=\tO',
 '002.jpeg\t \tO',
 '003.jpeg\tPrasad\tB-NAME',
 '003.jpeg\t@\tO',
 '003.jpeg\t"9,96,31,73,53,59,49,04,00,000"\tO',
 '003.jpeg\t  \tO',
 '003.jpeg\t   \tO',
 '003.jpeg\ti\tO',
 '003.jpeg\tFlex\tO',
 '003.jpeg\tDesign\tO',
 '003.jpeg\t#\tO',
 '003.jpeg\tAlbum\tO',
 '003.jpeg\tDesign\tO',
 '003.jpeg\t\tO',
 '003.jpeg\tVisiting\tO',
 '003.jpeg\tCards\tO',
 '003.jpeg\tDTP\tO',
 '003.jpeg\tWorks\tO',
 '003.jpeg\t(Telugu\tO',
 '003.jpeg\t&\tO',
 '003.jpeg\tEnglish)\tO',
 '003.jpeg\t \tO',
 '003.jpeg\t \tO',
 '003.jpeg\t \tO',
 '003.jpeg\t \tO',
 '004.jpeg\t<=>\tO',
 '004.jpeg\tMadison\tB-ORG',
 '004.jpeg\tYacht\tI-ORG',
 '004.jpeg\tSales\tI-ORG',
 '004.jpeg\tPaul\tB-NAME',
 '004.jpeg\tMadison\tI-NAME',
 '004.jpeg\tYacht\tB-DES',
 '004.jpeg\tBroker\tI-DES',
 '004.jpeg\t-\tO',
 '004.jpeg\tNortheast\tO',
 '004.jpeg\tRegion\tO',
 '004.jpeg\t   \tO',
 '004.jpeg\t  \tO',
 '004.jpeg\t \tO',
 '004.jpeg\tFax:\tO',
 '004.jpeg\t718-444-1206\tB-PHONE',
 '004.jpeg\t  \tO',
 '007.jpeg\twww\tB-WEB',
 '007.jpeg\tphototomics.com\tI-WEB',
 '007.jpeg\tPHOTOT\tB-ORG',
 '007.jpeg\tThomas\tB-NAME',
 '007.jpeg\tAtkins\tI-NAME',
 '007.jpeg\tPhotographer\tB-DES',
 '007.jpeg\tand\tI-DES',
 '007.jpeg\tDigital\tI-DES',
 '007.jpeg\tArtist\tI-DES',
 '007.jpeg\ttatkins@phototomics.com\tB-EMAIL',
 '007.jpeg\tPhototomics\tO',
 '007.jpeg\t3419\tO',
 '007.jpeg\tVia\tO',
 '007.jpeg\tLido\tO',
 '007.jpeg\t#340\tO',
 '007.jpeg\tNewport\tO',
 '007.jpeg\tBeach\tO',
 '007.jpeg\tCA\tO',
 '007.jpeg\t-\tO',
 '007.jpeg\tCalifornia\tO',
 '007.jpeg\t92663\tO',
 '007.jpeg\t \tO',
 '008.jpeg\t \tO',
 '008.jpeg\tReddy\tO',
 '008.jpeg\t9866186785\tB-PHONE',
 '008.jpeg\t   \tO',
 '008.jpeg\t \tO',
 '008.jpeg\tOpp\tO',
 '008.jpeg\tRamakrishna\tO',
 '008.jpeg\t"Theatre,Main"\tO',
 '008.jpeg\tRoad\tO',
 '008.jpeg\t"Peddapalli,"\tO',
 '008.jpeg\tDist\tO',
 '008.jpeg\t:\tO',
 '008.jpeg\t"Karimnagar,"\tO',
 '008.jpeg\tTelangana\tO',
 '008.jpeg\t-\tO',
 '008.jpeg\t505172\tO',
 '008.jpeg\temail\tO',
 '008.jpeg\t:\tO',
 '008.jpeg\tsrihithaads.pdpl@\tB-EMAIL',
 '008.jpeg\tgmail.com\tI-EMAIL',
 '008.jpeg\t \tO',
 '009.jpeg\tSaja\tB-NAME',
 '009.jpeg\t(Vik):\tO',
 '009.jpeg\t990083000\tB-PHONE',
 '009.jpeg\tG.S.M.\tB-ORG',
 '009.jpeg\tBOOSTER\tI-ORG',
 '009.jpeg\t1)\tO',
 '009.jpeg\tAll\tO',
 '009.jpeg\tTypes\tO',
 '009.jpeg\tof\tO',
 '009.jpeg\tMobile\tO',
 '009.jpeg\t"Repair,"\tO',
 '009.jpeg\t\tO',
 '009.jpeg\tData\tO',
 '009.jpeg\tTransfer\tO',
 '009.jpeg\t-\tO',
 '009.jpeg\tGame\tO',
 '009.jpeg\t&\tO',
 '009.jpeg\tApplication\tO',
 '009.jpeg\tLed\tO',
 '009.jpeg\tTouch\tO',
 '009.jpeg\tGlass\tO',
 '009.jpeg\t"Change,"\tO',
 '009.jpeg\tAll\tO',
 '009.jpeg\tMobile\tO',
 '009.jpeg\tLed\tO',
 '009.jpeg\t"Fitting,"\tO',
 '009.jpeg\tMobile\tO',
 '009.jpeg\tRepair\tO',
 '009.jpeg\tTraining\tO',
 '009.jpeg\t"loor,"\tO',
 '009.jpeg\tCity\tO',
 '009.jpeg\tCentre\tO',
 '009.jpeg\t"Mall,"\tO',
 '009.jpeg\tOpp.\tO',
 '009.jpeg\t"mbai-Central,"\tO',
 '009.jpeg\tMumbai\tO',
 '009.jpeg\t-\tO',
 '009.jpeg\t400\tO',
 '009.jpeg\t8\tO',
 '009.jpeg\t  \tO',
 '009.jpeg\t \tO',
 '009.jpeg\t  \tO',
 '009.jpeg\t   \tO',
 '009.jpeg\t  \tO',
 '009.jpeg\t  \tO',
 '009.jpeg\t_Ӊ_B:E:S.T.\tO',
 '010.jpeg\tDr.\tB-NAME',
 '010.jpeg\tMichael\tI-NAME',
 '010.jpeg\tDean\tI-NAME',
 '010.jpeg\tClarinet\tO',
 '010.jpeg\tPerforming\tO',
 '010.jpeg\tTeaching\tB-DES',
 '010.jpeg\tand\tI-DES',
 '010.jpeg\tConsulting\tI-DES',
 '010.jpeg\t682.888.7639\tB-PHONE',
 '010.jpeg\tclarinetmike.com\tB-WEB',
 '010.jpeg\tclarinetmike.wordpress.com\tB-WEB',
 '010.jpeg\tclarinetmiketexas@\tB-EMAIL',
 '010.jpeg\tyahoo.com\tI-EMAIL',
 '010.jpeg\t \tO',
 '011.jpeg\ta\tO',
 '011.jpeg\t:\tO',
 '011.jpeg\tCell\tO',
 '011.jpeg\t:\tO',
 '011.jpeg\t9885050228\tB-PHONE',
 '011.jpeg\tKrishna\tB-NAME',
 '011.jpeg\t3257779\tB-PHONE',
 '011.jpeg\t\\\tO',
 '011.jpeg\t9393937799\tB-PHONE',
 '011.jpeg\t \tO',
 '011.jpeg\t    \tO',
 '011.jpeg\t \tO',
 '011.jpeg\t \tO',
 '011.jpeg\tD.No.\tO',
 '011.jpeg\t"27-33-19,"\tO',
 '011.jpeg\tSatnam\tO',
 '011.jpeg\t"Towers,"\tO',
 '011.jpeg\tOpp:\tO',
 '011.jpeg\tBuckingham\tO',
 '011.jpeg\tPost\tO',
 '011.jpeg\t"Office,"\tO',
 '011.jpeg\tGudavallivari\tO',
 '011.jpeg\t"St.,"\tO',
 '011.jpeg\t"Governorpeta,"\tO',
 '011.jpeg\tVijayawada.\tO',
 '011.jpeg\tat\tO',
 '012.jpeg\tCell:\tO',
 '012.jpeg\t7396379143\tB-PHONE',
 '012.jpeg\t \tO',
 '013.jpeg\tMobile:73963791\tB-PHONE',
 '013.jpeg\t43\tO',
 '013.jpeg\tFLEX.\tO',
 '013.jpeg\tPRINT\tO',
 '013.jpeg\taz\tO',
 '013.jpeg\tDesigning\tO',
 '013.jpeg\t&\tO',
 '013.jpeg\tPrinting\tO',
 '013.jpeg\t \tO',
 '013.jpeg\t   \tO',
 '013.jpeg\tCL\tO',
 '013.jpeg\t \tO',
 '013.jpeg\tEL\tO',
 '013.jpeg\t   \tO',
 '013.jpeg\t \tO',
 '014.jpeg\tMob:-8445790640\tB-PHONE',
 '014.jpeg\tSiyalg\tO',
 '014.jpeg\tAll\tO',
 '014.jpeg\tKind\tO',
 '014.jpeg\t"Charger,"\tO',
 '014.jpeg\t"Earphones,"\tO',
 '014.jpeg\tMobile\tO',
 '014.jpeg\t"Photostate,"\tO',
 '014.jpeg\t&Anygkindlof\tO',
 '014.jpeg\tOnline\tO',
 '014.jpeg\tWorks.\tO',
 '014.jpeg\t \tO',
 '014.jpeg\t \tO',
 '015.jpeg\t \tO',
 '015.jpeg\t4!\tO',
 '015.jpeg\tShri\tO',
 '015.jpeg\tGaneshay\tO',
 '015.jpeg\tNamah\tO',
 '015.jpeg\t!t\tO',
 '015.jpeg\tM.\tO',
 '015.jpeg\t70147-98128\tB-PHONE',
 '015.jpeg\t \tO',
 '015.jpeg\tBAJA\tO',
 '015.jpeg\tDeals\tO',
 '015.jpeg\tin\tO',
 '015.jpeg\t:\tO',
 '015.jpeg\tAll\tO',
 '015.jpeg\tKinds\tO',
 '015.jpeg\tof\tO',
 '015.jpeg\tNew\tO',
 '015.jpeg\tMobile\tO',
 '015.jpeg\t"Handset,"\tO',
 '015.jpeg\tTempered\tO',
 '015.jpeg\tGlass\tO',
 '015.jpeg\tFINSERV\tO',
 '015.jpeg\tFancy\tO',
 '015.jpeg\t"Covers,"\tO',
 '015.jpeg\tAccessories\tO',
 '015.jpeg\tAvailable\tO',
 '015.jpeg\tHere\tO',
 '015.jpeg\t \tO',
 '015.jpeg\tSAMSUNG\tO',
 '015.jpeg\tOPPO\tO',
 '015.jpeg\tVivo\tO',
 '015.jpeg\tJenovo\tO',
 '015.jpeg\t@\tO',
 '015.jpeg\tiPhone\tO',
 '015.jpeg\tmobile\tO',
 '015.jpeg\tGIONEE\tO',
 '015.jpeg\t  \tO',
 '015.jpeg\t \tO',
 '016.jpeg\t    \tO',
 '016.jpeg\t91\tB-PHONE',
 '016.jpeg\t9087253526\tI-PHONE',
 '016.jpeg\t91\tB-PHONE',
 '016.jpeg\t9087252666\tI-PHONE',
 '016.jpeg\toe\tO',
 '016.jpeg\traghuvijayan104@gmail.com\tB-EMAIL',
 '017.jpeg\tY-Wireless\tB-ORG',
 '017.jpeg\tRepair\tI-ORG',
 '017.jpeg\t \tO',
 '017.jpeg\t \tO',
 '017.jpeg\t \tO',
 '017.jpeg\t \tO',
 '017.jpeg\t \tO',
 '017.jpeg\t \tO',
 '017.jpeg\teee\tO',
 '017.jpeg\tCertified\tO',
 '017.jpeg\tTechnician\tO',
 '017.jpeg\tPhone\tO',
 '017.jpeg\t\tO',
 '017.jpeg\tTablet\tO',
 '017.jpeg\t-\tO',
 '017.jpeg\tElectronic\tO',
 '017.jpeg\tRepairs\tO',
 '017.jpeg\tCall\tO',
 '017.jpeg\tus\tO',
 '017.jpeg\t330-270-5060\tB-PHONE',
 '017.jpeg\tfacebook.com/YoungstownWirelessRepair\tO',
 '018.jpeg\t \tO',
 '018.jpeg\tCell\tO',
 '018.jpeg\tPhone\tB-ORG',
 '018.jpeg\tRepair\tI-ORG',
 '018.jpeg\tCenter\tI-ORG',
 '018.jpeg\t6795\tO',
 '018.jpeg\tWilson\tO',
 '018.jpeg\t"Blvd,"\tO',
 '018.jpeg\tSuite\tO',
 '018.jpeg\t26\tO',
 '018.jpeg\tBUY\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tSELL\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tTRADE\tO',
 '018.jpeg\tFalls\tO',
 '018.jpeg\t"Church,"\tO',
 '018.jpeg\tVA\tO',
 '018.jpeg\t22044\tO',
 '018.jpeg\tTEL:\tO',
 '018.jpeg\t571\tB-PHONE',
 '018.jpeg\t606\tI-PHONE',
 '018.jpeg\t6636\tI-PHONE',
 '018.jpeg\t/\tO',
 '018.jpeg\t571606\tI-PHONE',
 '018.jpeg\t3445\tI-PHONE',
 '018.jpeg\t-\tO',
 '018.jpeg\t"iPhone,"\tO',
 '018.jpeg\tiPad\tO',
 '018.jpeg\t02-03-2004\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tHTC\tO',
 '018.jpeg\tRepair\tO',
 '018.jpeg\team\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tSamsung\tO',
 '018.jpeg\tRepair\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tTrackball\tO',
 '018.jpeg\tRepair\tO',
 '018.jpeg\thtc\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tCracked\tO',
 '018.jpeg\tScreens\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tWater\tO',
 '018.jpeg\tDamage\tO',
 '018.jpeg\t\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tSpeakers\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tCharger\tO',
 '018.jpeg\tPort\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tSoftware\tO',
 '018.jpeg\tUpdate\tO',
 '018.jpeg\tNOKIA\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tPassword\tO',
 '018.jpeg\tReset\tO',
 '018.jpeg\t..and\tO',
 '018.jpeg\talmost\tO',
 '018.jpeg\tany\tO',
 '018.jpeg\thardware\tO',
 '018.jpeg\tor\tO',
 '018.jpeg\tsoftware\tO',
 '018.jpeg\tissue!\tO',
 '018.jpeg\tEden\tO',
 '018.jpeg\tCenter\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tSeven\tO',
 '018.jpeg\tCorner\tO',
 '018.jpeg\t-\tO',
 '018.jpeg\tRoute\tO',
 '018.jpeg\t50\tO',
 '018.jpeg\t \tO',
 '020.jpeg\tMOBILE\tB-ORG',
 '020.jpeg\tREPAIR\tI-ORG',
 '020.jpeg\tCENTRE\tI-ORG',
 '020.jpeg\tON-SITE\tO',
 '020.jpeg\tREPAIRS\tO',
 '020.jpeg\tWHILE\tO',
 '020.jpeg\tYOU\tO',
 '020.jpeg\tWAIT\tO',
 '020.jpeg\tINSTANT\tO',
 '020.jpeg\tUNLOCKING\tO',
 '020.jpeg\tSOLUTIONS\tO',
 '020.jpeg\tDAMAGED\tO',
 '020.jpeg\tLCD\tO',
 '020.jpeg\tSCREENS\tO',
 '020.jpeg\tREPLACED\tO',
 '020.jpeg\tWATERILIQUID\tO',
 '020.jpeg\tDAMAGED\tO',
 '020.jpeg\tPHONES\tO',
 '020.jpeg\t"CHARGING,"\tO',
 '020.jpeg\tAUDIO\tO',
 '020.jpeg\t&\tO',
 '020.jpeg\tSIGNAL\tO',
 '020.jpeg\tPROBLEMS\tO',
 '020.jpeg\tSOFTWARE\tO',
 '020.jpeg\tPROBLEMS\tO',
 '020.jpeg\tREPLACEMENT\tO',
 '020.jpeg\tLOAN\tO',
 '020.jpeg\tPHONES\tO',
 '020.jpeg\tAVAILABLE\tO',
 '020.jpeg\tWHILE\tO',
 '020.jpeg\tYOUR\tO',
 '020.jpeg\tPHONE\tO',
 '020.jpeg\tIS\tO',
 '020.jpeg\tBEING\tO',
 '020.jpeg\tREPAIRED\tO',
 '020.jpeg\tNO-FIX\tO',
 '020.jpeg\tNO-FEE\tO',
 '020.jpeg\t  \tO',
 '020.jpeg\t  \tO',
 '020.jpeg\t20\tB-PHONE',
 '020.jpeg\t87499933\tI-PHONE',
 '020.jpeg\tWWW.MPRC.CO\tB-WEB',
 '021.jpeg\tEzy\tB-ORG',
 '021.jpeg\tFit\tI-ORG',
 '021.jpeg\t \tO',
 '021.jpeg\t \tO',
 '021.jpeg\t  \tO',
 '021.jpeg\t   \tO',
 '021.jpeg\t    \tO',
 '021.jpeg\t  \tO',
 '021.jpeg\t \tO',
 '021.jpeg\t+\tO',
 '021.jpeg\tSenice\tO',
 '021.jpeg\t+\tO',
 '021.jpeg\tBrakes\tO',
 '021.jpeg\t \tO',
 '021.jpeg\t91\tO',
 '021.jpeg\tPortland\tO',
 '021.jpeg\t"Rd,"\tO',
 '021.jpeg\tHucknall\tO',
 '021.jpeg\tTiming\tO',
 '021.jpeg\tBelts\tO',
 '021.jpeg\tNG15\tO',
 '021.jpeg\t7DS\tO',
 '021.jpeg\t+\tO',
 '021.jpeg\tSuspension\tO',
 '021.jpeg\tOpp\tO',
 '021.jpeg\tSandicliffe\tO',
 '021.jpeg\tFord\tO',
 '021.jpeg\t+\tO',
 '021.jpeg\tDiagnostics\tO',
 '021.jpeg\t+\tO',
 '021.jpeg\tBatteries\tO',
 '021.jpeg\tFree\tO',
 '021.jpeg\tBrake\tO',
 '021.jpeg\tCheck\tO',
 '021.jpeg\t \tO',
 '021.jpeg\t \tO',
 '021.jpeg\tEmail:\tO',
 '021.jpeg\tco.uk\tO',
 '021.jpeg\tWeb:\tO',
 '021.jpeg\twww.ezyfitautocentre.co.uk\tB-WEB',
 '022.jpeg\tDale\tB-NAME',
 '022.jpeg\tSteffen\tI-NAME',
 '022.jpeg\tClub\tB-DES',
 '022.jpeg\tManager\tI-DES',
 '022.jpeg\t \tO',
 '022.jpeg\tPLANET\tO',
 '022.jpeg\tFITNESS\tO',
 '022.jpeg\t|\tO',
 '022.jpeg\tHOME\tO',
 '022.jpeg\tof\tO',
 '022.jpeg\tthe\tO',
 '022.jpeg\tJUDGEMENT\tO',
 '022.jpeg\tFREE\tO',
 '022.jpeg\tZONE\tO',
 '022.jpeg\t9652\tO',
 '022.jpeg\tS.\tO',
 '022.jpeg\tRoberts\tO',
 '022.jpeg\tRd.\tO',
 '022.jpeg\t|\tO',
 '022.jpeg\tHickory\tO',
 '022.jpeg\t"Hills,"\tO',
 '022.jpeg\tIL\tO',
 '022.jpeg\t60457\tO',
 '022.jpeg\tAyes\tO',
 '022.jpeg\tP:\tO',
 '022.jpeg\t708.598.1010\tB-PHONE',
 '022.jpeg\tplanetfitness.com\tB-WEB',
 '023.jpeg\tHilton\tB-ORG',
 '023.jpeg\tOak\tI-ORG',
 '023.jpeg\tLawn\tI-ORG',
 '023.jpeg\tHeather\tB-NAME',
 '023.jpeg\tStevens\tI-NAME',
 '023.jpeg\tCatering\tB-DES',
 '023.jpeg\tManager\tI-DES',
 '023.jpeg\t9333\tO',
 '023.jpeg\tSouth\tO',
 '023.jpeg\tCicero\tO',
 '023.jpeg\tAvenue\tO',
 '023.jpeg\tOak\tO',
 '023.jpeg\t"Lawn,"\tO',
 '023.jpeg\tIL\tO',
 '023.jpeg\t60453\tO',
 '023.jpeg\tTel:\tO',
 '023.jpeg\t708\tB-PHONE',
 '023.jpeg\t425\tI-PHONE',
 '023.jpeg\t7800\tI-PHONE',
 '023.jpeg\tDirect\tO',
 '023.jpeg\tLine:\tO',
 '023.jpeg\t708\tO',
 '023.jpeg\t229\tO',
 '023.jpeg\t8859\tO',
 '023.jpeg\tFax:\tO',
 '023.jpeg\t708\tO',
 '023.jpeg\t229\tO',
 '023.jpeg\t8858\tO',
 '023.jpeg\temail:\tO',
 '023.jpeg\theather.stevens@hilton.com\tB-EMAIL',
 '023.jpeg\tHONORS\tO',
 '023.jpeg\tHILTON\tO',
 '023.jpeg\tofficial\tO',
 '023.jpeg\tSponsor\tO',
 '024.jpeg\t-\tO',
 '024.jpeg\tMobile:\tB-ORG',
 '024.jpeg\tlimited\tI-ORG',
 '024.jpeg\tMarian\tB-NAME',
 '024.jpeg\tPiontek\tI-NAME',
 '024.jpeg\t-708\tB-PHONE',
 '024.jpeg\t890-8911\tI-PHONE',
 '024.jpeg\t7884\tO',
 '024.jpeg\tN\tO',
 '024.jpeg\tMilwaukee\tO',
 '024.jpeg\tAve\tO',
 '024.jpeg\t"Niles,"\tO',
 '024.jpeg\tIL\tO',
 '024.jpeg\t60714\tO',
 '024.jpeg\tmpiontek@neptunemobile.com\tB-EMAIL',
 '025.jpeg\tFURNITURE\tO',
 '025.jpeg\t \tO',
 '025.jpeg\tVictor\tB-NAME',
 '025.jpeg\tHarris\tI-NAME',
 '025.jpeg\tJr\tI-NAME',
 '025.jpeg\tSales\tB-DES',
 '025.jpeg\tAssociate\tB-DES',
 '025.jpeg\ttel\tO',
 '025.jpeg\t630.783.2346\tB-PHONE',
 '025.jpeg\tfax\tO',
 '025.jpeg\t630.783.1175\tO',
 '025.jpeg\tAshley\tB-ORG',
 '025.jpeg\tFurniture\tI-ORG',
 '025.jpeg\tHomeStore\tI-ORG',
 '025.jpeg\t875\tO',
 '025.jpeg\tE\tO',
 '025.jpeg\tBoughton\tO',
 '025.jpeg\tRoad\tO',
 '025.jpeg\t"Bolingbrook,"\tO',
 '025.jpeg\tIL\tO',
 '025.jpeg\t60440\tO',
 '025.jpeg\twww.ashleyfurniturehomestore.com\tB-EMAIL',
 '027.jpeg\tWALT\tB-ORG',
 '027.jpeg\tDISNEY\tI-ORG',
 '027.jpeg\tPRODUCTIONS\tO',
 '027.jpeg\tKee۪\tO',
 '027.jpeg\tJohn\tB-NAME',
 '027.jpeg\tF.\tI-NAME',
 '027.jpeg\tCurry\tI-NAME',
 '027.jpeg\tDirector\tB-DES',
 '027.jpeg\t2%)\tO',
 '027.jpeg\tHotel\tO',
 '027.jpeg\tDivision\tO',
 '027.jpeg\tams\tO',
 '027.jpeg\t-213\tB-PHONE',
 '027.jpeg\t245-8951\tI-PHONE',
 '027.jpeg\t500\tO',
 '027.jpeg\tSO.\tO',
 '027.jpeg\tBUENA\tO',
 '027.jpeg\tVISTA\tO',
 '027.jpeg\tST.\tO',
 '027.jpeg\t+\tO',
 '027.jpeg\t"BURBANK,"\tO',
 '027.jpeg\tCALIFORNIA\tO',
 '027.jpeg\t91503\tO',
 '028.jpeg\tKUNUNURRA\tO',
 '028.jpeg\tRachell\tB-NAME',
 '028.jpeg\tFewster\tI-NAME',
 '028.jpeg\tShop\tO',
 '028.jpeg\t112b\tO',
 '028.jpeg\tCoolibah\tO',
 '028.jpeg\tDrive\tO',
 '028.jpeg\t418\tO',
 '028.jpeg\t894\tO',
 '028.jpeg\t400\tO',
 '028.jpeg\tKununurrra\tO',
 '028.jpeg\tWA\tO',
 '028.jpeg\t6743\tO',
 '028.jpeg\tPhone:\tO',
 '028.jpeg\t-8\tB-PHONE',
 '028.jpeg\t9168\tI-PHONE',
 '028.jpeg\t1737\tI-PHONE',
 '028.jpeg\tFax:\tO',
 '028.jpeg\t-8\tO',
 '028.jpeg\t9169\tO',
 '028.jpeg\t3940\tO',
 '028.jpeg\tEmail:\tO',
 '028.jpeg\tinfo@subwaykununurra.com.au\tB-EMAIL',
 '028.jpeg\t \tO',
 '030.jpeg\th\tO',
 '030.jpeg\tManaging\tB-DES',
 '030.jpeg\tDirector\tI-DES',
 '030.jpeg\tmail:\tO',
 '030.jpeg\tcustomercare@sho|\tB-EMAIL',
 '030.jpeg\t4reebok.com\tI-EMAIL',
 '030.jpeg\tShreshth\tB-NAME',
 '030.jpeg\tParekh\tI-NAME',
 '030.jpeg\tto\tO',
 '030.jpeg\thead\tO',
 '030.jpeg\tIndian\tO',
 '030.jpeg\toperations\tO',
 '030.jpeg\tReebok\tO',
 '030.jpeg\t \tO',
 '030.jpeg\tadd;\tO',
 '030.jpeg\t"326,"\tO',
 '030.jpeg\tThird\tO',
 '030.jpeg\t"Floor,"\tO',
 '030.jpeg\tChintamani\tO',
 '030.jpeg\t"Plaza,"\tO',
 '030.jpeg\t"Bewing,"\tO',
 '030.jpeg\tAndheri\tO',
 '030.jpeg\t"Chakala,"\tO',
 '030.jpeg\tMumbai\tO',
 '030.jpeg\tReebok\tB-ORG',
 '030.jpeg\tIndia\tI-ORG',
 '030.jpeg\tLtd.\tI-ORG',
 '031.jpeg\tGeneral\tB-DES',
 '031.jpeg\tManager\tI-DES',
 "031.jpeg\tDomino's\tB-ORG",
 '031.jpeg\t54321\tO',
 '031.jpeg\tCaesar\tO',
 '031.jpeg\tBlvd.\tO',
 '031.jpeg\tGardena\tO',
 '031.jpeg\t"Fresh,"\tO',
 '031.jpeg\tCA\tO',
 '031.jpeg\t92337\tO',
 '031.jpeg\tMordan\tO',
 '031.jpeg\tPisa\tO',
 '031.jpeg\tStore:\tO',
 '031.jpeg\t562-543-7689\tO',
 '031.jpeg\tCell:\tO',
 '031.jpeg\t562-456-3210\tB-PHONE',
 '031.jpeg\tmpisa@dominos.com\tB-EMAIL',
 '032.jpeg\t \tO',
 '032.jpeg\t \tO',
 '032.jpeg\tae\tO',
 '032.jpeg\tBe\tO',
 '032.jpeg\t3\tO',
 '032.jpeg\t \tO',
 '033.jpeg\t \tO',
 '033.jpeg\tPRAKASH\tB-NAME',
 '033.jpeg\tKHEDKAR\tI-NAME',
 '033.jpeg\t(Sales\tB-DES',
 '033.jpeg\tOfficer)\tI-DES',
 '033.jpeg\tM.\tO',
 '033.jpeg\t9227576803\tO',
 '033.jpeg\ta\tO',
 '033.jpeg\tLOAN\tO',
 '033.jpeg\tAGAINST\tO',
 '033.jpeg\tPROPERTY\tO',
 '033.jpeg\tBHAVYA\tB-ORG',
 '033.jpeg\tFINANCIAL\tI-ORG',
 '033.jpeg\tSERVICES\tI-ORG',
 '033.jpeg\tHDFC\tO',
 '033.jpeg\tBANK\tO',
 '033.jpeg\t"ASSOCIATE,"\tO',
 '033.jpeg\tMORTGAGE\tO',
 '033.jpeg\tLOANS\tO',
 '033.jpeg\t"1009-1010,"\tO',
 '033.jpeg\tCity\tO',
 '033.jpeg\tCentre\tO',
 '033.jpeg\t"Market,"\tO',
 '033.jpeg\tOpp.\tO',
 '033.jpeg\tA.V.\tO',
 '033.jpeg\t"Sons,"\tO',
 '033.jpeg\tGhod\tO',
 '033.jpeg\tDod\tO',
 '033.jpeg\t"Road,"\tO',
 '033.jpeg\tParle\tO',
 '033.jpeg\t"Point,"\tO',
 '033.jpeg\t"Surat-395007,"\tO',
 '033.jpeg\tPh.\tO',
 '033.jpeg\t261\tB-PHONE',
 '033.jpeg\t2210142\tI-PHONE',
 '033.jpeg\te\tO',
 '033.jpeg\tmail\tO',
 '033.jpeg\t:-\tO',
 '033.jpeg\tpykhedkar07@yahoo.com.\tB-EMAIL',
 '034.jpeg\t \tO',
 '034.jpeg\t   \tO',
 '034.jpeg\t \tO',
 '034.jpeg\t \tO',
 '034.jpeg\t \tO',
 '034.jpeg\t \tO',
 '034.jpeg\t \tO',
 '034.jpeg\t  \tO',
 '034.jpeg\t  \tO',
 '034.jpeg\t  \tO',
 '034.jpeg\t \tO',
 '034.jpeg\tJ\tO',
 '034.jpeg\t"laptop,"\tO',
 '034.jpeg\tComputer\tO',
 '034.jpeg\t&\tO',
 '034.jpeg\tPrinter\tO',
 '034.jpeg\tSales\tO',
 '034.jpeg\tJ\tO',
 '034.jpeg\tLaptop\tO',
 '034.jpeg\t&\tO',
 '034.jpeg\tComputer\tO',
 '034.jpeg\tService\tO',
 '034.jpeg\tJ\tO',
 '034.jpeg\tData\tO',
 '034.jpeg\tRecovery\tO',
 '034.jpeg\t&\tO',
 '034.jpeg\tNetworking\tO',
 '034.jpeg\t/\tO',
 '034.jpeg\tAMC\tO',
 '034.jpeg\t&\tO',
 '034.jpeg\tHouse\tO',
 '034.jpeg\tRepairs\tO',
 '034.jpeg\tService\tO',
 '034.jpeg\tJ\tO',
 '034.jpeg\tPrinter\tO',
 '034.jpeg\tRepairs\tO',
 '034.jpeg\t@\tO',
 '034.jpeg\tToner\tO',
 '034.jpeg\tRefiling\tO',
 '034.jpeg\tJ\tO',
 '034.jpeg\tAll\tO',
 '034.jpeg\tType\tO',
 '034.jpeg\tof\tO',
 '034.jpeg\tAccessories\tO',
 '034.jpeg\t/\tO',
 '034.jpeg\tCCTv.\tO',
 '034.jpeg\tCamera\tO',
 '034.jpeg\t/\tO',
 '034.jpeg\tWeb\tO',
 '034.jpeg\tHosting\tO',
 '034.jpeg\t&\tO',
 '034.jpeg\tDomain\tO',
 '034.jpeg\tRegister\tO',
 '034.jpeg\tJ\tO',
 '034.jpeg\tInstant\tO',
 '034.jpeg\tWeb\tO',
 '034.jpeg\tDevelopment\tO',
 '034.jpeg\t/\tO',
 '034.jpeg\tSoftware\tO',
 '034.jpeg\tDevelopment\tO',
 '034.jpeg\t \tO',
 '034.jpeg\tinfoTech\tO',
 '034.jpeg\tDo\tO',
 '034.jpeg\tSomething\tO',
 '034.jpeg\tBig\tO',
 '034.jpeg\t9898\tB-PHONE',
 '034.jpeg\t24\tI-PHONE',
 '034.jpeg\t4020\tI-PHONE',
 '034.jpeg\t9033\tI-PHONE',
 '034.jpeg\t25\tI-PHONE',
 '034.jpeg\t1418\tI-PHONE',
 '034.jpeg\t\tO',
 '034.jpeg\tperfectinfotech2013@gmail.com\tB-EMAIL',
 '034.jpeg\t@\tO',
 '034.jpeg\t"124,"\tO',
 '034.jpeg\tGurukrupa\tO',
 '034.jpeg\t"Complex,"\tO',
 '034.jpeg\tTalod-Majara\tO',
 '034.jpeg\tRoad\tO',
 '034.jpeg\t"Beside,"\tO',
 '034.jpeg\tMamlatdar\tO',
 '034.jpeg\t"Kacheri,"\tO',
 '034.jpeg\tTalod.\tO',
 '034.jpeg\t \tO',
 '035.jpeg\tCraig\tB-NAME',
 '035.jpeg\tForman\tI-NAME',
 '035.jpeg\tdi.\tO',
 '035.jpeg\tService\tB-ORG',
 '035.jpeg\tMax\tI-ORG',
 '035.jpeg\tLLC\tI-ORG',
 '035.jpeg\t25\tO',
 '035.jpeg\tPine\tO',
 '035.jpeg\tStreet\tO',
 '035.jpeg\t-\tO',
 '035.jpeg\tSuite\tO',
 '035.jpeg\t8\tO',
 '035.jpeg\tFacility\tO',
 '035.jpeg\tMaintenance\tO',
 '035.jpeg\t&\tO',

In [38]:
def add(a,b):
    return a + b
list(map(add,[2,1,2,3],[3,4,5,6]))

[5, 5, 7, 9]

#### lambda arguments: expression

In [44]:
pr = lambda x: print(x)

pr("ashish")

ashish

In [61]:
data = list( map(lambda x:x.split('\t'), text.split('\n')))

In [62]:
data

[['id', 'text', 'tag'],
 ['000.jpeg', ' ', 'O'],
 ['000.jpeg', '.', 'O'],
 ['000.jpeg', '040-4852', 'B-PHONE'],
 ['000.jpeg', '"8881,"', 'I-PHONE'],
 ['000.jpeg', '90309', 'B-PHONE'],
 ['000.jpeg', '52549', 'I-PHONE'],
 ['000.jpeg', 'Fi', 'O'],
 ['000.jpeg', '/laurelsoverseaseducation', 'O'],
 ['000.jpeg', '@:', 'O'],
 ['000.jpeg', 'LAURELS', 'B-ORG'],
 ['000.jpeg', 'OVERSEAS', 'I-ORG'],
 ['000.jpeg', 'EDUCATIONAL', 'I-ORG'],
 ['000.jpeg', 'CONSULTANCY', 'I-ORG'],
 ['000.jpeg', 'PVT.', 'I-ORG'],
 ['000.jpeg', 'LTD.', 'I-ORG'],
 ['000.jpeg', 'Sea', 'O'],
 ['000.jpeg', '|', 'O'],
 ['000.jpeg', 'U.K', 'O'],
 ['000.jpeg', 'AUSTRALIA', 'O'],
 ['000.jpeg', 'CANADA', 'O'],
 ['000.jpeg', 'IRELAND', 'O'],
 ['000.jpeg', ' ', 'O'],
 ['000.jpeg', ' ', 'O'],
 ['000.jpeg', ' ', 'O'],
 ['000.jpeg', ' ', 'O'],
 ['000.jpeg', ' ', 'O'],
 ['000.jpeg', ' ', 'O'],
 ['000.jpeg', 'www.laurelseducation.com', 'B-WEB'],
 ['000.jpeg', ')%info@laurelseducation.com', 'B-EMAIL'],
 ['000.jpeg', ' ', 'O'],
 ['001.jpeg', 'john', 'B-NAME'],
 ['001.jpeg', 'smith', 'I-NAME'],
 ['001.jpeg', 'marketing', 'B-DES'],
 ['001.jpeg', 'manager', 'I-DES'],
 ['001.jpeg', 'web:', 'O'],
 ['001.jpeg', 'www.psdgraphics.com', 'B-WEB'],
 ['001.jpeg', 'phone:', 'O'],
 ['001.jpeg', '123-456-7890', 'B-PHONE'],
 ['001.jpeg', 'mail:', 'O'],
 ['001.jpeg', 'email@psdgraphics.com', 'B-EMAIL'],
 ['002.jpeg', '    ', 'O'],
 ['002.jpeg', '   ', 'O'],
 ['002.jpeg', 'Sau', 'O'],
 ['002.jpeg', '0', 'O'],
 ['002.jpeg', '98489', 'B-PHONE'],
 ['002.jpeg', '24441', 'I-PHONE'],
 ['002.jpeg', 'dy', 'O'],
 ['002.jpeg', '"08672,"', 'O'],
 ['002.jpeg', '224441', 'O'],
 ['002.jpeg', '/ENKATESWAPA', 'B-ORG'],
 ['002.jpeg', '&', 'O'],
 ['002.jpeg', 'wie', 'O'],
 ['002.jpeg', ' ', 'O'],
 ['002.jpeg', '=', 'O'],
 ['002.jpeg', ' ', 'O'],
 ['003.jpeg', 'Prasad', 'B-NAME'],
 ['003.jpeg', '@', 'O'],
 ['003.jpeg', '"9,96,31,73,53,59,49,04,00,000"', 'O'],
 ['003.jpeg', '  ', 'O'],
 ['003.jpeg', '   ', 'O'],
 ['003.jpeg', 'i', 'O'],
 ['003.jpeg', 'Flex', 'O'],
 ['003.jpeg', 'Design', 'O'],
 ['003.jpeg', '#', 'O'],
 ['003.jpeg', 'Album', 'O'],
 ['003.jpeg', 'Design', 'O'],
 ['003.jpeg', '', 'O'],
 ['003.jpeg', 'Visiting', 'O'],
 ['003.jpeg', 'Cards', 'O'],
 ['003.jpeg', 'DTP', 'O'],
 ['003.jpeg', 'Works', 'O'],
 ['003.jpeg', '(Telugu', 'O'],
 ['003.jpeg', '&', 'O'],
 ['003.jpeg', 'English)', 'O'],
 ['003.jpeg', ' ', 'O'],
 ['003.jpeg', ' ', 'O'],
 ['003.jpeg', ' ', 'O'],
 ['003.jpeg', ' ', 'O'],
 ['004.jpeg', '<=>', 'O'],
 ['004.jpeg', 'Madison', 'B-ORG'],
 ['004.jpeg', 'Yacht', 'I-ORG'],
 ['004.jpeg', 'Sales', 'I-ORG'],
 ['004.jpeg', 'Paul', 'B-NAME'],
 ['004.jpeg', 'Madison', 'I-NAME'],
 ['004.jpeg', 'Yacht', 'B-DES'],
 ['004.jpeg', 'Broker', 'I-DES'],
 ['004.jpeg', '-', 'O'],
 ['004.jpeg', 'Northeast', 'O'],
 ['004.jpeg', 'Region', 'O'],
 ['004.jpeg', '   ', 'O'],
 ['004.jpeg', '  ', 'O'],
 ['004.jpeg', ' ', 'O'],
 ['004.jpeg', 'Fax:', 'O'],
 ['004.jpeg', '718-444-1206', 'B-PHONE'],
 ['004.jpeg', '  ', 'O'],
 ['007.jpeg', 'www', 'B-WEB'],
 ['007.jpeg', 'phototomics.com', 'I-WEB'],
 ['007.jpeg', 'PHOTOT', 'B-ORG'],
 ['007.jpeg', 'Thomas', 'B-NAME'],
 ['007.jpeg', 'Atkins', 'I-NAME'],
 ['007.jpeg', 'Photographer', 'B-DES'],
 ['007.jpeg', 'and', 'I-DES'],
 ['007.jpeg', 'Digital', 'I-DES'],
 ['007.jpeg', 'Artist', 'I-DES'],
 ['007.jpeg', 'tatkins@phototomics.com', 'B-EMAIL'],
 ['007.jpeg', 'Phototomics', 'O'],
 ['007.jpeg', '3419', 'O'],
 ['007.jpeg', 'Via', 'O'],
 ['007.jpeg', 'Lido', 'O'],
 ['007.jpeg', '#340', 'O'],
 ['007.jpeg', 'Newport', 'O'],
 ['007.jpeg', 'Beach', 'O'],
 ['007.jpeg', 'CA', 'O'],
 ['007.jpeg', '-', 'O'],
 ['007.jpeg', 'California', 'O'],
 ['007.jpeg', '92663', 'O'],
 ['007.jpeg', ' ', 'O'],
 ['008.jpeg', ' ', 'O'],
 ['008.jpeg', 'Reddy', 'O'],
 ['008.jpeg', '9866186785', 'B-PHONE'],
 ['008.jpeg', '   ', 'O'],
 ['008.jpeg', ' ', 'O'],
 ['008.jpeg', 'Opp', 'O'],
 ['008.jpeg', 'Ramakrishna', 'O'],
 ['008.jpeg', '"Theatre,Main"', 'O'],
 ['008.jpeg', 'Road', 'O'],
 ['008.jpeg', '"Peddapalli,"', 'O'],
 ['008.jpeg', 'Dist', 'O'],
 ['008.jpeg', ':', 'O'],
 ['008.jpeg', '"Karimnagar,"', 'O'],
 ['008.jpeg', 'Telangana', 'O'],
 ['008.jpeg', '-', 'O'],
 ['008.jpeg', '505172', 'O'],
 ['008.jpeg', 'email', 'O'],
 ['008.jpeg', ':', 'O'],
 ['008.jpeg', 'srihithaads.pdpl@', 'B-EMAIL'],
 ['008.jpeg', 'gmail.com', 'I-EMAIL'],
 ['008.jpeg', ' ', 'O'],
 ['009.jpeg', 'Saja', 'B-NAME'],
 ['009.jpeg', '(Vik):', 'O'],
 ['009.jpeg', '990083000', 'B-PHONE'],
 ['009.jpeg', 'G.S.M.', 'B-ORG'],
 ['009.jpeg', 'BOOSTER', 'I-ORG'],
 ['009.jpeg', '1)', 'O'],
 ['009.jpeg', 'All', 'O'],
 ['009.jpeg', 'Types', 'O'],
 ['009.jpeg', 'of', 'O'],
 ['009.jpeg', 'Mobile', 'O'],
 ['009.jpeg', '"Repair,"', 'O'],
 ['009.jpeg', '', 'O'],
 ['009.jpeg', 'Data', 'O'],
 ['009.jpeg', 'Transfer', 'O'],
 ['009.jpeg', '-', 'O'],
 ['009.jpeg', 'Game', 'O'],
 ['009.jpeg', '&', 'O'],
 ['009.jpeg', 'Application', 'O'],
 ['009.jpeg', 'Led', 'O'],
 ['009.jpeg', 'Touch', 'O'],
 ['009.jpeg', 'Glass', 'O'],
 ['009.jpeg', '"Change,"', 'O'],
 ['009.jpeg', 'All', 'O'],
 ['009.jpeg', 'Mobile', 'O'],
 ['009.jpeg', 'Led', 'O'],
 ['009.jpeg', '"Fitting,"', 'O'],
 ['009.jpeg', 'Mobile', 'O'],
 ['009.jpeg', 'Repair', 'O'],
 ['009.jpeg', 'Training', 'O'],
 ['009.jpeg', '"loor,"', 'O'],
 ['009.jpeg', 'City', 'O'],
 ['009.jpeg', 'Centre', 'O'],
 ['009.jpeg', '"Mall,"', 'O'],
 ['009.jpeg', 'Opp.', 'O'],
 ['009.jpeg', '"mbai-Central,"', 'O'],
 ['009.jpeg', 'Mumbai', 'O'],
 ['009.jpeg', '-', 'O'],
 ['009.jpeg', '400', 'O'],
 ['009.jpeg', '8', 'O'],
 ['009.jpeg', '  ', 'O'],
 ['009.jpeg', ' ', 'O'],
 ['009.jpeg', '  ', 'O'],
 ['009.jpeg', '   ', 'O'],
 ['009.jpeg', '  ', 'O'],
 ['009.jpeg', '  ', 'O'],
 ['009.jpeg', '_Ӊ_B:E:S.T.', 'O'],
 ['010.jpeg', 'Dr.', 'B-NAME'],
 ['010.jpeg', 'Michael', 'I-NAME'],
 ['010.jpeg', 'Dean', 'I-NAME'],
 ['010.jpeg', 'Clarinet', 'O'],
 ['010.jpeg', 'Performing', 'O'],
 ['010.jpeg', 'Teaching', 'B-DES'],
 ['010.jpeg', 'and', 'I-DES'],
 ['010.jpeg', 'Consulting', 'I-DES'],
 ['010.jpeg', '682.888.7639', 'B-PHONE'],
 ['010.jpeg', 'clarinetmike.com', 'B-WEB'],
 ['010.jpeg', 'clarinetmike.wordpress.com', 'B-WEB'],
 ['010.jpeg', 'clarinetmiketexas@', 'B-EMAIL'],
 ['010.jpeg', 'yahoo.com', 'I-EMAIL'],
 ['010.jpeg', ' ', 'O'],
 ['011.jpeg', 'a', 'O'],
 ['011.jpeg', ':', 'O'],
 ['011.jpeg', 'Cell', 'O'],
 ['011.jpeg', ':', 'O'],
 ['011.jpeg', '9885050228', 'B-PHONE'],
 ['011.jpeg', 'Krishna', 'B-NAME'],
 ['011.jpeg', '3257779', 'B-PHONE'],
 ['011.jpeg', '\\', 'O'],
 ['011.jpeg', '9393937799', 'B-PHONE'],
 ['011.jpeg', ' ', 'O'],
 ['011.jpeg', '    ', 'O'],
 ['011.jpeg', ' ', 'O'],
 ['011.jpeg', ' ', 'O'],
 ['011.jpeg', 'D.No.', 'O'],
 ['011.jpeg', '"27-33-19,"', 'O'],
 ['011.jpeg', 'Satnam', 'O'],
 ['011.jpeg', '"Towers,"', 'O'],
 ['011.jpeg', 'Opp:', 'O'],
 ['011.jpeg', 'Buckingham', 'O'],
 ['011.jpeg', 'Post', 'O'],
 ['011.jpeg', '"Office,"', 'O'],
 ['011.jpeg', 'Gudavallivari', 'O'],
 ['011.jpeg', '"St.,"', 'O'],
 ['011.jpeg', '"Governorpeta,"', 'O'],
 ['011.jpeg', 'Vijayawada.', 'O'],
 ['011.jpeg', 'at', 'O'],
 ['012.jpeg', 'Cell:', 'O'],
 ['012.jpeg', '7396379143', 'B-PHONE'],
 ['012.jpeg', ' ', 'O'],
 ['013.jpeg', 'Mobile:73963791', 'B-PHONE'],
 ['013.jpeg', '43', 'O'],
 ['013.jpeg', 'FLEX.', 'O'],
 ['013.jpeg', 'PRINT', 'O'],
 ['013.jpeg', 'az', 'O'],
 ['013.jpeg', 'Designing', 'O'],
 ['013.jpeg', '&', 'O'],
 ['013.jpeg', 'Printing', 'O'],
 ['013.jpeg', ' ', 'O'],
 ['013.jpeg', '   ', 'O'],
 ['013.jpeg', 'CL', 'O'],
 ['013.jpeg', ' ', 'O'],
 ['013.jpeg', 'EL', 'O'],
 ['013.jpeg', '   ', 'O'],
 ['013.jpeg', ' ', 'O'],
 ['014.jpeg', 'Mob:-8445790640', 'B-PHONE'],
 ['014.jpeg', 'Siyalg', 'O'],
 ['014.jpeg', 'All', 'O'],
 ['014.jpeg', 'Kind', 'O'],
 ['014.jpeg', '"Charger,"', 'O'],
 ['014.jpeg', '"Earphones,"', 'O'],
 ['014.jpeg', 'Mobile', 'O'],
 ['014.jpeg', '"Photostate,"', 'O'],
 ['014.jpeg', '&Anygkindlof', 'O'],
 ['014.jpeg', 'Online', 'O'],
 ['014.jpeg', 'Works.', 'O'],
 ['014.jpeg', ' ', 'O'],
 ['014.jpeg', ' ', 'O'],
 ['015.jpeg', ' ', 'O'],
 ['015.jpeg', '4!', 'O'],
 ['015.jpeg', 'Shri', 'O'],
 ['015.jpeg', 'Ganeshay', 'O'],
 ['015.jpeg', 'Namah', 'O'],
 ['015.jpeg', '!t', 'O'],
 ['015.jpeg', 'M.', 'O'],
 ['015.jpeg', '70147-98128', 'B-PHONE'],
 ['015.jpeg', ' ', 'O'],
 ['015.jpeg', 'BAJA', 'O'],
 ['015.jpeg', 'Deals', 'O'],
 ['015.jpeg', 'in', 'O'],
 ['015.jpeg', ':', 'O'],
 ['015.jpeg', 'All', 'O'],
 ['015.jpeg', 'Kinds', 'O'],
 ['015.jpeg', 'of', 'O'],
 ['015.jpeg', 'New', 'O'],
 ['015.jpeg', 'Mobile', 'O'],
 ['015.jpeg', '"Handset,"', 'O'],
 ['015.jpeg', 'Tempered', 'O'],
 ['015.jpeg', 'Glass', 'O'],
 ['015.jpeg', 'FINSERV', 'O'],
 ['015.jpeg', 'Fancy', 'O'],
 ['015.jpeg', '"Covers,"', 'O'],
 ['015.jpeg', 'Accessories', 'O'],
 ['015.jpeg', 'Available', 'O'],
 ['015.jpeg', 'Here', 'O'],
 ['015.jpeg', ' ', 'O'],
 ['015.jpeg', 'SAMSUNG', 'O'],
 ['015.jpeg', 'OPPO', 'O'],
 ['015.jpeg', 'Vivo', 'O'],
 ['015.jpeg', 'Jenovo', 'O'],
 ['015.jpeg', '@', 'O'],
 ['015.jpeg', 'iPhone', 'O'],
 ['015.jpeg', 'mobile', 'O'],
 ['015.jpeg', 'GIONEE', 'O'],
 ['015.jpeg', '  ', 'O'],
 ['015.jpeg', ' ', 'O'],
 ['016.jpeg', '    ', 'O'],
 ['016.jpeg', '91', 'B-PHONE'],
 ['016.jpeg', '9087253526', 'I-PHONE'],
 ['016.jpeg', '91', 'B-PHONE'],
 ['016.jpeg', '9087252666', 'I-PHONE'],
 ['016.jpeg', 'oe', 'O'],
 ['016.jpeg', 'raghuvijayan104@gmail.com', 'B-EMAIL'],
 ['017.jpeg', 'Y-Wireless', 'B-ORG'],
 ['017.jpeg', 'Repair', 'I-ORG'],
 ['017.jpeg', ' ', 'O'],
 ['017.jpeg', ' ', 'O'],
 ['017.jpeg', ' ', 'O'],
 ['017.jpeg', ' ', 'O'],
 ['017.jpeg', ' ', 'O'],
 ['017.jpeg', ' ', 'O'],
 ['017.jpeg', 'eee', 'O'],
 ['017.jpeg', 'Certified', 'O'],
 ['017.jpeg', 'Technician', 'O'],
 ['017.jpeg', 'Phone', 'O'],
 ['017.jpeg', '', 'O'],
 ['017.jpeg', 'Tablet', 'O'],
 ['017.jpeg', '-', 'O'],
 ['017.jpeg', 'Electronic', 'O'],
 ['017.jpeg', 'Repairs', 'O'],
 ['017.jpeg', 'Call', 'O'],
 ['017.jpeg', 'us', 'O'],
 ['017.jpeg', '330-270-5060', 'B-PHONE'],
 ['017.jpeg', 'facebook.com/YoungstownWirelessRepair', 'O'],
 ['018.jpeg', ' ', 'O'],
 ['018.jpeg', 'Cell', 'O'],
 ['018.jpeg', 'Phone', 'B-ORG'],
 ['018.jpeg', 'Repair', 'I-ORG'],
 ['018.jpeg', 'Center', 'I-ORG'],
 ['018.jpeg', '6795', 'O'],
 ['018.jpeg', 'Wilson', 'O'],
 ['018.jpeg', '"Blvd,"', 'O'],
 ['018.jpeg', 'Suite', 'O'],
 ['018.jpeg', '26', 'O'],
 ['018.jpeg', 'BUY', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'SELL', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'TRADE', 'O'],
 ['018.jpeg', 'Falls', 'O'],
 ['018.jpeg', '"Church,"', 'O'],
 ['018.jpeg', 'VA', 'O'],
 ['018.jpeg', '22044', 'O'],
 ['018.jpeg', 'TEL:', 'O'],
 ['018.jpeg', '571', 'B-PHONE'],
 ['018.jpeg', '606', 'I-PHONE'],
 ['018.jpeg', '6636', 'I-PHONE'],
 ['018.jpeg', '/', 'O'],
 ['018.jpeg', '571606', 'I-PHONE'],
 ['018.jpeg', '3445', 'I-PHONE'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', '"iPhone,"', 'O'],
 ['018.jpeg', 'iPad', 'O'],
 ['018.jpeg', '02-03-2004', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'HTC', 'O'],
 ['018.jpeg', 'Repair', 'O'],
 ['018.jpeg', 'eam', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Samsung', 'O'],
 ['018.jpeg', 'Repair', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Trackball', 'O'],
 ['018.jpeg', 'Repair', 'O'],
 ['018.jpeg', 'htc', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Cracked', 'O'],
 ['018.jpeg', 'Screens', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Water', 'O'],
 ['018.jpeg', 'Damage', 'O'],
 ['018.jpeg', '', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Speakers', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Charger', 'O'],
 ['018.jpeg', 'Port', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Software', 'O'],
 ['018.jpeg', 'Update', 'O'],
 ['018.jpeg', 'NOKIA', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Password', 'O'],
 ['018.jpeg', 'Reset', 'O'],
 ['018.jpeg', '..and', 'O'],
 ['018.jpeg', 'almost', 'O'],
 ['018.jpeg', 'any', 'O'],
 ['018.jpeg', 'hardware', 'O'],
 ['018.jpeg', 'or', 'O'],
 ['018.jpeg', 'software', 'O'],
 ['018.jpeg', 'issue!', 'O'],
 ['018.jpeg', 'Eden', 'O'],
 ['018.jpeg', 'Center', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Seven', 'O'],
 ['018.jpeg', 'Corner', 'O'],
 ['018.jpeg', '-', 'O'],
 ['018.jpeg', 'Route', 'O'],
 ['018.jpeg', '50', 'O'],
 ['018.jpeg', ' ', 'O'],
 ['020.jpeg', 'MOBILE', 'B-ORG'],
 ['020.jpeg', 'REPAIR', 'I-ORG'],
 ['020.jpeg', 'CENTRE', 'I-ORG'],
 ['020.jpeg', 'ON-SITE', 'O'],
 ['020.jpeg', 'REPAIRS', 'O'],
 ['020.jpeg', 'WHILE', 'O'],
 ['020.jpeg', 'YOU', 'O'],
 ['020.jpeg', 'WAIT', 'O'],
 ['020.jpeg', 'INSTANT', 'O'],
 ['020.jpeg', 'UNLOCKING', 'O'],
 ['020.jpeg', 'SOLUTIONS', 'O'],
 ['020.jpeg', 'DAMAGED', 'O'],
 ['020.jpeg', 'LCD', 'O'],
 ['020.jpeg', 'SCREENS', 'O'],
 ['020.jpeg', 'REPLACED', 'O'],
 ['020.jpeg', 'WATERILIQUID', 'O'],
 ['020.jpeg', 'DAMAGED', 'O'],
 ['020.jpeg', 'PHONES', 'O'],
 ['020.jpeg', '"CHARGING,"', 'O'],
 ['020.jpeg', 'AUDIO', 'O'],
 ['020.jpeg', '&', 'O'],
 ['020.jpeg', 'SIGNAL', 'O'],
 ['020.jpeg', 'PROBLEMS', 'O'],
 ['020.jpeg', 'SOFTWARE', 'O'],
 ['020.jpeg', 'PROBLEMS', 'O'],
 ['020.jpeg', 'REPLACEMENT', 'O'],
 ['020.jpeg', 'LOAN', 'O'],
 ['020.jpeg', 'PHONES', 'O'],
 ['020.jpeg', 'AVAILABLE', 'O'],
 ['020.jpeg', 'WHILE', 'O'],
 ['020.jpeg', 'YOUR', 'O'],
 ['020.jpeg', 'PHONE', 'O'],
 ['020.jpeg', 'IS', 'O'],
 ['020.jpeg', 'BEING', 'O'],
 ['020.jpeg', 'REPAIRED', 'O'],
 ['020.jpeg', 'NO-FIX', 'O'],
 ['020.jpeg', 'NO-FEE', 'O'],
 ['020.jpeg', '  ', 'O'],
 ['020.jpeg', '  ', 'O'],
 ['020.jpeg', '20', 'B-PHONE'],
 ['020.jpeg', '87499933', 'I-PHONE'],
 ['020.jpeg', 'WWW.MPRC.CO', 'B-WEB'],
 ['021.jpeg', 'Ezy', 'B-ORG'],
 ['021.jpeg', 'Fit', 'I-ORG'],
 ['021.jpeg', ' ', 'O'],
 ['021.jpeg', ' ', 'O'],
 ['021.jpeg', '  ', 'O'],
 ['021.jpeg', '   ', 'O'],
 ['021.jpeg', '    ', 'O'],
 ['021.jpeg', '  ', 'O'],
 ['021.jpeg', ' ', 'O'],
 ['021.jpeg', '+', 'O'],
 ['021.jpeg', 'Senice', 'O'],
 ['021.jpeg', '+', 'O'],
 ['021.jpeg', 'Brakes', 'O'],
 ['021.jpeg', ' ', 'O'],
 ['021.jpeg', '91', 'O'],
 ['021.jpeg', 'Portland', 'O'],
 ['021.jpeg', '"Rd,"', 'O'],
 ['021.jpeg', 'Hucknall', 'O'],
 ['021.jpeg', 'Timing', 'O'],
 ['021.jpeg', 'Belts', 'O'],
 ['021.jpeg', 'NG15', 'O'],
 ['021.jpeg', '7DS', 'O'],
 ['021.jpeg', '+', 'O'],
 ['021.jpeg', 'Suspension', 'O'],
 ['021.jpeg', 'Opp', 'O'],
 ['021.jpeg', 'Sandicliffe', 'O'],
 ['021.jpeg', 'Ford', 'O'],
 ['021.jpeg', '+', 'O'],
 ['021.jpeg', 'Diagnostics', 'O'],
 ['021.jpeg', '+', 'O'],
 ['021.jpeg', 'Batteries', 'O'],
 ['021.jpeg', 'Free', 'O'],
 ['021.jpeg', 'Brake', 'O'],
 ['021.jpeg', 'Check', 'O'],
 ['021.jpeg', ' ', 'O'],
 ['021.jpeg', ' ', 'O'],
 ['021.jpeg', 'Email:', 'O'],
 ['021.jpeg', 'co.uk', 'O'],
 ['021.jpeg', 'Web:', 'O'],
 ['021.jpeg', 'www.ezyfitautocentre.co.uk', 'B-WEB'],
 ['022.jpeg', 'Dale', 'B-NAME'],
 ['022.jpeg', 'Steffen', 'I-NAME'],
 ['022.jpeg', 'Club', 'B-DES'],
 ['022.jpeg', 'Manager', 'I-DES'],
 ['022.jpeg', ' ', 'O'],
 ['022.jpeg', 'PLANET', 'O'],
 ['022.jpeg', 'FITNESS', 'O'],
 ['022.jpeg', '|', 'O'],
 ['022.jpeg', 'HOME', 'O'],
 ['022.jpeg', 'of', 'O'],
 ['022.jpeg', 'the', 'O'],
 ['022.jpeg', 'JUDGEMENT', 'O'],
 ['022.jpeg', 'FREE', 'O'],
 ['022.jpeg', 'ZONE', 'O'],
 ['022.jpeg', '9652', 'O'],
 ['022.jpeg', 'S.', 'O'],
 ['022.jpeg', 'Roberts', 'O'],
 ['022.jpeg', 'Rd.', 'O'],
 ['022.jpeg', '|', 'O'],
 ['022.jpeg', 'Hickory', 'O'],
 ['022.jpeg', '"Hills,"', 'O'],
 ['022.jpeg', 'IL', 'O'],
 ['022.jpeg', '60457', 'O'],
 ['022.jpeg', 'Ayes', 'O'],
 ['022.jpeg', 'P:', 'O'],
 ['022.jpeg', '708.598.1010', 'B-PHONE'],
 ['022.jpeg', 'planetfitness.com', 'B-WEB'],
 ['023.jpeg', 'Hilton', 'B-ORG'],
 ['023.jpeg', 'Oak', 'I-ORG'],
 ['023.jpeg', 'Lawn', 'I-ORG'],
 ['023.jpeg', 'Heather', 'B-NAME'],
 ['023.jpeg', 'Stevens', 'I-NAME'],
 ['023.jpeg', 'Catering', 'B-DES'],
 ['023.jpeg', 'Manager', 'I-DES'],
 ['023.jpeg', '9333', 'O'],
 ['023.jpeg', 'South', 'O'],
 ['023.jpeg', 'Cicero', 'O'],
 ['023.jpeg', 'Avenue', 'O'],
 ['023.jpeg', 'Oak', 'O'],
 ['023.jpeg', '"Lawn,"', 'O'],
 ['023.jpeg', 'IL', 'O'],
 ['023.jpeg', '60453', 'O'],
 ['023.jpeg', 'Tel:', 'O'],
 ['023.jpeg', '708', 'B-PHONE'],
 ['023.jpeg', '425', 'I-PHONE'],
 ['023.jpeg', '7800', 'I-PHONE'],
 ['023.jpeg', 'Direct', 'O'],
 ['023.jpeg', 'Line:', 'O'],
 ['023.jpeg', '708', 'O'],
 ['023.jpeg', '229', 'O'],
 ['023.jpeg', '8859', 'O'],
 ['023.jpeg', 'Fax:', 'O'],
 ['023.jpeg', '708', 'O'],
 ['023.jpeg', '229', 'O'],
 ['023.jpeg', '8858', 'O'],
 ['023.jpeg', 'email:', 'O'],
 ['023.jpeg', 'heather.stevens@hilton.com', 'B-EMAIL'],
 ['023.jpeg', 'HONORS', 'O'],
 ['023.jpeg', 'HILTON', 'O'],
 ['023.jpeg', 'official', 'O'],
 ['023.jpeg', 'Sponsor', 'O'],
 ['024.jpeg', '-', 'O'],
 ['024.jpeg', 'Mobile:', 'B-ORG'],
 ['024.jpeg', 'limited', 'I-ORG'],
 ['024.jpeg', 'Marian', 'B-NAME'],
 ['024.jpeg', 'Piontek', 'I-NAME'],
 ['024.jpeg', '-708', 'B-PHONE'],
 ['024.jpeg', '890-8911', 'I-PHONE'],
 ['024.jpeg', '7884', 'O'],
 ['024.jpeg', 'N', 'O'],
 ['024.jpeg', 'Milwaukee', 'O'],
 ['024.jpeg', 'Ave', 'O'],
 ['024.jpeg', '"Niles,"', 'O'],
 ['024.jpeg', 'IL', 'O'],
 ['024.jpeg', '60714', 'O'],
 ['024.jpeg', 'mpiontek@neptunemobile.com', 'B-EMAIL'],
 ['025.jpeg', 'FURNITURE', 'O'],
 ['025.jpeg', ' ', 'O'],
 ['025.jpeg', 'Victor', 'B-NAME'],
 ['025.jpeg', 'Harris', 'I-NAME'],
 ['025.jpeg', 'Jr', 'I-NAME'],
 ['025.jpeg', 'Sales', 'B-DES'],
 ['025.jpeg', 'Associate', 'B-DES'],
 ['025.jpeg', 'tel', 'O'],
 ['025.jpeg', '630.783.2346', 'B-PHONE'],
 ['025.jpeg', 'fax', 'O'],
 ['025.jpeg', '630.783.1175', 'O'],
 ['025.jpeg', 'Ashley', 'B-ORG'],
 ['025.jpeg', 'Furniture', 'I-ORG'],
 ['025.jpeg', 'HomeStore', 'I-ORG'],
 ['025.jpeg', '875', 'O'],
 ['025.jpeg', 'E', 'O'],
 ['025.jpeg', 'Boughton', 'O'],
 ['025.jpeg', 'Road', 'O'],
 ['025.jpeg', '"Bolingbrook,"', 'O'],
 ['025.jpeg', 'IL', 'O'],
 ['025.jpeg', '60440', 'O'],
 ['025.jpeg', 'www.ashleyfurniturehomestore.com', 'B-EMAIL'],
 ['027.jpeg', 'WALT', 'B-ORG'],
 ['027.jpeg', 'DISNEY', 'I-ORG'],
 ['027.jpeg', 'PRODUCTIONS', 'O'],
 ['027.jpeg', 'Kee۪', 'O'],
 ['027.jpeg', 'John', 'B-NAME'],
 ['027.jpeg', 'F.', 'I-NAME'],
 ['027.jpeg', 'Curry', 'I-NAME'],
 ['027.jpeg', 'Director', 'B-DES'],
 ['027.jpeg', '2%)', 'O'],
 ['027.jpeg', 'Hotel', 'O'],
 ['027.jpeg', 'Division', 'O'],
 ['027.jpeg', 'ams', 'O'],
 ['027.jpeg', '-213', 'B-PHONE'],
 ['027.jpeg', '245-8951', 'I-PHONE'],
 ['027.jpeg', '500', 'O'],
 ['027.jpeg', 'SO.', 'O'],
 ['027.jpeg', 'BUENA', 'O'],
 ['027.jpeg', 'VISTA', 'O'],
 ['027.jpeg', 'ST.', 'O'],
 ['027.jpeg', '+', 'O'],
 ['027.jpeg', '"BURBANK,"', 'O'],
 ['027.jpeg', 'CALIFORNIA', 'O'],
 ['027.jpeg', '91503', 'O'],
 ['028.jpeg', 'KUNUNURRA', 'O'],
 ['028.jpeg', 'Rachell', 'B-NAME'],
 ['028.jpeg', 'Fewster', 'I-NAME'],
 ['028.jpeg', 'Shop', 'O'],
 ['028.jpeg', '112b', 'O'],
 ['028.jpeg', 'Coolibah', 'O'],
 ['028.jpeg', 'Drive', 'O'],
 ['028.jpeg', '418', 'O'],
 ['028.jpeg', '894', 'O'],
 ['028.jpeg', '400', 'O'],
 ['028.jpeg', 'Kununurrra', 'O'],
 ['028.jpeg', 'WA', 'O'],
 ['028.jpeg', '6743', 'O'],
 ['028.jpeg', 'Phone:', 'O'],
 ['028.jpeg', '-8', 'B-PHONE'],
 ['028.jpeg', '9168', 'I-PHONE'],
 ['028.jpeg', '1737', 'I-PHONE'],
 ['028.jpeg', 'Fax:', 'O'],
 ['028.jpeg', '-8', 'O'],
 ['028.jpeg', '9169', 'O'],
 ['028.jpeg', '3940', 'O'],
 ['028.jpeg', 'Email:', 'O'],
 ['028.jpeg', 'info@subwaykununurra.com.au', 'B-EMAIL'],
 ['028.jpeg', ' ', 'O'],
 ['030.jpeg', 'h', 'O'],
 ['030.jpeg', 'Managing', 'B-DES'],
 ['030.jpeg', 'Director', 'I-DES'],
 ['030.jpeg', 'mail:', 'O'],
 ['030.jpeg', 'customercare@sho|', 'B-EMAIL'],
 ['030.jpeg', '4reebok.com', 'I-EMAIL'],
 ['030.jpeg', 'Shreshth', 'B-NAME'],
 ['030.jpeg', 'Parekh', 'I-NAME'],
 ['030.jpeg', 'to', 'O'],
 ['030.jpeg', 'head', 'O'],
 ['030.jpeg', 'Indian', 'O'],
 ['030.jpeg', 'operations', 'O'],
 ['030.jpeg', 'Reebok', 'O'],
 ['030.jpeg', ' ', 'O'],
 ['030.jpeg', 'add;', 'O'],
 ['030.jpeg', '"326,"', 'O'],
 ['030.jpeg', 'Third', 'O'],
 ['030.jpeg', '"Floor,"', 'O'],
 ['030.jpeg', 'Chintamani', 'O'],
 ['030.jpeg', '"Plaza,"', 'O'],
 ['030.jpeg', '"Bewing,"', 'O'],
 ['030.jpeg', 'Andheri', 'O'],
 ['030.jpeg', '"Chakala,"', 'O'],
 ['030.jpeg', 'Mumbai', 'O'],
 ['030.jpeg', 'Reebok', 'B-ORG'],
 ['030.jpeg', 'India', 'I-ORG'],

In [64]:
df = pd.DataFrame(data[1:], columns=data[0])

#### To remove unwanted character and white spaces

### Cleaning text
- Remove white spaces
- Remove Unwanted Special Characters

In [45]:
from string import whitespace
from string import punctuation

In [46]:
white_space = whitespace
white_space

' \t\n\r\x0b\x0c'

In [47]:
punctations = punctuation
punctations

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

### Deleting Characters:
#### How str.maketrans() Works:
str.maketrans() creates a dictionary-like mapping of characters or strings, which can then be passed to translate() to perform the actual substitution.

In [52]:
# Delete characters 'a', 'b', 'c'
trans = str.maketrans('', '', 'abc')

text = "abcxyz"
result = text.translate(trans)
print(result)  # Output: xyz

text = "acxybz"
result = text.translate(trans)
print(result)  # Output: xyz

text = "axyz"
result = text.translate(trans)
print(result)  # Output: xyz

xyz
xyz
xyz

In [53]:
# Mapping 'a' to '1', 'b' to '2', and 'c' to '3'
trans = str.maketrans('abc', '123')

text = "abcabc"
result = text.translate(trans)
print(result)  # Output: 123123

text = "abcxyz"
result = text.translate(trans)
print(result)  # Output: 123123

text = "qwe a"
result = text.translate(trans)
print(result)  # Output: 123123

123123
123xyz
qwe 1

In [54]:
white_space = whitespace
punch = '!"#$%&\'()*+,:;<=>?[\\]^_`{|}~'

table_white_space = str.maketrans('','', white_space)
table_puncuation = str.maketrans('','',punch)

In [66]:
def clean_text(txt):
    text = str(txt)
    text = text.lower()

    remove_whitespace = text.translate(table_white_space)
    remove_punctation = remove_whitespace.translate(table_puncuation)

    return str(remove_punctation)

In [67]:
df.head()

         id      text      tag
0  000.jpeg                  O
1  000.jpeg         .        O
2  000.jpeg  040-4852  B-PHONE
3  000.jpeg   "8881,"  I-PHONE
4  000.jpeg     90309  B-PHONE

In [68]:
df['text'] = df['text'].apply(clean_text)

In [70]:
df.head()

         id      text      tag
0  000.jpeg                  O
1  000.jpeg         .        O
2  000.jpeg  040-4852  B-PHONE
3  000.jpeg      8881  I-PHONE
4  000.jpeg     90309  B-PHONE

In [71]:
data_clean = df.query("text != '' ")
data_clean

             id          text      tag
1      000.jpeg             .        O
2      000.jpeg      040-4852  B-PHONE
3      000.jpeg          8881  I-PHONE
4      000.jpeg         90309  B-PHONE
5      000.jpeg         52549  I-PHONE
...         ...           ...      ...
10439  290.jpeg  srmrrisurres    B-ORG
10441  290.jpeg       richard   B-NAME
10442  290.jpeg     pretorius   I-NAME
10444  290.jpeg      director    B-DES
10445                    none     None

[8272 rows x 3 columns]

#### To remove the null values

In [119]:
data_clean = data_clean.dropna()

#### Convert Data into Spacy Format

#### Data group by ids

In [123]:
group = data_clean.groupby(by='id')
group

In [124]:
group.groups.keys()

dict_keys(['000.jpeg', '001.jpeg', '002.jpeg', '003.jpeg', '004.jpeg', '007.jpeg', '008.jpeg', '009.jpeg', '010.jpeg', '011.jpeg', '012.jpeg', '013.jpeg', '014.jpeg', '015.jpeg', '016.jpeg', '017.jpeg', '018.jpeg', '020.jpeg', '021.jpeg', '022.jpeg', '023.jpeg', '024.jpeg', '025.jpeg', '027.jpeg', '028.jpeg', '030.jpeg', '031.jpeg', '032.jpeg', '033.jpeg', '034.jpeg', '035.jpeg', '036.jpeg', '037.jpeg', '038.jpeg', '039.jpeg', '040.jpeg', '041.jpeg', '042.jpeg', '043.jpeg', '044.jpeg', '045.jpeg', '047.jpeg', '048.jpeg', '049.jpeg', '050.jpeg', '051.jpeg', '052.jpeg', '053.jpeg', '054.jpeg', '055.jpeg', '056.jpeg', '057.jpeg', '058.jpeg', '059.jpeg', '060.jpeg', '061.jpeg', '062.jpeg', '063.jpeg', '064.jpeg', '065.jpeg', '066.jpeg', '067.jpeg', '068.jpeg', '069.jpeg', '070.jpeg', '071.jpeg', '072.jpeg', '073.jpeg', '074.jpeg', '075.jpeg', '076.jpeg', '078.jpeg', '079.jpeg', '080.jpeg', '081.jpeg', '082.jpeg', '083.jpeg', '084.jpeg', '085.jpeg', '086.jpeg', '087.jpeg', '088.jpeg', '089.jpeg', '090.jpeg', '091.jpeg', '092.jpeg', '094.jpeg', '095.jpeg', '096.jpeg', '097.jpeg', '098.jpeg', '099.jpeg', '101.jpeg', '102.jpeg', '104.jpeg', '106.jpeg', '107.jpeg', '108.jpeg', '109.jpeg', '110.jpeg', '111.jpeg', '112.jpeg', '113.jpeg', '114.jpeg', '115.jpeg', '117.jpeg', '118.jpeg', '119.jpeg', '120.jpeg', '121.jpeg', '122.jpeg', '123.jpeg', '124.jpeg', '125.jpeg', '126.jpeg', '127.jpeg', '129.jpeg', '130.jpeg', '131.jpeg', '132.jpeg', '133.jpeg', '134.jpeg', '135.jpeg', '136.jpeg', '137.jpeg', '138.jpeg', '139.jpeg', '140.jpeg', '141.jpeg', '142.jpeg', '143.jpeg', '144.jpeg', '145.jpeg', '146.jpeg', '147.jpeg', '148.jpeg', '149.jpeg', '150.jpeg', '151.jpeg', '152.jpeg', '153.jpeg', '154.jpeg', '155.jpeg', '156.jpeg', '157.jpeg', '158.jpeg', '159.jpeg', '160.jpeg', '161.jpeg', '162.jpeg', '163.jpeg', '164.jpeg', '165.jpeg', '166.jpeg', '167.jpeg', '168.jpeg', '169.jpeg', '170.jpeg', '171.jpeg', '172.jpeg', '173.jpeg', '174.jpeg', '175.jpeg', '176.jpeg', '177.jpeg', '178.jpeg', '179.jpeg', '180.jpeg', '181.jpeg', '182.jpeg', '183.jpeg', '185.jpeg', '186.jpeg', '187.jpeg', '188.jpeg', '189.jpeg', '190.jpeg', '191.jpeg', '193.jpeg', '194.jpeg', '195.jpeg', '196.jpeg', '197.jpeg', '198.jpeg', '199.jpeg', '200.jpeg', '201.jpeg', '202.jpeg', '203.jpeg', '204.jpeg', '205.jpeg', '206.jpeg', '207.jpeg', '208.jpeg', '209.jpeg', '210.jpeg', '211.jpeg', '212.jpeg', '213.jpeg', '214.jpeg', '215.jpeg', '216.jpeg', '217.jpeg', '218.jpeg', '219.jpeg', '220.jpeg', '221.jpeg', '222.jpeg', '223.jpeg', '224.jpeg', '225.jpeg', '226.jpeg', '227.jpeg', '229.jpeg', '231.jpeg', '232.jpeg', '233.jpeg', '234.jpeg', '235.jpeg', '236.jpeg', '237.jpeg', '238.jpeg', '239.jpeg', '240.jpeg', '241.jpeg', '242.jpeg', '243.jpeg', '244.jpeg', '245.jpeg', '246.jpeg', '247.jpeg', '248.jpeg', '249.jpeg', '250.jpeg', '251.jpeg', '252.jpeg', '253.jpeg', '254.jpeg', '255.jpeg', '256.jpeg', '257.jpeg', '258.jpeg', '259.jpeg', '260.jpeg', '261.jpeg', '262.jpeg', '263.jpeg', '264.jpeg', '265.jpeg', '266.jpeg', '268.jpeg', '269.jpeg', '270.jpeg', '271.jpeg', '273.jpeg', '274.jpeg', '275.jpeg', '276.jpeg', '277.jpeg', '278.jpeg', '280.jpeg', '282.jpeg', '284.jpeg', '286.jpeg', '287.jpeg', '288.jpeg', '290.jpeg'])

#### To get the one visting cards information

In [125]:
group.get_group('000.jpeg')

          id                       text      tag
1   000.jpeg                          .        O
2   000.jpeg                   040-4852  B-PHONE
3   000.jpeg                       8881  I-PHONE
4   000.jpeg                      90309  B-PHONE
5   000.jpeg                      52549  I-PHONE
6   000.jpeg                         fi        O
7   000.jpeg  /laurelsoverseaseducation        O
8   000.jpeg                          @        O
9   000.jpeg                    laurels    B-ORG
10  000.jpeg                   overseas    I-ORG
11  000.jpeg                educational    I-ORG
12  000.jpeg                consultancy    I-ORG
13  000.jpeg                       pvt.    I-ORG
14  000.jpeg                       ltd.    I-ORG
15  000.jpeg                        sea        O
17  000.jpeg                        u.k        O
18  000.jpeg                  australia        O
19  000.jpeg                     canada        O
20  000.jpeg                    ireland        O
27  000.jpeg   www.laurelseducation.com    B-WEB
28  000.jpeg  info@laurelseducation.com  B-EMAIL

In [126]:
groups_arr = group.get_group('000.jpeg')[['text', 'tag']].values
groups_arr

array([['.', 'O'],
       ['040-4852', 'B-PHONE'],
       ['8881', 'I-PHONE'],
       ['90309', 'B-PHONE'],
       ['52549', 'I-PHONE'],
       ['fi', 'O'],
       ['/laurelsoverseaseducation', 'O'],
       ['@', 'O'],
       ['laurels', 'B-ORG'],
       ['overseas', 'I-ORG'],
       ['educational', 'I-ORG'],
       ['consultancy', 'I-ORG'],
       ['pvt.', 'I-ORG'],
       ['ltd.', 'I-ORG'],
       ['sea', 'O'],
       ['u.k', 'O'],
       ['australia', 'O'],
       ['canada', 'O'],
       ['ireland', 'O'],
       ['www.laurelseducation.com', 'B-WEB'],
       ['info@laurelseducation.com', 'B-EMAIL']], dtype=object)

In [127]:
content = '' # all inforamtion in entire text
annotation = {'entities' : []} # all information of labels
start = 0
end = 0 

for text, label in  groups_arr:
    # print(text, label)
    text = str(text)
    str_len = len(text) + 1

    start = end
    end = start + str_len
    # print(start,end)

    if label != 'O':
        annot = (start, end - 1, label)
        annotation['entities'].append(annot)
    
    content = content + text + ' '

In [128]:
content

'. 040-4852 8881 90309 52549 fi /laurelsoverseaseducation @ laurels overseas educational consultancy pvt. ltd. sea u.k australia canada ireland www.laurelseducation.com info@laurelseducation.com '

In [129]:
annotation

{'entities': [(2, 10, 'B-PHONE'),
  (11, 15, 'I-PHONE'),
  (16, 21, 'B-PHONE'),
  (22, 27, 'I-PHONE'),
  (59, 66, 'B-ORG'),
  (67, 75, 'I-ORG'),
  (76, 87, 'I-ORG'),
  (88, 99, 'I-ORG'),
  (100, 104, 'I-ORG'),
  (105, 109, 'I-ORG'),
  (143, 167, 'B-WEB'),
  (168, 193, 'B-EMAIL')]}

In [130]:
content.find("ltd")

105

In [131]:
content.find('info@laurelseducation.com')

168

In [132]:
content.find('info@laurelseducation.com') + len('info@laurelseducation.com')

193

#### for all image data

In [134]:
group = data_clean.groupby(by='id')
cards = group.groups.keys()
cards

dict_keys(['000.jpeg', '001.jpeg', '002.jpeg', '003.jpeg', '004.jpeg', '007.jpeg', '008.jpeg', '009.jpeg', '010.jpeg', '011.jpeg', '012.jpeg', '013.jpeg', '014.jpeg', '015.jpeg', '016.jpeg', '017.jpeg', '018.jpeg', '020.jpeg', '021.jpeg', '022.jpeg', '023.jpeg', '024.jpeg', '025.jpeg', '027.jpeg', '028.jpeg', '030.jpeg', '031.jpeg', '032.jpeg', '033.jpeg', '034.jpeg', '035.jpeg', '036.jpeg', '037.jpeg', '038.jpeg', '039.jpeg', '040.jpeg', '041.jpeg', '042.jpeg', '043.jpeg', '044.jpeg', '045.jpeg', '047.jpeg', '048.jpeg', '049.jpeg', '050.jpeg', '051.jpeg', '052.jpeg', '053.jpeg', '054.jpeg', '055.jpeg', '056.jpeg', '057.jpeg', '058.jpeg', '059.jpeg', '060.jpeg', '061.jpeg', '062.jpeg', '063.jpeg', '064.jpeg', '065.jpeg', '066.jpeg', '067.jpeg', '068.jpeg', '069.jpeg', '070.jpeg', '071.jpeg', '072.jpeg', '073.jpeg', '074.jpeg', '075.jpeg', '076.jpeg', '078.jpeg', '079.jpeg', '080.jpeg', '081.jpeg', '082.jpeg', '083.jpeg', '084.jpeg', '085.jpeg', '086.jpeg', '087.jpeg', '088.jpeg', '089.jpeg', '090.jpeg', '091.jpeg', '092.jpeg', '094.jpeg', '095.jpeg', '096.jpeg', '097.jpeg', '098.jpeg', '099.jpeg', '101.jpeg', '102.jpeg', '104.jpeg', '106.jpeg', '107.jpeg', '108.jpeg', '109.jpeg', '110.jpeg', '111.jpeg', '112.jpeg', '113.jpeg', '114.jpeg', '115.jpeg', '117.jpeg', '118.jpeg', '119.jpeg', '120.jpeg', '121.jpeg', '122.jpeg', '123.jpeg', '124.jpeg', '125.jpeg', '126.jpeg', '127.jpeg', '129.jpeg', '130.jpeg', '131.jpeg', '132.jpeg', '133.jpeg', '134.jpeg', '135.jpeg', '136.jpeg', '137.jpeg', '138.jpeg', '139.jpeg', '140.jpeg', '141.jpeg', '142.jpeg', '143.jpeg', '144.jpeg', '145.jpeg', '146.jpeg', '147.jpeg', '148.jpeg', '149.jpeg', '150.jpeg', '151.jpeg', '152.jpeg', '153.jpeg', '154.jpeg', '155.jpeg', '156.jpeg', '157.jpeg', '158.jpeg', '159.jpeg', '160.jpeg', '161.jpeg', '162.jpeg', '163.jpeg', '164.jpeg', '165.jpeg', '166.jpeg', '167.jpeg', '168.jpeg', '169.jpeg', '170.jpeg', '171.jpeg', '172.jpeg', '173.jpeg', '174.jpeg', '175.jpeg', '176.jpeg', '177.jpeg', '178.jpeg', '179.jpeg', '180.jpeg', '181.jpeg', '182.jpeg', '183.jpeg', '185.jpeg', '186.jpeg', '187.jpeg', '188.jpeg', '189.jpeg', '190.jpeg', '191.jpeg', '193.jpeg', '194.jpeg', '195.jpeg', '196.jpeg', '197.jpeg', '198.jpeg', '199.jpeg', '200.jpeg', '201.jpeg', '202.jpeg', '203.jpeg', '204.jpeg', '205.jpeg', '206.jpeg', '207.jpeg', '208.jpeg', '209.jpeg', '210.jpeg', '211.jpeg', '212.jpeg', '213.jpeg', '214.jpeg', '215.jpeg', '216.jpeg', '217.jpeg', '218.jpeg', '219.jpeg', '220.jpeg', '221.jpeg', '222.jpeg', '223.jpeg', '224.jpeg', '225.jpeg', '226.jpeg', '227.jpeg', '229.jpeg', '231.jpeg', '232.jpeg', '233.jpeg', '234.jpeg', '235.jpeg', '236.jpeg', '237.jpeg', '238.jpeg', '239.jpeg', '240.jpeg', '241.jpeg', '242.jpeg', '243.jpeg', '244.jpeg', '245.jpeg', '246.jpeg', '247.jpeg', '248.jpeg', '249.jpeg', '250.jpeg', '251.jpeg', '252.jpeg', '253.jpeg', '254.jpeg', '255.jpeg', '256.jpeg', '257.jpeg', '258.jpeg', '259.jpeg', '260.jpeg', '261.jpeg', '262.jpeg', '263.jpeg', '264.jpeg', '265.jpeg', '266.jpeg', '268.jpeg', '269.jpeg', '270.jpeg', '271.jpeg', '273.jpeg', '274.jpeg', '275.jpeg', '276.jpeg', '277.jpeg', '278.jpeg', '280.jpeg', '282.jpeg', '284.jpeg', '286.jpeg', '287.jpeg', '288.jpeg', '290.jpeg'])

In [135]:
all_cards_data = []

for card in cards:
    card_data = []
    content = '' # all inforamtion in entire text
    annotation = {'entities' : []} # all information of labels
    start = 0
    end = 0 
    
    groups_arr = group.get_group(card)[['text', 'tag']].values

    for text, label in  groups_arr:
        # print(text, label)
        text = str(text)
        str_len = len(text) + 1
    
        start = end
        end = start + str_len
        # print(start,end)
    
        if label != 'O':
            annot = (start, end - 1, label)
            annotation['entities'].append(annot)
        
        content = content + text + ' ' 
    
    card_data = (content, annotation)
    all_cards_data.append(card_data)

In [136]:
all_cards_data

[('. 040-4852 8881 90309 52549 fi /laurelsoverseaseducation @ laurels overseas educational consultancy pvt. ltd. sea u.k australia canada ireland www.laurelseducation.com info@laurelseducation.com ',
  {'entities': [(2, 10, 'B-PHONE'),
    (11, 15, 'I-PHONE'),
    (16, 21, 'B-PHONE'),
    (22, 27, 'I-PHONE'),
    (59, 66, 'B-ORG'),
    (67, 75, 'I-ORG'),
    (76, 87, 'I-ORG'),
    (88, 99, 'I-ORG'),
    (100, 104, 'I-ORG'),
    (105, 109, 'I-ORG'),
    (143, 167, 'B-WEB'),
    (168, 193, 'B-EMAIL')]}),
 ('john smith marketing manager web www.psdgraphics.com phone 123-456-7890 mail email@psdgraphics.com ',
  {'entities': [(0, 4, 'B-NAME'),
    (5, 10, 'I-NAME'),
    (11, 20, 'B-DES'),
    (21, 28, 'I-DES'),
    (33, 52, 'B-WEB'),
    (59, 71, 'B-PHONE'),
    (77, 98, 'B-EMAIL')]}),
 ('sau 0 98489 24441 dy 08672 224441 /enkateswapa wie ',
  {'entities': [(6, 11, 'B-PHONE'), (12, 17, 'I-PHONE'), (34, 46, 'B-ORG')]}),
 ('prasad @ 99631735359490400000 i flex design album design visiting cards dtp works telugu english ',
  {'entities': [(0, 6, 'B-NAME')]}),
 ('madison yacht sales paul madison yacht broker - northeast region fax 718-444-1206 ',
  {'entities': [(0, 7, 'B-ORG'),
    (8, 13, 'I-ORG'),
    (14, 19, 'I-ORG'),
    (20, 24, 'B-NAME'),
    (25, 32, 'I-NAME'),
    (33, 38, 'B-DES'),
    (39, 45, 'I-DES'),
    (69, 81, 'B-PHONE')]}),
 ('www phototomics.com photot thomas atkins photographer and digital artist tatkins@phototomics.com phototomics 3419 via lido 340 newport beach ca - california 92663 ',
  {'entities': [(0, 3, 'B-WEB'),
    (4, 19, 'I-WEB'),
    (20, 26, 'B-ORG'),
    (27, 33, 'B-NAME'),
    (34, 40, 'I-NAME'),
    (41, 53, 'B-DES'),
    (54, 57, 'I-DES'),
    (58, 65, 'I-DES'),
    (66, 72, 'I-DES'),
    (73, 96, 'B-EMAIL')]}),
 ('reddy 9866186785 opp ramakrishna theatremain road peddapalli dist karimnagar telangana - 505172 email srihithaads.pdpl@ gmail.com ',
  {'entities': [(6, 16, 'B-PHONE'),
    (102, 119, 'B-EMAIL'),
    (120, 129, 'I-EMAIL')]}),
 ('saja vik 990083000 g.s.m. booster 1 all types of mobile repair data transfer - game application led touch glass change all mobile led fitting mobile repair training loor city centre mall opp. mbai-central mumbai - 400 8 ӊbes.t. ',
  {'entities': [(0, 4, 'B-NAME'),
    (9, 18, 'B-PHONE'),
    (19, 25, 'B-ORG'),
    (26, 33, 'I-ORG')]}),
 ('dr. michael dean clarinet performing teaching and consulting 682.888.7639 clarinetmike.com clarinetmike.wordpress.com clarinetmiketexas@ yahoo.com ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 11, 'I-NAME'),
    (12, 16, 'I-NAME'),
    (37, 45, 'B-DES'),
    (46, 49, 'I-DES'),
    (50, 60, 'I-DES'),
    (61, 73, 'B-PHONE'),
    (74, 90, 'B-WEB'),
    (91, 117, 'B-WEB'),
    (118, 136, 'B-EMAIL'),
    (137, 146, 'I-EMAIL')]}),
 ('a cell 9885050228 krishna 3257779 9393937799 d.no. 27-33-19 satnam towers opp buckingham post office gudavallivari st. governorpeta vijayawada. at ',
  {'entities': [(7, 17, 'B-PHONE'),
    (18, 25, 'B-NAME'),
    (26, 33, 'B-PHONE'),
    (34, 44, 'B-PHONE')]}),
 ('cell 7396379143 ', {'entities': [(5, 15, 'B-PHONE')]}),
 ('mobile73963791 43 flex. print az designing printing cl el ',
  {'entities': [(0, 14, 'B-PHONE')]}),
 ('mob-8445790640 siyalg all kind charger earphones mobile photostate anygkindlof online works. ',
  {'entities': [(0, 14, 'B-PHONE')]}),
 ('4 shri ganeshay namah t m. 70147-98128 baja deals in all kinds of new mobile handset tempered glass finserv fancy covers accessories available here samsung oppo vivo jenovo @ iphone mobile gionee ',
  {'entities': [(27, 38, 'B-PHONE')]}),
 ('91 9087253526 91 9087252666 oe raghuvijayan104@gmail.com ',
  {'entities': [(0, 2, 'B-PHONE'),
    (3, 13, 'I-PHONE'),
    (14, 16, 'B-PHONE'),
    (17, 27, 'I-PHONE'),
    (31, 56, 'B-EMAIL')]}),
 ('y-wireless repair eee certified technician phone tablet - electronic repairs call us 330-270-5060 facebook.com/youngstownwirelessrepair ',
  {'entities': [(0, 10, 'B-ORG'), (11, 17, 'I-ORG'), (85, 97, 'B-PHONE')]}),
 ('cell phone repair center 6795 wilson blvd suite 26 buy - sell - trade falls church va 22044 tel 571 606 6636 / 571606 3445 - iphone ipad 02-03-2004 - htc repair eam - samsung repair - trackball repair htc - cracked screens - water damage - speakers - charger port - software update nokia - password reset ..and almost any hardware or software issue eden center - seven corner - route 50 ',
  {'entities': [(5, 10, 'B-ORG'),
    (11, 17, 'I-ORG'),
    (18, 24, 'I-ORG'),
    (96, 99, 'B-PHONE'),
    (100, 103, 'I-PHONE'),
    (104, 108, 'I-PHONE'),
    (111, 117, 'I-PHONE'),
    (118, 122, 'I-PHONE')]}),
 ('mobile repair centre on-site repairs while you wait instant unlocking solutions damaged lcd screens replaced wateriliquid damaged phones charging audio signal problems software problems replacement loan phones available while your phone is being repaired no-fix no-fee 20 87499933 www.mprc.co ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 13, 'I-ORG'),
    (14, 20, 'I-ORG'),
    (269, 271, 'B-PHONE'),
    (272, 280, 'I-PHONE'),
    (281, 292, 'B-WEB')]}),
 ('ezy fit senice brakes 91 portland rd hucknall timing belts ng15 7ds suspension opp sandicliffe ford diagnostics batteries free brake check email co.uk web www.ezyfitautocentre.co.uk ',
  {'entities': [(0, 3, 'B-ORG'), (4, 7, 'I-ORG'), (155, 181, 'B-WEB')]}),
 ('dale steffen club manager planet fitness home of the judgement free zone 9652 s. roberts rd. hickory hills il 60457 ayes p 708.598.1010 planetfitness.com ',
  {'entities': [(0, 4, 'B-NAME'),
    (5, 12, 'I-NAME'),
    (13, 17, 'B-DES'),
    (18, 25, 'I-DES'),
    (123, 135, 'B-PHONE'),
    (136, 153, 'B-WEB')]}),
 ('hilton oak lawn heather stevens catering manager 9333 south cicero avenue oak lawn il 60453 tel 708 425 7800 direct line 708 229 8859 fax 708 229 8858 email heather.stevens@hilton.com honors hilton official sponsor ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 10, 'I-ORG'),
    (11, 15, 'I-ORG'),
    (16, 23, 'B-NAME'),
    (24, 31, 'I-NAME'),
    (32, 40, 'B-DES'),
    (41, 48, 'I-DES'),
    (96, 99, 'B-PHONE'),
    (100, 103, 'I-PHONE'),
    (104, 108, 'I-PHONE'),
    (157, 183, 'B-EMAIL')]}),
 ('- mobile limited marian piontek -708 890-8911 7884 n milwaukee ave niles il 60714 mpiontek@neptunemobile.com ',
  {'entities': [(2, 8, 'B-ORG'),
    (9, 16, 'I-ORG'),
    (17, 23, 'B-NAME'),
    (24, 31, 'I-NAME'),
    (32, 36, 'B-PHONE'),
    (37, 45, 'I-PHONE'),
    (82, 108, 'B-EMAIL')]}),
 ('furniture victor harris jr sales associate tel 630.783.2346 fax 630.783.1175 ashley furniture homestore 875 e boughton road bolingbrook il 60440 www.ashleyfurniturehomestore.com ',
  {'entities': [(10, 16, 'B-NAME'),
    (17, 23, 'I-NAME'),
    (24, 26, 'I-NAME'),
    (27, 32, 'B-DES'),
    (33, 42, 'B-DES'),
    (47, 59, 'B-PHONE'),
    (77, 83, 'B-ORG'),
    (84, 93, 'I-ORG'),
    (94, 103, 'I-ORG'),
    (145, 177, 'B-EMAIL')]}),
 ('walt disney productions kee۪ john f. curry director 2 hotel division ams -213 245-8951 500 so. buena vista st. burbank california 91503 ',
  {'entities': [(0, 4, 'B-ORG'),
    (5, 11, 'I-ORG'),
    (29, 33, 'B-NAME'),
    (34, 36, 'I-NAME'),
    (37, 42, 'I-NAME'),
    (43, 51, 'B-DES'),
    (73, 77, 'B-PHONE'),
    (78, 86, 'I-PHONE')]}),
 ('kununurra rachell fewster shop 112b coolibah drive 418 894 400 kununurrra wa 6743 phone -8 9168 1737 fax -8 9169 3940 email info@subwaykununurra.com.au ',
  {'entities': [(10, 17, 'B-NAME'),
    (18, 25, 'I-NAME'),
    (88, 90, 'B-PHONE'),
    (91, 95, 'I-PHONE'),
    (96, 100, 'I-PHONE'),
    (124, 151, 'B-EMAIL')]}),
 ('h managing director mail customercare@sho 4reebok.com shreshth parekh to head indian operations reebok add 326 third floor chintamani plaza bewing andheri chakala mumbai reebok india ltd. ',
  {'entities': [(2, 10, 'B-DES'),
    (11, 19, 'I-DES'),
    (25, 41, 'B-EMAIL'),
    (42, 53, 'I-EMAIL'),
    (54, 62, 'B-NAME'),
    (63, 69, 'I-NAME'),
    (170, 176, 'B-ORG'),
    (177, 182, 'I-ORG'),
    (183, 187, 'I-ORG')]}),
 ('general manager dominos 54321 caesar blvd. gardena fresh ca 92337 mordan pisa store 562-543-7689 cell 562-456-3210 mpisa@dominos.com ',
  {'entities': [(0, 7, 'B-DES'),
    (8, 15, 'I-DES'),
    (16, 23, 'B-ORG'),
    (102, 114, 'B-PHONE'),
    (115, 132, 'B-EMAIL')]}),
 ('ae be 3 ', {'entities': []}),
 ('prakash khedkar sales officer m. 9227576803 a loan against property bhavya financial services hdfc bank associate mortgage loans 1009-1010 city centre market opp. a.v. sons ghod dod road parle point surat-395007 ph. 261 2210142 e mail - pykhedkar07@yahoo.com. ',
  {'entities': [(0, 7, 'B-NAME'),
    (8, 15, 'I-NAME'),
    (16, 21, 'B-DES'),
    (22, 29, 'I-DES'),
    (68, 74, 'B-ORG'),
    (75, 84, 'I-ORG'),
    (85, 93, 'I-ORG'),
    (216, 219, 'B-PHONE'),
    (220, 227, 'I-PHONE'),
    (237, 259, 'B-EMAIL')]}),
 ('j laptop computer printer sales j laptop computer service j data recovery networking / amc house repairs service j printer repairs @ toner refiling j all type of accessories / cctv. camera / web hosting domain register j instant web development / software development infotech do something big 9898 24 4020 9033 25 1418 perfectinfotech2013@gmail.com @ 124 gurukrupa complex talod-majara road beside mamlatdar kacheri talod. ',
  {'entities': [(294, 298, 'B-PHONE'),
    (299, 301, 'I-PHONE'),
    (302, 306, 'I-PHONE'),
    (307, 311, 'I-PHONE'),
    (312, 314, 'I-PHONE'),
    (315, 319, 'I-PHONE'),
    (320, 349, 'B-EMAIL')]}),
 ('craig forman di. service max llc 25 pine street - suite 8 facility maintenance janitorial and supplies rockaway nj 7866 office -973 627-9292 fax -973 210-9160 cell -973 876-8402 craig@servicemaxnj.com www.servicemaxnj.com ',
  {'entities': [(0, 5, 'B-NAME'),
    (6, 12, 'I-NAME'),
    (17, 24, 'B-ORG'),
    (25, 28, 'I-ORG'),
    (29, 32, 'I-ORG'),
    (164, 168, 'B-PHONE'),
    (169, 177, 'I-PHONE'),
    (178, 200, 'B-EMAIL'),
    (201, 221, 'B-WEB')]}),
 ('8 stanford stanford medicine cardiovascular institute joseph c. wu md phd director stanford cardiovascular institute professor medicine cardiology radiology 265 campus drive g-1120b tel -650 736-2246 stanford ca 94305 mc-5454 fax -650 736-0234 http//wulab.stanfordedu cvi -650 725-7964 e-mail joewu@stanford.edu het //evi.stanford.edu ',
  {'entities': [(11, 19, 'B-ORG'),
    (20, 28, 'I-ORG'),
    (29, 43, 'I-ORG'),
    (44, 53, 'I-ORG'),
    (54, 60, 'B-NAME'),
    (61, 63, 'I-NAME'),
    (64, 66, 'I-NAME'),
    (74, 82, 'B-DES'),
    (186, 190, 'B-PHONE'),
    (191, 199, 'I-PHONE'),
    (244, 267, 'B-WEB'),
    (293, 311, 'B-EMAIL')]}),
 ('8281604684 9061825334 9544851506 you dream it we make it sgraphics manathala isons arcade above fedaral bank perumanoorkulam jn. manarcad-kottayam tel 481 2373840 vibrantgraphicz@gmail.com she flex vinyl printing cloth printing flex boards light boards wedding cards visiting cards sticker cutting notice poster brochures graphic designing and all other advertisement works ',
  {'entities': [(0, 10, 'B-PHONE'),
    (11, 21, 'B-PHONE'),
    (22, 32, 'B-PHONE')]}),
 ('in association with lobo associates tel 91 481 2424398 / 7034641404 door no. xxii/32 parel church road kurisummodu 686104 changanacherry kottayam. www.aramex.com manuel joseph lobo aramexchry@gmail.com ',
  {'entities': [(40, 42, 'B-PHONE'),
    (43, 46, 'I-PHONE'),
    (47, 54, 'I-PHONE'),
    (57, 67, 'B-PHONE'),
    (147, 161, 'B-WEB'),
    (162, 168, 'B-NAME'),
    (169, 175, 'I-NAME'),
    (181, 201, 'B-EMAIL')]}),
 ('burger king canada inc. manager jatheepa sathananthan maa nicole white 1490 dixie rd b k mississaugaon lse 3.00e05 burger king 905-274-1607 burger@king.com www.burgerking.com ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 11, 'I-ORG'),
    (12, 18, 'I-ORG'),
    (19, 23, 'I-ORG'),
    (24, 31, 'B-DES'),
    (32, 40, 'B-NAME'),
    (41, 53, 'I-NAME'),
    (58, 64, 'B-NAME'),
    (65, 70, 'I-NAME'),
    (115, 121, 'B-ORG'),
    (122, 126, 'I-ORG'),
    (127, 139, 'B-PHONE'),
    (140, 155, 'B-EMAIL'),
    (156, 174, 'B-WEB')]}),
 ('alamo productions 434136 sierra hwy. canyon country ca 94359 -805 252-6157 te pree ',
  {'entities': [(0, 5, 'B-ORG'),
    (6, 17, 'I-ORG'),
    (61, 65, 'B-PHONE'),
    (66, 74, 'I-PHONE')]}),
 ('cell 8099948528 ce 8466045457 email lictsrikant@gmail.com life insurance corporation of india seosrika ntht@gmail .com thathineni srikanth insurance advisor agent code no. 0316164y life insurance corporation of india br. off. lic office trimulgherry sec۪bad - 500 16 add. borabanda hyderabad - 500 18 lictsrikant8099948528.blogspot.in interviewsinhyderabad.blogspot.in facebook.com/lictsrikant8099948528 facebook.com/thathineni.srikanth.9 promote your business online pybo ',
  {'entities': [(5, 15, 'B-PHONE'),
    (19, 29, 'B-PHONE'),
    (36, 57, 'B-EMAIL'),
    (58, 62, 'B-ORG'),
    (63, 72, 'I-ORG'),
    (73, 84, 'I-ORG'),
    (85, 87, 'I-ORG'),
    (88, 93, 'I-ORG'),
    (94, 102, 'B-EMAIL'),
    (103, 113, 'I-EMAIL'),
    (114, 118, 'I-EMAIL'),
    (119, 129, 'B-NAME'),
    (130, 138, 'I-NAME'),
    (139, 148, 'B-DES'),
    (149, 156, 'I-DES'),
    (181, 185, 'B-ORG'),
    (186, 195, 'I-ORG'),
    (196, 207, 'I-ORG'),
    (208, 210, 'I-ORG'),
    (211, 216, 'I-ORG'),
    (301, 334, 'B-WEB'),
    (335, 368, 'B-WEB')]}),
 ('john best test engineer philips healthcare tel 1 -717 667-5109 fax 1 -717 667-5169 john.best@philips.com philips echo drive reedsville pa 17084-8603 usa www.philips.com ',
  {'entities': [(0, 4, 'B-NAME'),
    (5, 9, 'I-NAME'),
    (10, 14, 'B-DES'),
    (15, 23, 'I-DES'),
    (24, 31, 'B-ORG'),
    (32, 42, 'I-ORG'),
    (47, 48, 'B-PHONE'),
    (49, 53, 'I-PHONE'),
    (54, 62, 'I-PHONE'),
    (83, 104, 'B-EMAIL'),
    (153, 168, 'B-WEB')]}),
 ('john w. best senior electronics design engineer 2124 old gatesburg road phone -814 867-8600 ext. 255 state college pa 16803 fax -814 867-4513 jbest@spectrumedix.com ',
  {'entities': [(0, 4, 'B-NAME'),
    (5, 7, 'I-NAME'),
    (8, 12, 'I-NAME'),
    (13, 19, 'B-DES'),
    (20, 31, 'B-DES'),
    (32, 38, 'B-DES'),
    (39, 47, 'B-DES'),
    (78, 82, 'B-PHONE'),
    (83, 91, 'I-PHONE'),
    (142, 164, 'B-EMAIL')]}),
 ('joseph smith speech and hearing science phd 2009 university of illinois at urbana-champaign student college of applied health science department of health science 602 east green street 217.333.1000 urbana il 61801 josephsmith@illinois.edu ',
  {'entities': [(0, 6, 'B-NAME'),
    (7, 12, 'I-NAME'),
    (13, 19, 'B-DES'),
    (20, 23, 'I-DES'),
    (24, 31, 'I-DES'),
    (32, 39, 'I-DES'),
    (40, 43, 'I-DES'),
    (49, 59, 'B-ORG'),
    (60, 62, 'I-ORG'),
    (63, 71, 'I-ORG'),
    (72, 74, 'I-ORG'),
    (75, 91, 'I-ORG'),
    (185, 197, 'B-PHONE'),
    (214, 238, 'B-EMAIL')]}),
 ('northeastern state university rowdy riverhawk bachelor of business administration accounting phone 918-444-3110 may 2017 careerservices@nsuok.edu 705 north grand avenue tahlequah ok 74464 ',
  {'entities': [(0, 12, 'B-ORG'),
    (13, 18, 'I-ORG'),
    (19, 29, 'I-ORG'),
    (30, 35, 'B-NAME'),
    (36, 45, 'I-NAME'),
    (82, 92, 'B-DES'),
    (99, 111, 'B-PHONE'),
    (121, 145, 'B-EMAIL')]}),
 ('eddie yaklin 22 wasan 888-639-1170 702-421-0081 direct 702-421-0081 cel 702-421-0081 24000 ai ter las vegas nv 89123 www.alibizcards.com davidv@allbizcards.com fleet i ',
  {'entities': [(0, 5, 'B-NAME'),
    (6, 12, 'I-NAME'),
    (22, 34, 'B-PHONE'),
    (35, 47, 'B-PHONE'),
    (55, 67, 'B-PHONE'),
    (72, 84, 'B-PHONE'),
    (117, 136, 'B-WEB'),
    (137, 159, 'B-EMAIL')]}),
 ('the george washington university washington dc erik a. rodriguez assistant professor of chemistry department of chemistry 800 22nd street nw science and engineering hall suite 4000 washington dc 20052 202-994-0305 telephone 202-994-5873 fax erikrodriguez@gwu.edu 30 pow ',
  {'entities': [(0, 3, 'B-ORG'),
    (4, 10, 'I-ORG'),
    (11, 21, 'I-ORG'),
    (22, 32, 'I-ORG'),
    (47, 51, 'B-NAME'),
    (52, 54, 'I-NAME'),
    (55, 64, 'I-NAME'),
    (65, 74, 'B-DES'),
    (75, 84, 'I-DES'),
    (85, 87, 'I-DES'),
    (88, 97, 'I-DES'),
    (201, 213, 'B-PHONE'),
    (241, 262, 'B-EMAIL')]}),
 ('j elon university john doe 2000 campus box elon nc 27244 university title office 123.456.7890 mobile 123.456.7890 school office or department fax 123.456.7890 name@elon.edu wwwelon.edu/site gi facebook g twitter ',
  {'entities': [(2, 6, 'B-ORG'),
    (7, 17, 'I-ORG'),
    (18, 22, 'B-NAME'),
    (23, 26, 'I-NAME'),
    (81, 93, 'B-PHONE'),
    (101, 113, 'B-PHONE'),
    (159, 172, 'B-EMAIL'),
    (173, 189, 'B-WEB')]}),
 ('cp toyota your toyota sales james bond 4718 san fernando rd. sales leasing consultant glendale ca 91204 bus. -818 547-4220 service -818 901-2345 fax. -818 547-4680 parts -818 678-9012 info@firstprintingca.com www.firstprintingca.com ',
  {'entities': [(3, 9, 'B-ORG'),
    (28, 33, 'B-NAME'),
    (34, 38, 'I-NAME'),
    (61, 66, 'B-DES'),
    (67, 74, 'I-DES'),
    (75, 85, 'I-DES'),
    (109, 113, 'B-PHOE'),
    (114, 122, 'I-PHONE'),
    (184, 208, 'B-EMAIL'),
    (209, 232, 'B-WEB')]}),
 ('james bond salesperson genesis brand genesis your town hyundai 4718 san fernando road f glendale ca 91204 t -818 547-4220 f -818 547-4680 www.firstprintingca.com ',
  {'entities': [(0, 5, 'B-NAME'),
    (6, 10, 'I-NAME'),
    (11, 22, 'B-DES'),
    (37, 44, 'B-ORG'),
    (108, 112, 'B-PHONE'),
    (113, 121, 'I-PHONE'),
    (138, 161, 'B-WEB')]}),
 ('honda donnie hansen motocross team rider team honda american honda motor co. inc. 100 west alondra boulevard e gardena ca 90247 -213 321-8680 ',
  {'entities': [(0, 5, 'B-ORG'),
    (6, 12, 'B-NAME'),
    (13, 19, 'I-NAME'),
    (20, 29, 'B-DES'),
    (30, 34, 'I-DES'),
    (35, 40, 'I-DES'),
    (52, 60, 'B-ORG'),
    (61, 66, 'I-ORG'),
    (67, 72, 'I-ORG'),
    (73, 76, 'I-ORG'),
    (77, 81, 'I-ORG'),
    (128, 132, 'B-PHONE'),
    (133, 141, 'I-PHONE')]}),
 ('james bond your city honda sales leasing consultant 4718 san fernando rd. glendale ca 91204 bus. -818 547-4220 fax -818 547-4680 info@firstprintingca.com www.firstprintingca.com ',
  {'entities': [(0, 5, 'B-NAME'),
    (6, 10, 'I-NAME'),
    (11, 15, 'B-ORG'),
    (16, 20, 'I-ORG'),
    (21, 26, 'I-ORG'),
    (27, 32, 'B-DES'),
    (33, 40, 'I-DES'),
    (41, 51, 'I-DES'),
    (97, 101, 'B-PHONE'),
    (102, 110, 'I-PHONE'),
    (129, 153, 'B-EMAIL'),
    (154, 177, 'B-WEB')]}),
 ('established 1922 william j. cunningham john j. delaney ing. 1590 blue hill avenue mattapan mass. blu 3800 ',
  {'entities': [(17, 24, 'B-NAME'),
    (25, 27, 'I-NAME'),
    (28, 38, 'I-NAME'),
    (39, 43, 'B-ORG'),
    (44, 46, 'I-ORG'),
    (47, 54, 'I-ORG'),
    (55, 59, 'I-ORG')]}),
 ('jack bolel senior sales executive 7470 sound avenue mattituck ny 11952 re power office 631.240.0999 universe mobile 631.533.9399 fax 631.466.5200 jbolel@solaruniverse.com 52689-me www.solaruniverse/eastendli.com ',
  {'entities': [(0, 4, 'B-NAME'),
    (5, 10, 'I-NAME'),
    (11, 17, 'B-DES'),
    (18, 23, 'I-DES'),
    (24, 33, 'I-DES'),
    (71, 73, 'B-ORG'),
    (74, 79, 'I-ORG'),
    (87, 99, 'B-PHONE'),
    (116, 128, 'B-PHONE'),
    (146, 170, 'B-EMAIL'),
    (180, 211, 'B-WEB')]}),
 ('reagan hayes luke j. hayes 1862 s. bentley avenue suite 101 los angeles ca 90025 p 888.380.8642 f 310.494.5937 luke@reaganhayes.com www.reaganhayes.com ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 12, 'I-ORG'),
    (13, 17, 'B-NAME'),
    (18, 20, 'I-NAME'),
    (21, 26, 'I-NAME'),
    (83, 95, 'B-PHONE'),
    (111, 131, 'B-EMAIL'),
    (132, 151, 'B-WEB')]}),
 ('jeffery barnes leasing professional cell 818-283-2837 office 818-283-5987 fax 818-283-2339 www.allbizcards.com 3948 auto center dr. davidv@allbizcards.com los angeles ca 90025 ',
  {'entities': [(0, 7, 'B-NAME'),
    (8, 14, 'I-NAME'),
    (15, 22, 'B-DES'),
    (23, 35, 'I-DES'),
    (41, 53, 'B-PHONE'),
    (61, 73, 'B-PHONE'),
    (91, 110, 'B-WEB')]}),

#### Split data into traing and testing set

In [137]:
import random

In [138]:
random.shuffle(all_cards_data)

In [139]:
all_cards_data

[('john smith marketing manager web www.psdgraphics.com phone 123-456-7890 mail email@psdgraphics.com ',
  {'entities': [(0, 4, 'B-NAME'),
    (5, 10, 'I-NAME'),
    (11, 20, 'B-DES'),
    (21, 28, 'I-DES'),
    (33, 52, 'B-WEB'),
    (59, 71, 'B-PHONE'),
    (77, 98, 'B-EMAIL')]}),
 ('satyendra gupta cell 9846536345 panjagutta hyderabad a.p. ph91-40-2307 3692 emailforcehyd@gmail.com www.cfcabcd.com ',
  {'entities': [(0, 9, 'B-NAME'),
    (21, 31, 'B-PHONE'),
    (58, 70, 'B-PHONE'),
    (71, 75, 'I-PHONE'),
    (76, 99, 'B-EMAIL'),
    (100, 115, 'B-WEB')]}),
 ('xs cancel e save sor۪ aaron s assistant designer design group mobile comm. t -9053 samsung f 82-01-2345-6789 electronics m -9053 ',
  {'entities': [(22, 27, 'B-ORG'),
    (28, 29, 'I-ORG'),
    (30, 39, 'B-NAME'),
    (40, 48, 'I-NAME'),
    (83, 90, 'B-ORG'),
    (123, 128, 'B-PHONE')]}),
 ('d.a.umak scientist m.p. council of science technology remote sensing applications centre 26 kisan bhavan jail road arera hills bhopal - 462004 tel 553224 763497 555948 554578 fax. 755 - 554712 553929 e-mail mpcost @ mp.nic.in. res a-122 bda colony. shahpura bhopal - 462 16 f723970cr ',
  {'entities': [(0, 8, 'B-NAME'),
    (9, 18, 'B-DES'),
    (19, 23, 'B-ORG'),
    (24, 31, 'I-ORG'),
    (32, 34, 'I-ORG'),
    (35, 42, 'I-ORG'),
    (43, 53, 'I-ORG'),
    (147, 153, 'B-PHONE'),
    (154, 160, 'I-PHONE'),
    (161, 167, 'I-PHONE'),
    (168, 174, 'I-PHONE'),
    (207, 213, 'B-EMAIL'),
    (214, 215, 'I-EMAIL'),
    (216, 226, 'I-EMAIL')]}),
 ('. 040-4852 8881 90309 52549 fi /laurelsoverseaseducation @ laurels overseas educational consultancy pvt. ltd. sea u.k australia canada ireland www.laurelseducation.com info@laurelseducation.com ',
  {'entities': [(2, 10, 'B-PHONE'),
    (11, 15, 'I-PHONE'),
    (16, 21, 'B-PHONE'),
    (22, 27, 'I-PHONE'),
    (59, 66, 'B-ORG'),
    (67, 75, 'I-ORG'),
    (76, 87, 'I-ORG'),
    (88, 99, 'I-ORG'),
    (100, 104, 'I-ORG'),
    (105, 109, 'I-ORG'),
    (143, 167, 'B-WEB'),
    (168, 193, 'B-EMAIL')]}),
 ('www phototomics.com photot thomas atkins photographer and digital artist tatkins@phototomics.com phototomics 3419 via lido 340 newport beach ca - california 92663 ',
  {'entities': [(0, 3, 'B-WEB'),
    (4, 19, 'I-WEB'),
    (20, 26, 'B-ORG'),
    (27, 33, 'B-NAME'),
    (34, 40, 'I-NAME'),
    (41, 53, 'B-DES'),
    (54, 57, 'I-DES'),
    (58, 65, 'I-DES'),
    (66, 72, 'I-DES'),
    (73, 96, 'B-EMAIL')]}),
 ('heinrich heinrich corporation india pvt. ltd. amit choudhary 0-284 beta-4 head services greater noida - 201308 91.9717 228 880 u.p. india e sindia@heinrichtimited.com wavww.heintichlimited.com ',
  {'entities': [(9, 17, 'B-ORG'),
    (18, 29, 'I-ORG'),
    (30, 35, 'I-ORG'),
    (36, 40, 'I-ORG'),
    (41, 45, 'I-ORG'),
    (46, 50, 'B-NAME'),
    (51, 60, 'I-NAME'),
    (74, 78, 'B-DES'),
    (79, 87, 'I-DES'),
    (111, 118, 'B-PHONE'),
    (119, 122, 'I-PHONE'),
    (140, 166, 'B-EMAIL'),
    (167, 192, 'B-WEB')]}),
 ('esri india sunil kumar pk. business manager niit gis ltd. 3rd floor. prashanti complex basheerbagh hyderabad - 500 63 india e tel 55633616 23240434 23243336 fax 9140 23231567 23298867 e-mail sunilkkpk@niit.com website wwwesriindia.com ',
  {'entities': [(0, 4, 'B-ORG'),
    (5, 10, 'I-ORG'),
    (11, 16, 'B-NAME'),
    (17, 22, 'I-NAME'),
    (23, 26, 'I-NAME'),
    (27, 35, 'B-DES'),
    (36, 43, 'I-DES'),
    (44, 48, 'B-ORG'),
    (49, 52, 'I-ORG'),
    (53, 57, 'I-ORG'),
    (130, 138, 'B-PHONE'),
    (139, 147, 'I-PHONE'),
    (148, 156, 'I-PHONE'),
    (191, 209, 'B-EMAIL'),
    (218, 234, 'B-WEB')]}),
 ('ambuja cement micro materials yatin joshi head - alccofine ambuja cements limited elegant business park behind kotak mahindra bank midc cross road b۪ off andheri - kurla road andheri east mumbai - 400 59 tel. -22 4066 7501 / 6616 7501 mobile 91 9920085526 email yatin.joshi@ambujacement.com website .www.alccofine.com e www.ambujacement.com e www.lafargeholcim.com ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 13, 'I-ORG'),
    (30, 35, 'B-NAME'),
    (36, 41, 'I-NAME'),
    (42, 46, 'B-DES'),
    (47, 48, 'I-DES'),
    (49, 58, 'I-DES'),
    (59, 65, 'B-ORG'),
    (66, 73, 'I-ORG'),
    (74, 81, 'I-ORG'),
    (209, 212, 'B-PHONE'),
    (213, 217, 'I-PHONE'),
    (218, 222, 'I-PHONE'),
    (225, 229, 'B-PHONE'),
    (230, 234, 'I-PHONE'),
    (242, 244, 'B-PHONE'),
    (245, 255, 'I-PHONE'),
    (262, 290, 'B-EMAIL'),
    (299, 317, 'B-WEB'),
    (320, 340, 'B-WEB'),
    (343, 364, 'B-WEB')]}),
 ('valued products uc al r card board art visiting cards synthetic visiting cards letter pads pamphlets multi color specialists magazines prospectus labels packing boxes 91 92165 25794 non woven fabric carry bags 91 98728 25794 e-mail bbsp1995@yahoo.com www.novelties-cards.webs.com http//bluebirdmetalcrafts.yolasite.com ',
  {'entities': [(167, 169, 'B-PHONE'),
    (170, 175, 'I-PHONE'),
    (176, 181, 'I-PHONE'),
    (210, 212, 'B-PHONE'),
    (232, 250, 'B-EMAIL'),
    (251, 279, 'B-WEB'),
    (280, 318, 'B-WEB')]}),
 ('dr. mohan s c ph.d assistant professor department of civil engineering x tel 91 40 66 30 36 72 fax 91 40 66 30 39 98 mob 91 8001 2 4453 email mohansc@hyderabad. bits-pilani.ac.in url bits pilani hyderabad/mohansc/profile hyderabad campus a birla institute of technology science pilani hyderabad campus jawahar nagar shameerpet mandal hyderabad 500 78 telangana siate india. ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 9, 'I-NAME'),
    (10, 11, 'I-NAME'),
    (12, 13, 'I-NAME'),
    (19, 28, 'B-DES'),
    (29, 38, 'I-DES'),
    (77, 79, 'B-PHONE'),
    (80, 82, 'I-PHONE'),
    (83, 85, 'I-PHONE'),
    (86, 88, 'I-PHONE'),
    (89, 91, 'I-PHONE'),
    (92, 94, 'I-PHONE'),
    (121, 123, 'B-PHONE'),
    (124, 128, 'I-PHONE'),
    (129, 130, 'I-PHONE'),
    (131, 135, 'I-PHONE'),
    (142, 160, 'B-EMAIL'),
    (161, 178, 'B-EMAIL'),
    (240, 245, 'B-ORG'),
    (246, 255, 'I-ORG'),
    (256, 258, 'I-ORG'),
    (259, 269, 'I-ORG'),
    (270, 277, 'I-ORG'),
    (278, 284, 'I-ORG')]}),
 ('o 7152182 7152171 ww r 3000324 y.v. siva kumar wa. development officer life jusurance corporation of india office city street no. 4 habsiguda hyderabad - 500 7 plotnq.254 telecom nagar gachi bowli hyderabad - 500 2 ',
  {'entities': [(2, 9, 'B-PHONE'),
    (10, 17, 'I-PHONE'),
    (31, 35, 'B-NAME'),
    (36, 40, 'I-NAME'),
    (41, 46, 'I-NAME'),
    (51, 62, 'B-DES'),
    (63, 70, 'I-DES'),
    (71, 75, 'B-ORG'),
    (76, 85, 'I-ORG'),
    (86, 97, 'I-ORG'),
    (98, 100, 'I-ORG'),
    (101, 106, 'I-ORG'),
    (107, 113, 'I-ORG')]}),
 ('l. krishna reddy mobile 9246538840 managing director b.e. civil ph. 27666972 wonder p ltd. yer ae 1-9-630/1 3rd floor vidyanagar hyderabad - 44 ',
  {'entities': [(0, 2, 'B-NAME'),
    (3, 10, 'I-NAME'),
    (11, 16, 'I-NAME'),
    (24, 34, 'B-PHONE'),
    (44, 52, 'B-DES'),
    (53, 57, 'I-DES'),
    (58, 63, 'I-DES'),
    (68, 76, 'B-PHONE'),
    (77, 83, 'B-ORG'),
    (84, 85, 'I-ORG'),
    (86, 90, 'I-ORG')]}),
 ('eddie yaklin 22 wasan 888-639-1170 702-421-0081 direct 702-421-0081 cel 702-421-0081 24000 ai ter las vegas nv 89123 www.alibizcards.com davidv@allbizcards.com fleet i ',
  {'entities': [(0, 5, 'B-NAME'),
    (6, 12, 'I-NAME'),
    (22, 34, 'B-PHONE'),
    (35, 47, 'B-PHONE'),
    (55, 67, 'B-PHONE'),
    (72, 84, 'B-PHONE'),
    (117, 136, 'B-WEB'),
    (137, 159, 'B-EMAIL')]}),
 ('imperial college of technology tahir qureshi srecor dae a 552810830 it oe 333 3030830 ast near road havelian designed by www.webcomforts.com ',
  {'entities': [(0, 8, 'B-ORG'),
    (9, 16, 'I-ORG'),
    (17, 19, 'I-ORG'),
    (20, 30, 'I-ORG'),
    (31, 36, 'B-NAME'),
    (37, 44, 'I-NAME'),
    (45, 51, 'I-NAME'),
    (58, 67, 'B-PHONE'),
    (74, 77, 'B-PHONE'),
    (78, 85, 'I-PHONE'),
    (121, 140, 'B-WEB')]}),
 ('online services pvt. ltd. redefining online subhash jain website and php software development director seo smo internet marketing brochure catalogue designing printing domain registration web hosting websites www.samyakonline.net www.samyakonline. biz www.outsourcegraphicdesigns.com www.samyakonline.co.in cell 9810083308 email nfo@samyakonine net ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 15, 'I-ORG'),
    (16, 20, 'I-ORG'),
    (21, 25, 'I-ORG'),
    (44, 51, 'B-NAME'),
    (52, 56, 'I-NAME'),
    (209, 229, 'B-WEB'),
    (230, 247, 'B-WEB'),
    (252, 283, 'B-WEB'),
    (284, 306, 'B-WEB'),
    (312, 322, 'B-PHONE'),
    (329, 344, 'B-EMAIL'),
    (345, 348, 'I-EMAIL')]}),
 ('s. rama krishna m. tech. senior faculty transportation engineering engineering staff college of india a forum of the institution of engineers india old bombay road gachi bowli hyderabad 500 32 india phone off 23000465 / 23000466 fax 040-23000336 e-mail esciic@yahoo com e-mail ramakrishnas23@hotmail.com ',
  {'entities': [(0, 2, 'B-NAME'),
    (3, 7, 'I-NAME'),
    (8, 15, 'I-NAME'),
    (25, 31, 'B-DES'),
    (32, 39, 'I-DES'),
    (67, 78, 'B-ORG'),
    (79, 84, 'I-ORG'),
    (85, 92, 'I-ORG'),
    (93, 95, 'I-ORG'),
    (96, 101, 'I-ORG'),
    (209, 217, 'B-PHONE'),
    (220, 228, 'B-PHONE'),
    (253, 265, 'B-EMAIL'),
    (266, 269, 'I-EMAIL'),
    (277, 303, 'B-EMAIL')]}),
 ('dr. b. umashankar associate professor department of civil engineering indian institute of technology hyderabad kandi sangareddy - 502285 telangana india tel -2250 6034 fax -2250 6032 e-mail buma@iith.ac.in http//www.iith.ac.in ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 6, 'I-NAME'),
    (7, 17, 'I-NAME'),
    (18, 27, 'B-DES'),
    (28, 37, 'I-DES'),
    (70, 76, 'B-ORG'),
    (77, 86, 'I-ORG'),
    (87, 89, 'I-ORG'),
    (90, 100, 'I-ORG'),
    (101, 110, 'I-ORG'),
    (157, 162, 'B-PHONE'),
    (163, 167, 'I-PHONE'),
    (190, 205, 'B-EMAIL'),
    (206, 226, 'B-WEB')]}),
 ('rn higreen design meee ra 7908225333 pa ltd ',
  {'entities': [(3, 10, 'B-ORG'),
    (11, 17, 'I-ORG'),
    (26, 36, 'B-PHONE'),
    (37, 39, 'I-ORG'),
    (40, 43, 'I-ORG')]}),
 ('burger king canada inc. manager jatheepa sathananthan maa nicole white 1490 dixie rd b k mississaugaon lse 3.00e05 burger king 905-274-1607 burger@king.com www.burgerking.com ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 11, 'I-ORG'),
    (12, 18, 'I-ORG'),
    (19, 23, 'I-ORG'),
    (24, 31, 'B-DES'),
    (32, 40, 'B-NAME'),
    (41, 53, 'I-NAME'),
    (58, 64, 'B-NAME'),
    (65, 70, 'I-NAME'),
    (115, 121, 'B-ORG'),
    (122, 126, 'I-ORG'),
    (127, 139, 'B-PHONE'),
    (140, 155, 'B-EMAIL'),
    (156, 174, 'B-WEB')]}),
 ('saja vik 990083000 g.s.m. booster 1 all types of mobile repair data transfer - game application led touch glass change all mobile led fitting mobile repair training loor city centre mall opp. mbai-central mumbai - 400 8 ӊbes.t. ',
  {'entities': [(0, 4, 'B-NAME'),
    (9, 18, 'B-PHONE'),
    (19, 25, 'B-ORG'),
    (26, 33, 'I-ORG')]}),
 ('off 40 23224963 res 40 23310679 fax 40 23222963 n.v. subba rao m. sc. m. sc.engg u.k. m.a. jt. transport commissioner b block 6 floor brk bhavan tank bund road hyderabad 500 63 e-mail nuvusetty12 @ rediffmail.com oe a ',
  {'entities': [(4, 6, 'B-PHONE'),
    (7, 15, 'I-PHONE'),
    (48, 52, 'B-NAME'),
    (53, 58, 'I-NAME'),
    (59, 62, 'I-NAME'),
    (91, 94, 'B-DES'),
    (95, 104, 'I-DES'),
    (105, 117, 'I-DES'),
    (184, 195, 'B-EMAIL'),
    (196, 197, 'I-EMAIL'),
    (198, 212, 'I-EMAIL')]}),
 ('sunil mehta manager ser eel ba pts eps ec 2 reine eay print aaa ee tepe ea uae ',
  {'entities': [(0, 5, 'B-NAME'), (6, 11, 'I-NAME'), (12, 19, 'B-DES')]}),
 ('cell 91 8143222000 sai balaji digital jh quality in time delivery long time durability low price hig flex vinyl printing 5-85/2 first floor oppchenna reddy hospital geetha theater road chanda nagar hyd-500050 e-mail saibalajidigitals9@gmail.com web www.saibalajidigitals.com ',
  {'entities': [(5, 7, 'B-PHONE'),
    (8, 18, 'I-PHONE'),
    (19, 22, 'B-ORG'),
    (23, 29, 'I-ORG'),
    (30, 37, 'I-ORG'),
    (216, 244, 'B-EMAIL'),
    (249, 274, 'B-WEB')]}),
 ('madison yacht sales paul madison yacht broker - northeast region fax 718-444-1206 ',
  {'entities': [(0, 7, 'B-ORG'),
    (8, 13, 'I-ORG'),
    (14, 19, 'I-ORG'),
    (20, 24, 'B-NAME'),
    (25, 32, 'I-NAME'),
    (33, 38, 'B-DES'),
    (39, 45, 'I-DES'),
    (69, 81, 'B-PHONE')]}),
 ('d.bhaskar reddy marketing executive triplex lab technologies pvt. ltd. gis division resource information xx remote sensing ac mapping solutions regd. office1-10-199/1 1st floor ashoknagar x roads hyd -20 ph 7613966 fax 7604489 email - contact@triplextec.com pe ae ',
  {'entities': [(0, 9, 'B-NAME'),
    (10, 15, 'I-NAME'),
    (16, 25, 'B-DES'),
    (26, 35, 'I-DES'),
    (36, 43, 'B-ORG'),
    (44, 47, 'I-ORG'),
    (48, 60, 'I-ORG'),
    (61, 65, 'I-ORG'),
    (66, 70, 'I-ORG'),
    (207, 214, 'B-PHONE'),
    (235, 257, 'B-EMAIL')]}),
 ('miami uy niilwaukee re anna zuckerman aczuckerman@gmail.com ',
  {'entities': [(28, 37, 'B-ORG'), (38, 59, 'B-EMAIL')]}),
 ('m. 9908075875 g. anjaneyulu goud anjaneyulu.goud@khannapublishers.in area sales manager khanna publishers regd. office 2-b nath market delhi -110006 phone 23912380 ',
  {'entities': [(3, 13, 'B-PHONE'),
    (14, 16, 'B-NAME'),
    (17, 27, 'I-NAME'),
    (33, 68, 'B-EMAIL'),
    (69, 73, 'B-DES'),
    (74, 79, 'I-DES'),
    (80, 87, 'I-DES'),
    (88, 94, 'B-ORG'),
    (95, 105, 'I-ORG'),
    (155, 163, 'B-PHONE')]}),
 ('ws bimgrafx naresh kumar m.v 0800 associate - business development 91 99855 67714 naresh.m@bimgrafx.com ',
  {'entities': [(3, 11, 'B-ORG'),
    (12, 18, 'B-NAME'),
    (19, 24, 'I-NAME'),
    (25, 28, 'I-NAME'),
    (34, 43, 'B-DES'),
    (46, 54, 'I-DES'),
    (55, 66, 'I-DES'),
    (67, 69, 'B-PHONE'),
    (70, 75, 'I-PHONE'),
    (76, 81, 'I-PHONE'),
    (82, 103, 'B-EMAIL')]}),
 ('p.s.deshpande phone 55501119 s.s.deshpande tele fax 24652049 mobile 21566652 industeics - . 4-7-339 esamia bazar victory play ground hyderabad-500 27 a.p. e-mail ',
  {'entities': [(0, 13, 'B-NAME'),
    (20, 28, 'B-PHONE'),
    (29, 42, 'B-NAME'),
    (68, 76, 'B-PHONE')]}),
 ('construction chemicals master builders technology mbt india pvt. ltd. 29 krishna nagar indl. layout g.vidya sagar reddy tavarakare main road sales engineer off hosur road opp prestige acropolis bangalore - 560 29 telefax 91-80-553 6859 mobile 9848127549 hyderabad meyter e-mail mbtindia29@vsnl.net web www.mbt-india.com ',
  {'entities': [(23, 29, 'B-ORG'),
    (30, 38, 'I-ORG'),
    (39, 49, 'I-ORG'),
    (50, 53, 'I-ORG'),
    (54, 59, 'I-ORG'),
    (60, 64, 'I-ORG'),
    (65, 69, 'I-ORG'),
    (100, 107, 'B-NAME'),
    (108, 113, 'I-NAME'),
    (114, 119, 'I-NAME'),
    (243, 253, 'B-PHONE'),
    (278, 297, 'B-EMAIL'),
    (302, 319, 'B-WEB')]}),
 ('r. krishnamoorthy hp 91 95661 22266 a rkb solutions the mindpower group company no 10a 1st floor rkr nagar poompuhar nagar 1st main road kolathur chennai -600 99 phone 91- 44-64563388 email kps@rkbsolutions.co.in wwwarkbsolutions.co.in ',
  {'entities': [(3, 17, 'B-NAME'),
    (21, 23, 'B-PHONE'),
    (24, 29, 'I-PHONE'),
    (30, 35, 'I-PHONE'),
    (38, 41, 'B-ORG'),
    (42, 51, 'I-ORG'),
    (52, 55, 'I-ORG'),
    (56, 65, 'I-ORG'),
    (66, 71, 'I-ORG'),
    (72, 79, 'I-ORG'),
    (168, 171, 'B-PHONE'),
    (172, 183, 'I-PHONE'),
    (190, 212, 'B-EMAIL'),
    (213, 235, 'B-WEB')]}),
 ('patanjal all patanjali products are available here go green distributors no.25 vivekanandha nagar behind radha rani theatre opp. eurokids school singanallur post coimbatore- 5 contact no 422 - 2273 729 94456 37712 70941 30557 go12green@gmail.com ',
  {'entities': [(0, 8, 'B-ORG'),
    (187, 190, 'B-PHONE'),
    (191, 192, 'I-PHONE'),
    (193, 197, 'I-PHONE'),
    (198, 201, 'I-PHONE'),
    (202, 207, 'B-PHONE'),
    (208, 213, 'I-PHONE'),
    (214, 219, 'I-PHONE'),
    (220, 225, 'I-PHONE'),
    (226, 245, 'B-EMAIL')]}),
 ('- 27903901 cell 32382439 s. prop. bhavani caterers specialists in north south andhra pure vegetarian meals dishes for all functions marriages gruha pravesham birthday parties a to z marriage contractors h.no. 1-38-1082 indiramma nagar begumpet near airport hyderababd ',
  {'entities': [(2, 10, 'B-PHONE'),
    (16, 24, 'I-PHONE'),
    (34, 41, 'B-NAME'),
    (42, 50, 'I-NAME')]}),
 ('mobile73963791 43 flex. print az designing printing cl el ',
  {'entities': [(0, 14, 'B-PHONE')]}),
 ('laxman. j mobitel 6275992 kavika photo video graphers specialist in modeling photography h.no. 1-1-257/29 behind mahaveer medical hall chikkadpally hyderabad - 500 20 ',
  {'entities': [(0, 7, 'B-NAME'),
    (8, 9, 'I-NAME'),
    (18, 25, 'B-PHONE'),
    (26, 32, 'B-ORG')]}),
 ('tof aan a a dalla a rae os mg ean te te k. om prakash . -40117949 b.e. civil m.s. australia 40118001 c.e.o. seatco group 30280000 cell 0091-8106888800 fax 30223333 cao seatco recognised by govt. of india squth east asia trading company ra. no. b-0180/ap/per/1000/5/5690/2001 sanatana ectasy office 203 liberty main road himayatnagar hyderabad - 500 29 telangana india. - website www.seatco.net email contact@seatco.net uae eoman e saudi qatar esingapore e kuwait uk e usa ',
  {'entities': [(40, 42, 'B-NAME'),
    (43, 45, 'I-NAME'),
    (46, 53, 'I-NAME'),
    (56, 65, 'B-PHONE'),
    (92, 100, 'B-PHONE'),
    (101, 107, 'B-DES'),
    (121, 129, 'B-PHONE'),
    (135, 150, 'B-PHONE'),
    (204, 209, 'B-ORG'),
    (210, 214, 'I-ORG'),
    (215, 219, 'I-ORG'),
    (220, 227, 'I-ORG'),
    (228, 235, 'I-ORG'),
    (379, 393, 'B-WEB'),
    (400, 418, 'B-EMAIL'),
    (431, 436, 'NAME')]}),
 ('ph 048-3306095 oj s ob 040-3748221 r fax 040-3397648 040-3731313 dr. m. anji re eddy m.tech.ph.d.rs environmental remote sensing gis lab. 524 vth floor academic black centre-for environment institute of pg studies research j.n.t. university mahaveer marg masab tank hyderabad - 500 28 a.p. india ',
  {'entities': [(3, 14, 'B-PHONE'),
    (23, 34, 'B-PHONE'),
    (65, 68, 'B-NAME'),
    (69, 71, 'I-NAME'),
    (72, 76, 'I-NAME'),
    (77, 79, 'I-NAME'),
    (80, 84, 'I-NAME'),
    (100, 113, 'B-ORG'),
    (114, 120, 'I-ORG'),
    (121, 128, 'I-ORG'),
    (129, 132, 'I-ORG'),
    (133, 137, 'I-ORG')]}),
 ('john doe @ businesscards.business q 123 broadway. ',
  {'entities': [(0, 4, 'B-NAME'), (5, 8, 'I-NAME')]}),
 ('prasad. c vishwam.c m.tech pgdca miste. m.techstruct. mie miste. ph. off. 23513527 9866648018 ph.off 23513527 9866648018 cell 98490 - 23777 cell 98490 - 44439 p.v.associates architects engineers email associates. pv@ gmail.com 12-2-823/a/1/8/c second floor inguva towers pillar no. 20-21 mehdipatnam abad. ',
  {'entities': [(0, 7, 'B-NAME'),
    (8, 9, 'I-NAME'),
    (10, 19, 'B-NAME'),
    (74, 82, 'B-PHONE'),
    (83, 93, 'B-PHONE'),
    (101, 109, 'B-PHONE'),
    (110, 120, 'B-PHONE'),
    (126, 131, 'B-PHONE'),
    (132, 133, 'I-PHONE'),
    (134, 139, 'I-PHONE'),
    (145, 150, 'B-PHONE'),
    (151, 152, 'I-PHONE'),
    (153, 158, 'I-PHONE'),
    (159, 173, 'B-ORG'),
    (201, 212, 'B-EMAIL'),
    (213, 216, 'I-EMAIL'),
    (217, 226, 'I-EMAIL')]}),
 ('p. ramulu a marketing executive ae 94406 15689 e ee @ gate - ece scitech publications india pvt. ltd. d 3-4-249/1 beside venkataramana theater lane street no.2 lingampally kachiguda hyderabad-500 27 phone 91 - 040- 2755 0050 2755 14 publishing scitechhyd @ yahoo.co.in future www.scitechpublications.com p ',
  {'entities': [(0, 2, 'B-NAME'),
    (3, 9, 'I-NAME'),
    (12, 21, 'B-DES'),
    (22, 31, 'I-DES'),
    (35, 40, 'B-PHONE'),
    (41, 46, 'I-PHONE'),
    (65, 72, 'B-ORG'),
    (73, 85, 'I-ORG'),
    (86, 91, 'I-ORG'),
    (92, 96, 'I-ORG'),
    (97, 101, 'I-ORG'),
    (205, 207, 'B-PHONE'),
    (210, 214, 'I-PHONE'),
    (215, 219, 'I-PHONE'),
    (220, 224, 'I-PHONE'),
    (225, 229, 'B-PHONE'),
    (230, 232, 'I-PHONE'),
    (233, 243, 'B-EMAIL'),
    (244, 254, 'I-EMAIL'),
    (255, 256, 'I-EMAIL'),
    (257, 268, 'I-EMAIL'),
    (276, 303, 'B-WEB')]}),

In [140]:
len(all_cards_data)

267

In [141]:
split_index = int(0.8 * len(all_cards_data))  # 80% for training
split_index

213

In [144]:
train_data = all_cards_data[:split_index]
test_data =  all_cards_data[split_index:]

In [146]:
len(test_data)

54

In [145]:
test_data

[('sharath ramadhyanam manager - business development 9 9133884848 / 91 7671814848 sharath@byndr.com by nn aq www.byndr.com ',
  {'entities': [(0, 7, 'B-NAME'),
    (8, 19, 'I-NAME'),
    (20, 27, 'B-DES'),
    (28, 29, 'I-DES'),
    (30, 38, 'I-DES'),
    (39, 50, 'I-DES'),
    (51, 52, 'B-PHONE'),
    (53, 63, 'I-PHONE'),
    (66, 68, 'B-PHONE'),
    (69, 79, 'I-PHONE'),
    (80, 97, 'B-EMAIL'),
    (107, 120, 'B-WEB')]}),
 ('chipotle mexican grill nathan houston general manager rand 817.577.0208 chipotle mexican grill inc. 817.577.0247 7604 denton highway watauga tx 76148 fax ',
  {'entities': [(23, 29, 'B-NAME'),
    (30, 37, 'I-NAME'),
    (38, 45, 'B-ORG'),
    (46, 53, 'I-ORG'),
    (59, 71, 'B-PHONE'),
    (72, 80, 'B-ORG'),
    (81, 88, 'I-ORG'),
    (89, 94, 'I-ORG'),
    (95, 99, 'I-ORG'),
    (100, 112, 'B-PHONE')]}),
 ('dr. d. 040-27500080 cell 9441285587 retd. prof. consulting civil engineer geotechnical engineer 3 resi. h. no. 6-1-108/18 abhinavanagar colony padmaraonagar secunderabad - 500 25 ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 6, 'I-NAME'),
    (7, 19, 'B-PHONE'),
    (25, 35, 'B-PHONE'),
    (36, 41, 'B-DES'),
    (42, 47, 'I-DES'),
    (48, 58, 'I-DES'),
    (59, 64, 'I-DES'),
    (65, 73, 'I-DES')]}),
 ('-209 251-8611 tom mason volkswagen volkswagen 5615 kings canyon road fresno california 93727 doug bloomer res. ph. sanger 787-2701 ',
  {'entities': [(0, 4, 'B-PHONE'),
    (5, 13, 'I-PHONE'),
    (14, 17, 'B-NAME'),
    (18, 23, 'I-NAME'),
    (24, 34, 'I-NAME'),
    (35, 45, 'B-ORG')]}),
 ('91 9849 366 10 ea nishanth@capeducationalservices.com capeducationalservices@gmail.com career adv ice point @ flat 205 saga society heights besides tilak nagar hospital tilak nagar hyderabad - 500 44 ',
  {'entities': [(0, 2, 'B-PHONE'),
    (3, 7, 'I-PHONE'),
    (8, 11, 'I-PHONE'),
    (12, 14, 'I-PHONE'),
    (18, 53, 'B-EMAIL'),
    (54, 86, 'B-EMAIL'),
    (87, 93, 'B-ORG'),
    (94, 97, 'I-ORG'),
    (98, 101, 'I-ORG'),
    (102, 107, 'I-ORG')]}),
 ('china national investment guaranty corp. zheng xian yao vice president senior economist add beijing commercial college tel 86-10 843-7042 33 fuoheng road beijing 841-7711 ext 2855 post code 100037 fax 86-10 843-7040 843-7043 ',
  {'entities': [(0, 5, 'B-ORG'),
    (6, 14, 'I-ORG'),
    (15, 25, 'I-ORG'),
    (26, 34, 'I-ORG'),
    (35, 40, 'I-ORG'),
    (41, 46, 'B-NAME'),
    (47, 51, 'I-NAME'),
    (52, 55, 'I-NAME'),
    (56, 60, 'B-DES'),
    (61, 70, 'I-DES'),
    (71, 77, 'I-DES'),
    (78, 87, 'I-DES'),
    (123, 128, 'B-PHONE'),
    (129, 137, 'I-PHONE'),
    (138, 140, 'I-PHONE'),
    (162, 170, 'B-PHONE'),
    (171, 174, 'I-PHONE'),
    (175, 179, 'I-PHONE')]}),
 ('shat ng am dunn 7 bas seb 44618 shia. aat 630 he fh 1.330.464.5501 mh 1.330.828.2108 www.facebook.com/petergrahamdunn www.p grahamdunn.com ',
  {'entities': [(67, 69, 'B-PHONE'),
    (85, 117, 'B-WEB'),
    (118, 123, 'B-WEB'),
    (124, 138, 'I-WEB')]}),
 ('suraksha double action cement a.b traders authorised distributor birla kesoram l t orient acc coromondal king andhra cement wholesaler retailer gudimatkapur cell 98480 ih phones 56570081 82 83 84 85 ',
  {'entities': [(0, 8, 'B-ORG'),
    (30, 33, 'B-ORG'),
    (34, 41, 'I-ORG'),
    (162, 167, 'B-PHONE'),
    (178, 186, 'B-PHONE'),
    (187, 189, 'I-PHONE'),
    (190, 192, 'I-PHONE'),
    (193, 195, 'I-PHONE'),
    (196, 198, 'I-PHONE')]}),
 ('reddy 9866186785 opp ramakrishna theatremain road peddapalli dist karimnagar telangana - 505172 email srihithaads.pdpl@ gmail.com ',
  {'entities': [(6, 16, 'B-PHONE'),
    (102, 119, 'B-EMAIL'),
    (120, 129, 'I-EMAIL')]}),
 ('state university mountains minds patrick henry adjunct professor/lecturer political science 1736 hanover hall bozeman mt 59717 tel -406 994-1776 fax -406 994-1913 email patrick.henry@montana.edu ',
  {'entities': [(0, 5, 'B-ORG'),
    (6, 16, 'I-ORG'),
    (33, 40, 'B-NAME'),
    (41, 46, 'I-NAME'),
    (92, 96, 'PHONE'),
    (131, 135, 'B-PHONE'),
    (136, 144, 'I-PHONE'),
    (169, 194, 'B-EMAIL')]}),
 ('venkatanarayanan technical hse project engineer projects technology tel 91 80 4021 7380 fax 91 80 4021 7158 mob 91 72 5902 7946 email v.sridharan2@shell.com shell technology centre bangalore shell india markets private limited rmz centennial campus b no. 8b kundalahalli main road bengaluru 560 048 india website www.shell.com ',
  {'entities': [(0, 16, 'B-NAME'),
    (17, 26, 'B-DES'),
    (27, 30, 'I-DES'),
    (31, 38, 'I-DES'),
    (39, 47, 'I-DES'),
    (72, 74, 'B-PHONE'),
    (75, 77, 'I-PHONE'),
    (78, 82, 'I-PHONE'),
    (83, 87, 'I-PHONE'),
    (112, 114, 'B-PHONE'),
    (115, 117, 'I-PHONE'),
    (118, 122, 'I-PHONE'),
    (123, 127, 'I-PHONE'),
    (134, 156, 'B-EMAIL'),
    (191, 196, 'B-ORG'),
    (197, 202, 'I-ORG'),
    (203, 210, 'I-ORG'),
    (211, 218, 'I-ORG'),
    (219, 226, 'I-ORG'),
    (313, 326, 'B-WEB')]}),
 ('the george washington university washington dc erik a. rodriguez assistant professor of chemistry department of chemistry 800 22nd street nw science and engineering hall suite 4000 washington dc 20052 202-994-0305 telephone 202-994-5873 fax erikrodriguez@gwu.edu 30 pow ',
  {'entities': [(0, 3, 'B-ORG'),
    (4, 10, 'I-ORG'),
    (11, 21, 'I-ORG'),
    (22, 32, 'I-ORG'),
    (47, 51, 'B-NAME'),
    (52, 54, 'I-NAME'),
    (55, 64, 'I-NAME'),
    (65, 74, 'B-DES'),
    (75, 84, 'I-DES'),
    (85, 87, 'I-DES'),
    (88, 97, 'I-DES'),
    (201, 213, 'B-PHONE'),
    (241, 262, 'B-EMAIL')]}),
 ('arn mt tear enforce ae infosolutions x ltd . creative courses robotics gaming animation videography photography digital painting graphics cad technology partners autodesk corel founpry. qunity e ',
  {'entities': [(0, 3, 'B-NAME'),
    (23, 36, 'B-ORG'),
    (37, 38, 'I-ORG'),
    (39, 42, 'I-ORG'),
    (129, 137, 'ORG'),
    (177, 185, 'EMAIL')]}),
 ('dr. syed faheem cell 9849015197 physiocare physiotherapy clinic flat no. 101 aries plaza behind chandana brothers st. anns college lane mehdipatnam hyderbad - 28 a ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 8, 'I-NAME'),
    (9, 15, 'I-NAME'),
    (21, 31, 'B-PHONE'),
    (32, 42, 'B-ORG')]}),
 ('g v gupta territory manager - academic cambridge university press cambridge university press india house no. 3-5-874/6/4 near fernandez hospital op block st.no.5 hyderguda hyderabad-500029 www.cambridgeindia.org tel 91 40 23244458 66101126 fax 91 4023244459 mobile 91 9849543342 email ggupta@cambridge.org i crater tne aman temd mn ft ',
  {'entities': [(0, 1, 'NAME'),
    (2, 3, 'NAME'),
    (39, 48, 'B-ORG'),
    (49, 59, 'I-ORG'),
    (60, 65, 'I-ORG'),
    (66, 75, 'B-ORG'),
    (76, 86, 'I-ORG'),
    (87, 92, 'I-ORG'),
    (93, 98, 'I-ORG'),
    (189, 211, 'B-WEB'),
    (216, 218, 'B-PHONE'),
    (219, 221, 'I-PHONE'),
    (222, 230, 'I-PHONE'),
    (231, 239, 'B-PHONE'),
    (265, 267, 'B-PHONE'),
    (268, 278, 'I-PHONE'),
    (285, 305, 'B-EMAIL')]}),
 ('krb mudaliar ph 0 27660486 cell 9849373800 res 27018231 offset printers eeoc designing cartons labels books brochures calenders greetings booklets posters etc. -2gyani complex 1-9-630/1 vidyanagar beside sbh hyderabad - 44 ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 12, 'I-NAME'),
    (16, 17, 'B-PHONE'),
    (18, 26, 'I-PHONE'),
    (32, 42, 'B-PHONE')]}),
 ('o 3314282 extn. 38 p-7635538- v.s.murthy msc.\u06dd associate professor officer - in - charge of exams - jntu college of fine arts mahaveer marg hyderabad - 28 res b-36 301 sreemaan krishna sri residency xb colony. hyderabad - 500 13 ',
  {'entities': [(2, 9, 'B-PHONE'),
    (10, 15, 'I-PHONE'),
    (16, 18, 'I-PHONE'),
    (30, 40, 'B-NAME'),
    (47, 56, 'B-DES'),
    (57, 66, 'I-DES')]}),
 ('y-wireless repair eee certified technician phone tablet - electronic repairs call us 330-270-5060 facebook.com/youngstownwirelessrepair ',
  {'entities': [(0, 10, 'B-ORG'), (11, 17, 'I-ORG'), (85, 97, 'B-PHONE')]}),
 ('aditya birla g venu territory technical services manager ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 12, 'I-ORG'),
    (13, 14, 'B-NAME'),
    (15, 19, 'I-NAME'),
    (20, 29, 'B-DES'),
    (30, 39, 'I-DES'),
    (40, 48, 'I-DES'),
    (49, 56, 'I-DES')]}),
 ('dr. ramesh kumar t. reddy managing director spatial applications limited 770-f road 44 jubilee hills hyderabad - 500 33 alp. india. phone 91 40 360 8244 360 8148 production office 91 40 354 2020 web-site www.spatialapps.com ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 10, 'I-NAME'),
    (11, 16, 'I-NAME'),
    (17, 19, 'I-NAME'),
    (20, 25, 'I-NAME'),
    (26, 34, 'B-DES'),
    (35, 43, 'I-DES'),
    (44, 51, 'B-ORG'),
    (52, 64, 'I-ORG'),
    (65, 72, 'I-ORG'),
    (138, 140, 'B-PHONE'),
    (141, 143, 'I-PHONE'),
    (144, 147, 'I-PHONE'),
    (148, 152, 'I-PHONE'),
    (153, 156, 'I-PHONE'),
    (157, 161, 'I-PHONE'),
    (204, 223, 'B-WEB')]}),
 ('dr. k.h.v. durga rao head disaster management support division national remote sensing centre indian space research organisation department of space government of india balanagar hyderabad - 500 037 telangana india tel off. 91 40 23884541 / 4232 fax 971 40 23870445 / 23774271 mobile 91 9440583027 e-mail durgaraokhv@nrsc.gov.in khvdurgarao@yahoo.com ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 10, 'I-NAME'),
    (11, 16, 'I-NAME'),
    (17, 20, 'I-NAME'),
    (21, 25, 'B-DES'),
    (94, 100, 'B-ORG'),
    (101, 106, 'I-ORG'),
    (107, 115, 'I-ORG'),
    (116, 128, 'I-ORG'),
    (224, 226, 'B-PHONE'),
    (227, 229, 'I-PHONE'),
    (230, 238, 'I-PHONE'),
    (241, 245, 'I-PHONE'),
    (257, 265, 'PHONE'),
    (268, 276, 'PHONE'),
    (284, 286, 'B-PHONE'),
    (287, 297, 'I-PHONE'),
    (305, 328, 'B-EMAIL'),
    (329, 350, 'B-EMAIL')]}),
 ('evan caulfield cubermed internet marketing consultant we dont just build your website we build your business 5834 robins n p -703 249-0001 ext 703 e evan@cybermed.com ',
  {'entities': [(0, 4, 'B-NAME'),
    (5, 14, 'I-NAME'),
    (15, 23, 'B-ORG'),
    (125, 129, 'B-PHONE'),
    (130, 138, 'I-PHONE'),
    (149, 166, 'B-EMAIL')]}),
 ('prasad @ 99631735359490400000 i flex design album design visiting cards dtp works telugu english ',
  {'entities': [(0, 6, 'B-NAME')]}),
 ('oracle۪ oracle india private limited prestige technology park mercury block 2b lvl 7-9 29 sarjapur marthahalli ring road bangalore karnataka - 560 103 india chandrasekhar patarlapalli pmp director jd edwards enterpriseone phone 91 80 40298952 mobile 91.98 80594936 fax 91 80 40296480 chandrasekhar.patarlapalli@oracle.com oracle.com ',
  {'entities': [(8, 14, 'B-ORG'),
    (15, 20, 'I-ORG'),
    (21, 28, 'I-ORG'),
    (29, 36, 'I-ORG'),
    (157, 170, 'B-NAME'),
    (171, 183, 'I-NAME'),
    (188, 196, 'B-DES'),
    (228, 230, 'B-PHONE'),
    (231, 233, 'I-PHONE'),
    (234, 242, 'I-PHONE'),
    (250, 255, 'B-PHONE'),
    (256, 264, 'I-PHONE'),
    (284, 321, 'B-EMAIL'),
    (322, 332, 'B-WEB')]}),
 ('a national academy of construction nac prof. m. prasad m.tech. ae director cmri nac campus cyberabad e-mail nac @ satyam.net.in r 23838158-504 ',
  {'entities': [(2, 10, 'B-ORG'),
    (11, 18, 'I-ORG'),
    (19, 21, 'I-ORG'),
    (22, 34, 'I-ORG'),
    (39, 44, 'B-NAME'),
    (45, 47, 'I-NAME'),
    (48, 54, 'I-NAME'),
    (66, 74, 'B-DES'),
    (130, 142, 'B-PHONE')]}),
 ('john w. best senior electronics design engineer 2124 old gatesburg road phone -814 867-8600 ext. 255 state college pa 16803 fax -814 867-4513 jbest@spectrumedix.com ',
  {'entities': [(0, 4, 'B-NAME'),
    (5, 7, 'I-NAME'),
    (8, 12, 'I-NAME'),
    (13, 19, 'B-DES'),
    (20, 31, 'B-DES'),
    (32, 38, 'B-DES'),
    (39, 47, 'B-DES'),
    (78, 82, 'B-PHONE'),
    (83, 91, 'I-PHONE'),
    (142, 164, 'B-EMAIL')]}),
 ('dr.d. vijay kishore b.archm.up phd altp fila principal co-ordinator national centre for qip programme co-ordinator npcbaerm head of architecture school of planning and architecture jawaharlal nehru technological university mahavir marg hyderabad- 500 28 india ph. -40 23310133 23300315 233317006 fax 23390770 email dvijaykishore @rediffmail com ',
  {'entities': [(0, 5, 'B-NAME'),
    (6, 11, 'I-NAME'),
    (12, 19, 'I-NAME'),
    (145, 151, 'B-ORG'),
    (152, 154, 'I-ORG'),
    (155, 163, 'I-ORG'),
    (164, 167, 'I-ORG'),
    (168, 180, 'I-ORG'),
    (181, 191, 'I-ORG'),
    (192, 197, 'I-ORG'),
    (198, 211, 'I-ORG'),
    (212, 222, 'I-ORG'),
    (264, 267, 'B-PHONE'),
    (268, 276, 'I-PHONE'),
    (277, 285, 'I-PHONE'),
    (286, 295, 'I-PHONE'),
    (315, 328, 'B-EMAIL'),
    (329, 340, 'I-EMAIL'),
    (341, 344, 'I-EMAIL')]}),
 ('capricot francis.a business manager education solutions m 91 93460 39220 e francis.a@capricot.com p 91 40 6663 9371/ 73 f 91 40 6663 9372 capricot.com capricot technologies pvt. ltd. unit no.7 8 4th floor downtown - the mall۪ 6-2-27/a 6-2-28 beside lotus hospital lakdikapul hyderabad 500 004 india bangalore new delhi mumbai hyderabad ',
  {'entities': [(19, 27, 'B-DES'),
    (28, 35, 'I-DES'),
    (58, 60, 'B-EMAIL'),
    (61, 66, 'I-EMAIL'),
    (67, 72, 'I-EMAIL'),
    (75, 97, 'B-EMAIL'),
    (100, 102, 'B-PHONE'),
    (103, 105, 'I-PHONE'),
    (106, 110, 'I-PHONE'),
    (111, 116, 'I-PHONE'),
    (125, 127, 'PHONE'),
    (128, 132, 'PHONE'),
    (133, 137, 'PHONE'),
    (138, 150, 'WEB'),
    (151, 159, 'B-ORG'),
    (160, 172, 'I-ORG'),
    (173, 177, 'I-ORG'),
    (178, 182, 'I-ORG')]}),
 ('kumar swamy. m deputy general manager mobile 9100771796 visit our website www.vishwa.co.in founded by alumni of iits nits a email vishwahyd1@gmail.com gate ies psus dilshunagar kukatpally 4 floor near sidhartha 4 floor above sbi 2\u06dd floor 04-jan arundelpet 2 floor greensquare plaza womens degree collage kphb colony above kapil chit funds guntur hanamkonda warangal 7093002099 7093298707 9440475345 986676452 7032902099 9866976452 9866974972 ',
  {'entities': [(0, 5, 'B-NAME'),
    (6, 12, 'I-NAME'),
    (13, 14, 'I-NAME'),
    (15, 21, 'B-DES'),
    (22, 29, 'I-DES'),
    (30, 37, 'I-DES'),
    (45, 55, 'B-PHONE'),
    (74, 90, 'B-WEB'),
    (130, 150, 'B-EMAIL'),
    (366, 376, 'B-PHONE'),
    (409, 419, 'B-PHONE'),
    (420, 430, 'B-PHONE'),
    (431, 441, 'B-PHONE')]}),
 ('dr. g. venkataramana m.b.b.s. d.v. d.p.c. p.g.d.f.e. f.c.s.e.p.1. ph.d. diplomate american board of sexology w.h.o.-fellow on stds aids consultant vatsayana clinic special clinic for sexual marital problems g-i dhruvatara apts near eenadu paper office next to rta office medinova compound erramanzil somajiguda hyderabad-500 82 040-23319519 time 5-00 p.m. to 9-00 pm. mobile 9246345937 e-mailaidsandsex @rocketmail.com ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 6, 'I-NAME'),
    (7, 20, 'I-NAME'),
    (136, 146, 'B-DES'),
    (147, 156, 'B-ORG'),
    (157, 163, 'I-ORG'),
    (328, 340, 'B-PHONE'),
    (375, 385, 'B-PHONE'),
    (386, 402, 'B-EMAIL'),
    (403, 418, 'I-EMAIL')]}),
 ('hilton oak lawn heather stevens catering manager 9333 south cicero avenue oak lawn il 60453 tel 708 425 7800 direct line 708 229 8859 fax 708 229 8858 email heather.stevens@hilton.com honors hilton official sponsor ',
  {'entities': [(0, 6, 'B-ORG'),
    (7, 10, 'I-ORG'),
    (11, 15, 'I-ORG'),
    (16, 23, 'B-NAME'),
    (24, 31, 'I-NAME'),
    (32, 40, 'B-DES'),
    (41, 48, 'I-DES'),
    (96, 99, 'B-PHONE'),
    (100, 103, 'I-PHONE'),
    (104, 108, 'I-PHONE'),
    (157, 183, 'B-EMAIL')]}),
 ('esri india krishna mohan deshiraju associate consultant niit gis ltd. 3rd floor prashanti complex basheerbagh hyderabad - 500 63 india e tel 9140 55633616 23240434 23243336 fax 9140 23231567 23298867 e-mail krishnamd@niit.com e website www.eesriindia.com ',
  {'entities': [(0, 4, 'B-ORG'),
    (5, 10, 'B-ORG'),
    (11, 18, 'B-NAME'),
    (19, 24, 'I-NAME'),
    (25, 34, 'I-NAME'),
    (35, 44, 'B-DES'),
    (45, 55, 'I-DES'),
    (56, 60, 'B-ORG'),
    (61, 64, 'I-ORG'),
    (65, 69, 'I-ORG'),
    (141, 145, 'B-PHONE'),
    (146, 154, 'I-PHONE'),
    (155, 163, 'I-PHONE'),
    (164, 172, 'I-PHONE'),
    (207, 225, 'B-EMAIL'),
    (236, 254, 'B-WEB')]}),
 ('jeffery barnes leasing professional cell 818-283-2837 office 818-283-5987 fax 818-283-2339 www.allbizcards.com 3948 auto center dr. davidv@allbizcards.com los angeles ca 90025 ',
  {'entities': [(0, 7, 'B-NAME'),
    (8, 14, 'I-NAME'),
    (15, 22, 'B-DES'),
    (23, 35, 'I-DES'),
    (41, 53, 'B-PHONE'),
    (61, 73, 'B-PHONE'),
    (91, 110, 'B-WEB')]}),
 ('\u06dd ravikumar ft manager infinitypmc infinitypmc private limited workhub@axis no 27 vellalar street 4th floor adambakkam chennai - 600 88 landmark above hdfc bank ltd ee eure mom tcm mat oscr tt tct rad ',
  {'entities': [(2, 11, 'B-NAME'),
    (15, 22, 'B-ORG'),
    (23, 34, 'B-ORG'),
    (35, 46, 'B-ORG'),
    (47, 54, 'I-ORG'),
    (55, 62, 'I-ORG'),
    (151, 155, 'ORG'),
    (156, 160, 'ORG'),
    (161, 164, 'ORG')]}),
 ('ph off 051-9252887 fax no. 051-9252339 e-mail ar.shakir@hotmail.com abdul rashid shakir assistant director audit bureau of circulation abc ministry of information and broadcasting government of pakistan 4 floor block c-1 benevolent fund building zero point islamabad. ',
  {'entities': [(7, 18, 'B-PHONE'),
    (46, 67, 'B-EMAIL'),
    (68, 73, 'B-NAME'),
    (74, 80, 'I-NAME'),
    (81, 87, 'I-NAME'),
    (88, 97, 'B-DES'),
    (98, 106, 'I-DES')]}),
 ('srinivas tallapragada executive director en es for iso 9001 2015 company satyavani projects and consultants pvt. ltd. a-203 kushal towers khairatabad hyderabad-500 4 tel 91-40-39804646 23321623 d 39804621 fax 91-04-23308184 mobile 9866749191 e-maib ',
  {'entities': [(0, 8, 'B-NAME'),
    (9, 21, 'I-NAME'),
    (22, 31, 'B-DES'),
    (32, 40, 'I-DES'),
    (73, 82, 'B-ORG'),
    (83, 91, 'I-ORG'),
    (92, 95, 'I-ORG'),
    (96, 107, 'I-ORG'),
    (108, 112, 'I-ORG'),
    (113, 117, 'I-ORG'),
    (170, 184, 'B-PHONE'),
    (185, 193, 'I-PHONE'),
    (209, 223, 'B-PHONE'),
    (231, 241, 'I-PHONE')]}),
 ('sathish 9840768632 raji 9566359907 azhar 9840840097 mechanic page re- modification selling and buying 49 cnk road triplicane chennai - 600 5 email chainsgears@gmail.com ',
  {'entities': [(0, 7, 'B-NAME'),
    (8, 18, 'B-PHONE'),
    (19, 23, 'B-NAME'),
    (24, 34, 'B-PHONE'),
    (35, 40, 'B-NAME'),
    (41, 51, 'B-PHONE'),
    (52, 60, 'B-DES'),
    (147, 168, 'B-EMAIL')]}),
 ('dr. michael dean clarinet performing teaching and consulting 682.888.7639 clarinetmike.com clarinetmike.wordpress.com clarinetmiketexas@ yahoo.com ',
  {'entities': [(0, 3, 'B-NAME'),
    (4, 11, 'I-NAME'),
    (12, 16, 'I-NAME'),
    (37, 45, 'B-DES'),
    (46, 49, 'I-DES'),
    (50, 60, 'I-DES'),
    (61, 73, 'B-PHONE'),
    (74, 90, 'B-WEB'),
    (91, 117, 'B-WEB'),
    (118, 136, 'B-EMAIL'),
    (137, 146, 'I-EMAIL')]}),
 ('kenneth y. fishman dds steven e. roth dmd timothy chase dmd 220 east 63rd street new york ny 10065 s milesn y 212-752-6537 cosmetic implant dentistry www.smilesny.com creating new yorks most beautiful smiles flosstard 12 varps patent 5722439 other patents pending ',
  {'entities': [(0, 7, 'B-NAME'),
    (8, 10, 'I-NAME'),
    (110, 122, 'B-PHONE'),
    (123, 131, 'B-ORG'),
    (132, 139, 'I-ORG'),
    (150, 166, 'B-EMAIL')]}),
 ('james bond ey sales leasing consultant 4718 san femando road award of excellence glendale ca 91204 bus 818-547-4220 fax 818-547-4680 info@firstprintingca.com your nissan sales ',
  {'entities': [(0, 5, 'B-NAME'),
    (6, 10, 'I-NAME'),
    (14, 19, 'B-DES'),
    (20, 27, 'I-DES'),
    (28, 38, 'I-DES'),
    (103, 115, 'B-PHONE'),
    (133, 157, 'B-EMAIL'),
    (158, 162, 'B-ORG'),
    (163, 169, 'I-ORG'),
    (170, 175, 'I-ORG')]}),
 ('walt disney productions kee۪ john f. curry director 2 hotel division ams -213 245-8951 500 so. buena vista st. burbank california 91503 ',
  {'entities': [(0, 4, 'B-ORG'),
    (5, 11, 'I-ORG'),
    (29, 33, 'B-NAME'),
    (34, 36, 'I-NAME'),
    (37, 42, 'I-NAME'),
    (43, 51, 'B-DES'),
    (73, 77, 'B-PHONE'),
    (78, 86, 'I-PHONE')]}),
 ('a. srinivas rao ph 23112470 cell 98480 41937 sri shirdi sai caterer s kavuri hills - 1 madhapur hyderabad. ',

### Save data into pickle formate

In [142]:
import pickle

In [147]:
pickle.dump(train_data, open('./data/train_data.pkl', mode = 'wb'))
pickle.dump(test_data, open('./data/test_data.pkl', mode = 'wb'))