In [4]:
from cv2 import imread
from cv2 import waitKey
from cv2 import destroyAllWindows
from cv2 import imshow

In [7]:
inv_img = imread('./invoices/page_11.png')

In [12]:
from pytesseract import image_to_string
from pytesseract import image_to_data

In [13]:

text_cv = image_to_string(inv_img)
text_cv

'De propere tuin by Stefan\nMertens\n\n3 Berkenstraat\n\nAarschot, 3200\n\nBelgié\n\ninfo @deproperetuinbystefan.be\nTelefoon: 0474685499\n\nRekening naar:\n\nlise\n\nUrban Real Estate BV\nSchippersstraat 21\nHasselt, 3500\n\nBelgié\n\nFACTUUR #0000042\n\nUitgiftedatum: 25 jul 2024\nVervaldatum: 1 aug 2024\n\nBtw-id: BE 1005.429.249\nIBAN: BEQ9 7310 5924 6157\n\nExtra klantgegevens:\n\niise@soreal.be\nBtw-id: BE0881 675 560\n\nTuinonderhoud op 23 juli 2024 (BTW VERLEGD)\n\nProduct of dienst Aantal\nWerkuren 3.5\nMateriaalkosten 1\nKilometervergoeding 26\n\nPrijs Belasting Lijntotaal\n€ 37,20 € 130,20\n€5,00 € 5,00\n\n€0,20 € 5,20\n\n25 \\wa\n'

In [14]:
data = image_to_data(inv_img)
data

'level\tpage_num\tblock_num\tpar_num\tline_num\tword_num\tleft\ttop\twidth\theight\tconf\ttext\n1\t1\t0\t0\t0\t0\t0\t0\t2483\t3510\t-1\t\n2\t1\t1\t0\t0\t0\t313\t828\t551\t289\t-1\t\n3\t1\t1\t1\t0\t0\t314\t828\t444\t71\t-1\t\n4\t1\t1\t1\t1\t0\t314\t828\t444\t34\t-1\t\n5\t1\t1\t1\t1\t1\t314\t829\t42\t27\t90.951714\tDe\n5\t1\t1\t1\t1\t2\t371\t836\t137\t26\t90.951714\tpropere\n5\t1\t1\t1\t1\t3\t522\t828\t62\t28\t91.361153\ttuin\n5\t1\t1\t1\t1\t4\t596\t829\t40\t33\t95.540474\tby\n5\t1\t1\t1\t1\t5\t647\t829\t111\t27\t96.319031\tStefan\n4\t1\t1\t1\t2\t0\t314\t873\t141\t26\t-1\t\n5\t1\t1\t1\t2\t1\t314\t873\t141\t26\t96.433662\tMertens\n3\t1\t1\t2\t0\t0\t313\t916\t245\t27\t-1\t\n4\t1\t1\t2\t1\t0\t313\t916\t245\t27\t-1\t\n5\t1\t1\t2\t1\t1\t313\t916\t18\t27\t92.882111\t3\n5\t1\t1\t2\t1\t2\t344\t916\t214\t26\t90.253540\tBerkenstraat\n3\t1\t1\t3\t0\t0\t314\t959\t246\t30\t-1\t\n4\t1\t1\t3\t1\t0\t314\t959\t246\t30\t-1\t\n5\t1\t1\t3\t1\t1\t314\t959\t154\t30\t92.133438\tAarschot,\n5\t1\t1\t3\t1\t2\t482\t959\t78\t27\t96.226601\t3200\n3\t1\t1\t4\t0\t0\t316\t1002\t101\t34\t-1\t\n4\t1\t1\t4\t1\t0\t316\t1002\t101\t34\t-1\t\n5\t1\t1\t4\t1\t1\t316\t1002\t101\t34\t84.573639\tBelgié\n3\t1\t1\t5\t0\t0\t314\t1045\t550\t72\t-1\t\n4\t1\t1\t5\t1\t0\t315\t1045\t549\t34\t-1\t\n5\t1\t1\t5\t1\t1\t315\t1046\t59\t26\t89.837425\tinfo\n5\t1\t1\t5\t1\t2\t381\t1045\t483\t34\t89.837425\t@deproperetuinbystefan.be\n4\t1\t1\t5\t2\t0\t314\t1089\t388\t28\t-1\t\n5\t1\t1\t5\t2\t1\t314\t1089\t158\t28\t90.967056\tTelefoon:\n5\t1\t1\t5\t2\t2\t485\t1089\t217\t28\t96.627693\t0474685499\n2\t1\t2\t0\t0\t0\t316\t1243\t362\t258\t-1\t\n3\t1\t2\t1\t0\t0\t317\t1243\t246\t34\t-1\t\n4\t1\t2\t1\t1\t0\t317\t1243\t246\t34\t-1\t\n5\t1\t2\t1\t1\t1\t317\t1243\t153\t34\t91.159515\tRekening\n5\t1\t2\t1\t1\t2\t484\t1251\t79\t20\t96.736366\tnaar:\n3\t1\t2\t2\t0\t0\t317\t1294\t56\t26\t-1\t\n4\t1\t2\t2\t1\t0\t317\t1294\t56\t26\t-1\t\n5\t1\t2\t2\t1\t1\t317\t1294\t56\t26\t56.324120\tlise\n3\t1\t2\t3\t0\t0\t316\t1337\t362\t116\t-1\t\n4\t1\t2\t3\t1\t0\t317\t1337\t361\t27\t-1\t\n5\t1\t2\t3\t1\t1\t317\t1337\t99\t27\t94.748993\tUrban\n5\t1\t2\t3\t1\t2\t429\t1337\t69\t26\t96.757950\tReal\n5\t1\t2\t3\t1\t3\t510\t1337\t106\t26\t96.412834\tEstate\n5\t1\t2\t3\t1\t4\t632\t1337\t46\t26\t96.702728\tBV\n4\t1\t2\t3\t2\t0\t316\t1380\t305\t33\t-1\t\n5\t1\t2\t3\t2\t1\t316\t1380\t267\t33\t92.156784\tSchippersstraat\n5\t1\t2\t3\t2\t2\t593\t1380\t28\t26\t96.826851\t21\n4\t1\t2\t3\t3\t0\t318\t1423\t224\t30\t-1\t\n5\t1\t2\t3\t3\t1\t318\t1423\t130\t30\t95.472931\tHasselt,\n5\t1\t2\t3\t3\t2\t461\t1423\t81\t27\t96.439163\t3500\n3\t1\t2\t4\t0\t0\t319\t1466\t100\t35\t-1\t\n4\t1\t2\t4\t1\t0\t319\t1466\t100\t35\t-1\t\n5\t1\t2\t4\t1\t1\t319\t1466\t100\t35\t92.410736\tBelgié\n2\t1\t3\t0\t0\t0\t1569\t520\t603\t47\t-1\t\n3\t1\t3\t1\t0\t0\t1569\t520\t603\t47\t-1\t\n4\t1\t3\t1\t1\t0\t1569\t520\t603\t47\t-1\t\n5\t1\t3\t1\t1\t1\t1569\t521\t285\t46\t91.072388\tFACTUUR\n5\t1\t3\t1\t1\t2\t1871\t520\t301\t47\t96.280464\t#0000042\n2\t1\t4\t0\t0\t0\t1754\t629\t420\t87\t-1\t\n3\t1\t4\t1\t0\t0\t1754\t629\t420\t87\t-1\t\n4\t1\t4\t1\t1\t0\t1754\t629\t420\t34\t-1\t\n5\t1\t4\t1\t1\t1\t1754\t629\t235\t34\t81.367065\tUitgiftedatum:\n5\t1\t4\t1\t1\t2\t2002\t629\t34\t27\t96.154594\t25\n5\t1\t4\t1\t1\t3\t2046\t629\t35\t33\t94.500038\tjul\n5\t1\t4\t1\t1\t4\t2094\t629\t80\t27\t96.840561\t2024\n4\t1\t4\t1\t2\t0\t1778\t681\t396\t35\t-1\t\n5\t1\t4\t1\t2\t1\t1778\t681\t209\t27\t91.233002\tVervaldatum:\n5\t1\t4\t1\t2\t2\t2000\t682\t10\t26\t93.861023\t1\n5\t1\t4\t1\t2\t3\t2025\t689\t55\t27\t93.861023\taug\n5\t1\t4\t1\t2\t4\t2094\t681\t80\t27\t96.229507\t2024\n2\t1\t5\t0\t0\t0\t1047\t1034\t455\t83\t-1\t\n3\t1\t5\t1\t0\t0\t1047\t1034\t455\t83\t-1\t\n4\t1\t5\t1\t1\t0\t1047\t1034\t394\t27\t-1\t\n5\t1\t5\t1\t1\t1\t1047\t1034\t107\t27\t91.515526\tBtw-id:\n5\t1\t5\t1\t1\t2\t1169\t1034\t40\t27\t91.319206\tBE\n5\t1\t5\t1\t1\t3\t1220\t1034\t221\t27\t90.066360\t1005.429.249\n4\t1\t5\t1\t2\t0\t1048\t1089\t454\t28\t-1\t\n5\t1\t5\t1\t2\t1\t1048\t1090\t84\t27\t91.620941\tIBAN:\n5\t1\t5\t1\t2\t2\t1146\t1089\t83\t28\t84.999664\tBEQ9\n5\t1\t5\t1\t2\t3\t1243\t1089\t76\t28\t96.657074\t7310\n5\t1\t5\t1\t2\t4\t1332\t1089\t80\t28\t96.511139\t5924\n5\t1\t5\t1\t2\t5\t1424\t1089\t78\t28\t95.905128\t6157\n2\t1\t6\t0\t0\t0\t1034\t1245\t360\t34\t-1\t\n3\t1\t6\t1\t0\t0\t1034\t1245\t360\t34\t-1\t\n4\t1\t6\t1\t1\t0\t1034\t1245\t360\t34\t-1\t\n5\t1\t6\t1\t1\t1\t1034\t1245\t81\t27\t91.435432\tExtra\n5\t1\t6\t1\t1\t2\t1129\t1245\t265\t34\t63.689327\tklantgegevens:\n2\t1\t7\t0\t0\t0\t1033\t1294\t394\t72\t-1\t\n3\t1\t7\t1\t0\t0\t1033\t1294\t394\t72\t-1\t\n4\t1\t7\t1\t1\t0\t1033\t1294\t251\t33\t-1\t\n5\t1\t7\t1\t1\t1\t1033\t1294\t251\t33\t69.966187\tiise@soreal.be\n4\t1\t7\t1\t2\t0\t1035\t1337\t392\t29\t-1\t\n5\t1\t7\t1\t2\t1\t1035\t1338\t107\t26\t91.721191\tBtw-id:\n5\t1\t7\t1\t2\t2\t1156\t1337\t122\t29\t39.804817\tBE0881\n5\t1\t7\t1\t2\t3\t1294\t1338\t59\t28\t96.911263\t675\n5\t1\t7\t1\t2\t4\t1365\t1337\t62\t27\t96.155151\t560\n2\t1\t8\t0\t0\t0\t318\t1673\t1347\t57\t-1\t\n3\t1\t8\t1\t0\t0\t318\t1673\t1347\t57\t-1\t\n4\t1\t8\t1\t1\t0\t318\t1673\t1347\t57\t-1\t\n5\t1\t8\t1\t1\t1\t318\t1673\t424\t47\t91.987717\tTuinonderhoud\n5\t1\t8\t1\t1\t2\t761\t1686\t72\t44\t96.930931\top\n5\t1\t8\t1\t1\t3\t850\t1674\t66\t46\t95.680527\t23\n5\t1\t8\t1\t1\t4\t930\t1673\t78\t57\t93.276726\tjuli\n5\t1\t8\t1\t1\t5\t1026\t1674\t144\t46\t93.276726\t2024\n5\t1\t8\t1\t1\t6\t1190\t1674\t153\t53\t90.385475\t(BTW\n5\t1\t8\t1\t1\t7\t1361\t1673\t304\t53\t90.385475\tVERLEGD)\n2\t1\t9\t0\t0\t0\t323\t1806\t633\t520\t-1\t\n3\t1\t9\t1\t0\t0\t323\t1806\t633\t515\t-1\t\n4\t1\t9\t1\t1\t0\t323\t1806\t633\t32\t-1\t\n5\t1\t9\t1\t1\t1\t323\t1807\t157\t31\t96.827690\tProduct\n5\t1\t9\t1\t1\t2\t492\t1807\t39\t31\t93.285110\tof\n5\t1\t9\t1\t1\t3\t543\t1806\t125\t32\t91.161850\tdienst\n5\t1\t9\t1\t1\t4\t823\t1807\t133\t31\t85.591583\tAantal\n4\t1\t9\t1\t2\t0\t323\t1947\t554\t49\t-1\t\n5\t1\t9\t1\t2\t1\t323\t1947\t175\t49\t91.227196\tWerkuren\n5\t1\t9\t1\t2\t2\t825\t1951\t52\t31\t96.705444\t3.5\n4\t1\t9\t1\t3\t0\t326\t2116\t514\t32\t-1\t\n5\t1\t9\t1\t3\t1\t326\t2116\t304\t32\t92.097626\tMateriaalkosten\n5\t1\t9\t1\t3\t2\t827\t2116\t13\t30\t96.900848\t1\n4\t1\t9\t1\t4\t0\t327\t2276\t545\t50\t-1\t\n5\t1\t9\t1\t4\t1\t327\t2276\t401\t50\t91.353088\tKilometervergoeding\n5\t1\t9\t1\t4\t2\t827\t2281\t45\t32\t97.001335\t26\n2\t1\t10\t0\t0\t0\t1174\t1802\t1006\t351\t-1\t\n3\t1\t10\t1\t0\t0\t1174\t1802\t1006\t351\t-1\t\n4\t1\t10\t1\t1\t0\t1176\t1802\t1001\t49\t-1\t\n5\t1\t10\t1\t1\t1\t1176\t1802\t83\t49\t96.882454\tPrijs\n5\t1\t10\t1\t1\t2\t1523\t1806\t189\t40\t92.118950\tBelasting\n5\t1\t10\t1\t1\t3\t1985\t1806\t192\t39\t91.748703\tLijntotaal\n4\t1\t10\t1\t2\t0\t1174\t1950\t1005\t39\t-1\t\n5\t1\t10\t1\t2\t1\t1174\t1951\t24\t32\t93.305161\t€\n5\t1\t10\t1\t2\t2\t1209\t1951\t100\t38\t96.588821\t37,20\n5\t1\t10\t1\t2\t3\t2018\t1950\t24\t32\t93.283432\t€\n5\t1\t10\t1\t2\t4\t2055\t1950\t124\t38\t96.747849\t130,20\n4\t1\t10\t1\t3\t0\t1175\t2115\t1005\t38\t-1\t\n5\t1\t10\t1\t3\t1\t1175\t2116\t116\t37\t92.387466\t€5,00\n5\t1\t10\t1\t3\t2\t2063\t2115\t23\t31\t93.284935\t€\n5\t1\t10\t1\t3\t3\t2098\t2115\t82\t37\t96.129280\t5,00\n2\t1\t11\t0\t0\t0\t1176\t2280\t1005\t38\t-1\t\n3\t1\t11\t1\t0\t0\t1176\t2280\t1005\t38\t-1\t\n4\t1\t11\t1\t1\t0\t1176\t2280\t1005\t38\t-1\t\n5\t1\t11\t1\t1\t1\t1176\t2281\t116\t37\t91.596008\t€0,20\n5\t1\t11\t1\t1\t2\t2067\t2280\t24\t31\t93.295303\t€\n5\t1\t11\t1\t1\t3\t2102\t2280\t79\t38\t96.072311\t5,20\n2\t1\t12\t0\t0\t0\t2259\t35\t162\t58\t-1\t\n3\t1\t12\t1\t0\t0\t2259\t35\t162\t58\t-1\t\n4\t1\t12\t1\t1\t0\t2259\t35\t162\t58\t-1\t\n5\t1\t12\t1\t1\t1\t2259\t43\t59\t42\t67.618973\t25\n5\t1\t12\t1\t1\t2\t2328\t35\t93\t58\t0.000000\t\\wa\n'

In [15]:
data_list = list(map(lambda x : x.split('\t'),data.split('\n')))

for _ in data_list:
    print(_)

['level', 'page_num', 'block_num', 'par_num', 'line_num', 'word_num', 'left', 'top', 'width', 'height', 'conf', 'text']
['1', '1', '0', '0', '0', '0', '0', '0', '2483', '3510', '-1', '']
['2', '1', '1', '0', '0', '0', '313', '828', '551', '289', '-1', '']
['3', '1', '1', '1', '0', '0', '314', '828', '444', '71', '-1', '']
['4', '1', '1', '1', '1', '0', '314', '828', '444', '34', '-1', '']
['5', '1', '1', '1', '1', '1', '314', '829', '42', '27', '90.951714', 'De']
['5', '1', '1', '1', '1', '2', '371', '836', '137', '26', '90.951714', 'propere']
['5', '1', '1', '1', '1', '3', '522', '828', '62', '28', '91.361153', 'tuin']
['5', '1', '1', '1', '1', '4', '596', '829', '40', '33', '95.540474', 'by']
['5', '1', '1', '1', '1', '5', '647', '829', '111', '27', '96.319031', 'Stefan']
['4', '1', '1', '1', '2', '0', '314', '873', '141', '26', '-1', '']
['5', '1', '1', '1', '2', '1', '314', '873', '141', '26', '96.433662', 'Mertens']
['3', '1', '1', '2', '0', '0', '313', '916', '245', '27', '-1', '']
['4', '1', '1', '2', '1', '0', '313', '916', '245', '27', '-1', '']
['5', '1', '1', '2', '1', '1', '313', '916', '18', '27', '92.882111', '3']
['5', '1', '1', '2', '1', '2', '344', '916', '214', '26', '90.253540', 'Berkenstraat']
['3', '1', '1', '3', '0', '0', '314', '959', '246', '30', '-1', '']
['4', '1', '1', '3', '1', '0', '314', '959', '246', '30', '-1', '']
['5', '1', '1', '3', '1', '1', '314', '959', '154', '30', '92.133438', 'Aarschot,']
['5', '1', '1', '3', '1', '2', '482', '959', '78', '27', '96.226601', '3200']
['3', '1', '1', '4', '0', '0', '316', '1002', '101', '34', '-1', '']
['4', '1', '1', '4', '1', '0', '316', '1002', '101', '34', '-1', '']
['5', '1', '1', '4', '1', '1', '316', '1002', '101', '34', '84.573639', 'Belgié']
['3', '1', '1', '5', '0', '0', '314', '1045', '550', '72', '-1', '']
['4', '1', '1', '5', '1', '0', '315', '1045', '549', '34', '-1', '']
['5', '1', '1', '5', '1', '1', '315', '1046', '59', '26', '89.837425', 'info']
['5', '1', '1', '5', '1', '2', '381', '1045', '483', '34', '89.837425', '@deproperetuinbystefan.be']
['4', '1', '1', '5', '2', '0', '314', '1089', '388', '28', '-1', '']
['5', '1', '1', '5', '2', '1', '314', '1089', '158', '28', '90.967056', 'Telefoon:']
['5', '1', '1', '5', '2', '2', '485', '1089', '217', '28', '96.627693', '0474685499']
['2', '1', '2', '0', '0', '0', '316', '1243', '362', '258', '-1', '']
['3', '1', '2', '1', '0', '0', '317', '1243', '246', '34', '-1', '']
['4', '1', '2', '1', '1', '0', '317', '1243', '246', '34', '-1', '']
['5', '1', '2', '1', '1', '1', '317', '1243', '153', '34', '91.159515', 'Rekening']
['5', '1', '2', '1', '1', '2', '484', '1251', '79', '20', '96.736366', 'naar:']
['3', '1', '2', '2', '0', '0', '317', '1294', '56', '26', '-1', '']
['4', '1', '2', '2', '1', '0', '317', '1294', '56', '26', '-1', '']
['5', '1', '2', '2', '1', '1', '317', '1294', '56', '26', '56.324120', 'lise']
['3', '1', '2', '3', '0', '0', '316', '1337', '362', '116', '-1', '']
['4', '1', '2', '3', '1', '0', '317', '1337', '361', '27', '-1', '']
['5', '1', '2', '3', '1', '1', '317', '1337', '99', '27', '94.748993', 'Urban']
['5', '1', '2', '3', '1', '2', '429', '1337', '69', '26', '96.757950', 'Real']
['5', '1', '2', '3', '1', '3', '510', '1337', '106', '26', '96.412834', 'Estate']
['5', '1', '2', '3', '1', '4', '632', '1337', '46', '26', '96.702728', 'BV']
['4', '1', '2', '3', '2', '0', '316', '1380', '305', '33', '-1', '']
['5', '1', '2', '3', '2', '1', '316', '1380', '267', '33', '92.156784', 'Schippersstraat']
['5', '1', '2', '3', '2', '2', '593', '1380', '28', '26', '96.826851', '21']
['4', '1', '2', '3', '3', '0', '318', '1423', '224', '30', '-1', '']
['5', '1', '2', '3', '3', '1', '318', '1423', '130', '30', '95.472931', 'Hasselt,']
['5', '1', '2', '3', '3', '2', '461', '1423', '81', '27', '96.439163', '3500']
['3', '1', '2', '4', '0', '0', '319', '1466', '100', '35', '-1', '']
['4', '1', '2', '4', '1', '0', '319', '1466', '100', '35', '-1', '']
['5', '1', '2', '4', '1', '1', '319', '1466', '100', '35', '92.410736', 'Belgié']
['2', '1', '3', '0', '0', '0', '1569', '520', '603', '47', '-1', '']
['3', '1', '3', '1', '0', '0', '1569', '520', '603', '47', '-1', '']
['4', '1', '3', '1', '1', '0', '1569', '520', '603', '47', '-1', '']
['5', '1', '3', '1', '1', '1', '1569', '521', '285', '46', '91.072388', 'FACTUUR']
['5', '1', '3', '1', '1', '2', '1871', '520', '301', '47', '96.280464', '#0000042']
['2', '1', '4', '0', '0', '0', '1754', '629', '420', '87', '-1', '']
['3', '1', '4', '1', '0', '0', '1754', '629', '420', '87', '-1', '']
['4', '1', '4', '1', '1', '0', '1754', '629', '420', '34', '-1', '']
['5', '1', '4', '1', '1', '1', '1754', '629', '235', '34', '81.367065', 'Uitgiftedatum:']
['5', '1', '4', '1', '1', '2', '2002', '629', '34', '27', '96.154594', '25']
['5', '1', '4', '1', '1', '3', '2046', '629', '35', '33', '94.500038', 'jul']
['5', '1', '4', '1', '1', '4', '2094', '629', '80', '27', '96.840561', '2024']
['4', '1', '4', '1', '2', '0', '1778', '681', '396', '35', '-1', '']
['5', '1', '4', '1', '2', '1', '1778', '681', '209', '27', '91.233002', 'Vervaldatum:']
['5', '1', '4', '1', '2', '2', '2000', '682', '10', '26', '93.861023', '1']
['5', '1', '4', '1', '2', '3', '2025', '689', '55', '27', '93.861023', 'aug']
['5', '1', '4', '1', '2', '4', '2094', '681', '80', '27', '96.229507', '2024']
['2', '1', '5', '0', '0', '0', '1047', '1034', '455', '83', '-1', '']
['3', '1', '5', '1', '0', '0', '1047', '1034', '455', '83', '-1', '']
['4', '1', '5', '1', '1', '0', '1047', '1034', '394', '27', '-1', '']
['5', '1', '5', '1', '1', '1', '1047', '1034', '107', '27', '91.515526', 'Btw-id:']
['5', '1', '5', '1', '1', '2', '1169', '1034', '40', '27', '91.319206', 'BE']
['5', '1', '5', '1', '1', '3', '1220', '1034', '221', '27', '90.066360', '1005.429.249']
['4', '1', '5', '1', '2', '0', '1048', '1089', '454', '28', '-1', '']
['5', '1', '5', '1', '2', '1', '1048', '1090', '84', '27', '91.620941', 'IBAN:']
['5', '1', '5', '1', '2', '2', '1146', '1089', '83', '28', '84.999664', 'BEQ9']
['5', '1', '5', '1', '2', '3', '1243', '1089', '76', '28', '96.657074', '7310']
['5', '1', '5', '1', '2', '4', '1332', '1089', '80', '28', '96.511139', '5924']
['5', '1', '5', '1', '2', '5', '1424', '1089', '78', '28', '95.905128', '6157']
['2', '1', '6', '0', '0', '0', '1034', '1245', '360', '34', '-1', '']
['3', '1', '6', '1', '0', '0', '1034', '1245', '360', '34', '-1', '']
['4', '1', '6', '1', '1', '0', '1034', '1245', '360', '34', '-1', '']
['5', '1', '6', '1', '1', '1', '1034', '1245', '81', '27', '91.435432', 'Extra']
['5', '1', '6', '1', '1', '2', '1129', '1245', '265', '34', '63.689327', 'klantgegevens:']
['2', '1', '7', '0', '0', '0', '1033', '1294', '394', '72', '-1', '']
['3', '1', '7', '1', '0', '0', '1033', '1294', '394', '72', '-1', '']
['4', '1', '7', '1', '1', '0', '1033', '1294', '251', '33', '-1', '']
['5', '1', '7', '1', '1', '1', '1033', '1294', '251', '33', '69.966187', 'iise@soreal.be']
['4', '1', '7', '1', '2', '0', '1035', '1337', '392', '29', '-1', '']
['5', '1', '7', '1', '2', '1', '1035', '1338', '107', '26', '91.721191', 'Btw-id:']
['5', '1', '7', '1', '2', '2', '1156', '1337', '122', '29', '39.804817', 'BE0881']
['5', '1', '7', '1', '2', '3', '1294', '1338', '59', '28', '96.911263', '675']
['5', '1', '7', '1', '2', '4', '1365', '1337', '62', '27', '96.155151', '560']
['2', '1', '8', '0', '0', '0', '318', '1673', '1347', '57', '-1', '']
['3', '1', '8', '1', '0', '0', '318', '1673', '1347', '57', '-1', '']
['4', '1', '8', '1', '1', '0', '318', '1673', '1347', '57', '-1', '']
['5', '1', '8', '1', '1', '1', '318', '1673', '424', '47', '91.987717', 'Tuinonderhoud']
['5', '1', '8', '1', '1', '2', '761', '1686', '72', '44', '96.930931', 'op']
['5', '1', '8', '1', '1', '3', '850', '1674', '66', '46', '95.680527', '23']
['5', '1', '8', '1', '1', '4', '930', '1673', '78', '57', '93.276726', 'juli']
['5', '1', '8', '1', '1', '5', '1026', '1674', '144', '46', '93.276726', '2024']
['5', '1', '8', '1', '1', '6', '1190', '1674', '153', '53', '90.385475', '(BTW']
['5', '1', '8', '1', '1', '7', '1361', '1673', '304', '53', '90.385475', 'VERLEGD)']
['2', '1', '9', '0', '0', '0', '323', '1806', '633', '520', '-1', '']
['3', '1', '9', '1', '0', '0', '323', '1806', '633', '515', '-1', '']
['4', '1', '9', '1', '1', '0', '323', '1806', '633', '32', '-1', '']
['5', '1', '9', '1', '1', '1', '323', '1807', '157', '31', '96.827690', 'Product']
['5', '1', '9', '1', '1', '2', '492', '1807', '39', '31', '93.285110', 'of']
['5', '1', '9', '1', '1', '3', '543', '1806', '125', '32', '91.161850', 'dienst']
['5', '1', '9', '1', '1', '4', '823', '1807', '133', '31', '85.591583', 'Aantal']
['4', '1', '9', '1', '2', '0', '323', '1947', '554', '49', '-1', '']
['5', '1', '9', '1', '2', '1', '323', '1947', '175', '49', '91.227196', 'Werkuren']
['5', '1', '9', '1', '2', '2', '825', '1951', '52', '31', '96.705444', '3.5']
['4', '1', '9', '1', '3', '0', '326', '2116', '514', '32', '-1', '']
['5', '1', '9', '1', '3', '1', '326', '2116', '304', '32', '92.097626', 'Materiaalkosten']
['5', '1', '9', '1', '3', '2', '827', '2116', '13', '30', '96.900848', '1']
['4', '1', '9', '1', '4', '0', '327', '2276', '545', '50', '-1', '']
['5', '1', '9', '1', '4', '1', '327', '2276', '401', '50', '91.353088', 'Kilometervergoeding']
['5', '1', '9', '1', '4', '2', '827', '2281', '45', '32', '97.001335', '26']
['2', '1', '10', '0', '0', '0', '1174', '1802', '1006', '351', '-1', '']
['3', '1', '10', '1', '0', '0', '1174', '1802', '1006', '351', '-1', '']
['4', '1', '10', '1', '1', '0', '1176', '1802', '1001', '49', '-1', '']
['5', '1', '10', '1', '1', '1', '1176', '1802', '83', '49', '96.882454', 'Prijs']
['5', '1', '10', '1', '1', '2', '1523', '1806', '189', '40', '92.118950', 'Belasting']
['5', '1', '10', '1', '1', '3', '1985', '1806', '192', '39', '91.748703', 'Lijntotaal']
['4', '1', '10', '1', '2', '0', '1174', '1950', '1005', '39', '-1', '']
['5', '1', '10', '1', '2', '1', '1174', '1951', '24', '32', '93.305161', '€']
['5', '1', '10', '1', '2', '2', '1209', '1951', '100', '38', '96.588821', '37,20']
['5', '1', '10', '1', '2', '3', '2018', '1950', '24', '32', '93.283432', '€']
['5', '1', '10', '1', '2', '4', '2055', '1950', '124', '38', '96.747849', '130,20']
['4', '1', '10', '1', '3', '0', '1175', '2115', '1005', '38', '-1', '']
['5', '1', '10', '1', '3', '1', '1175', '2116', '116', '37', '92.387466', '€5,00']
['5', '1', '10', '1', '3', '2', '2063', '2115', '23', '31', '93.284935', '€']
['5', '1', '10', '1', '3', '3', '2098', '2115', '82', '37', '96.129280', '5,00']
['2', '1', '11', '0', '0', '0', '1176', '2280', '1005', '38', '-1', '']
['3', '1', '11', '1', '0', '0', '1176', '2280', '1005', '38', '-1', '']
['4', '1', '11', '1', '1', '0', '1176', '2280', '1005', '38', '-1', '']
['5', '1', '11', '1', '1', '1', '1176', '2281', '116', '37', '91.596008', '€0,20']
['5', '1', '11', '1', '1', '2', '2067', '2280', '24', '31', '93.295303', '€']
['5', '1', '11', '1', '1', '3', '2102', '2280', '79', '38', '96.072311', '5,20']
['2', '1', '12', '0', '0', '0', '2259', '35', '162', '58', '-1', '']
['3', '1', '12', '1', '0', '0', '2259', '35', '162', '58', '-1', '']
['4', '1', '12', '1', '1', '0', '2259', '35', '162', '58', '-1', '']
['5', '1', '12', '1', '1', '1', '2259', '43', '59', '42', '67.618973', '25']
['5', '1', '12', '1', '1', '2', '2328', '35', '93', '58', '0.000000', '\\wa']
['']

In [16]:
from pandas import DataFrame

df = DataFrame(data_list[1:], columns=data_list[0])
df

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,2483,3510,-1,
1,2,1,1,0,0,0,313,828,551,289,-1,
2,3,1,1,1,0,0,314,828,444,71,-1,
3,4,1,1,1,1,0,314,828,444,34,-1,
4,5,1,1,1,1,1,314,829,42,27,90.951714,De
...,...,...,...,...,...,...,...,...,...,...,...,...
143,3,1,12,1,0,0,2259,35,162,58,-1,
144,4,1,12,1,1,0,2259,35,162,58,-1,
145,5,1,12,1,1,1,2259,43,59,42,67.618973,25
146,5,1,12,1,1,2,2328,35,93,58,0.000000,\wa
147,,None,None,None,None,None,None,None,None,None,None,None

In [17]:
df = df.dropna()

In [18]:
col_int = ['level', 'page_num', 'block_num','par_num', 'line_num', 'word_num', 'left', 'top', 'width','height','conf']

df[col_int] = df[col_int].astype(float, copy=True).astype(int)

C:\Users\Bindra\AppData\Local\Temp\ipykernel_20412\3813526581.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col_int] = df[col_int].astype(float, copy=True).astype(int)

In [20]:
df[['level', 'left', 'top', 'width', 'height', 'conf']]

     level  left  top  width  height  conf
0        1     0    0   2483    3510    -1
1        2   313  828    551     289    -1
2        3   314  828    444      71    -1
3        4   314  828    444      34    -1
4        5   314  829     42      27    90
..     ...   ...  ...    ...     ...   ...
142      2  2259   35    162      58    -1
143      3  2259   35    162      58    -1
144      4  2259   35    162      58    -1
145      5  2259   43     59      42    67
146      5  2328   35     93      58     0

[147 rows x 6 columns]

In [24]:
for l,x,y,w,h,c in df[['level', 'left', 'top', 'width', 'height', 'conf']].values:
    print(l,x,y,w,h,c)

1 0 0 2483 3510 -1
2 313 828 551 289 -1
3 314 828 444 71 -1
4 314 828 444 34 -1
5 314 829 42 27 90
5 371 836 137 26 90
5 522 828 62 28 91
5 596 829 40 33 95
5 647 829 111 27 96
4 314 873 141 26 -1
5 314 873 141 26 96
3 313 916 245 27 -1
4 313 916 245 27 -1
5 313 916 18 27 92
5 344 916 214 26 90
3 314 959 246 30 -1
4 314 959 246 30 -1
5 314 959 154 30 92
5 482 959 78 27 96
3 316 1002 101 34 -1
4 316 1002 101 34 -1
5 316 1002 101 34 84
3 314 1045 550 72 -1
4 315 1045 549 34 -1
5 315 1046 59 26 89
5 381 1045 483 34 89
4 314 1089 388 28 -1
5 314 1089 158 28 90
5 485 1089 217 28 96
2 316 1243 362 258 -1
3 317 1243 246 34 -1
4 317 1243 246 34 -1
5 317 1243 153 34 91
5 484 1251 79 20 96
3 317 1294 56 26 -1
4 317 1294 56 26 -1
5 317 1294 56 26 56
3 316 1337 362 116 -1
4 317 1337 361 27 -1
5 317 1337 99 27 94
5 429 1337 69 26 96
5 510 1337 106 26 96
5 632 1337 46 26 96
4 316 1380 305 33 -1
5 316 1380 267 33 92
5 593 1380 28 26 96
4 318 1423 224 30 -1
5 318 1423 130 30 95
5 461 1423 81 27 96
3 319 1466 100 35 -1
4 319 1466 100 35 -1
5 319 1466 100 35 92
2 1569 520 603 47 -1
3 1569 520 603 47 -1
4 1569 520 603 47 -1
5 1569 521 285 46 91
5 1871 520 301 47 96
2 1754 629 420 87 -1
3 1754 629 420 87 -1
4 1754 629 420 34 -1
5 1754 629 235 34 81
5 2002 629 34 27 96
5 2046 629 35 33 94
5 2094 629 80 27 96
4 1778 681 396 35 -1
5 1778 681 209 27 91
5 2000 682 10 26 93
5 2025 689 55 27 93
5 2094 681 80 27 96
2 1047 1034 455 83 -1
3 1047 1034 455 83 -1
4 1047 1034 394 27 -1
5 1047 1034 107 27 91
5 1169 1034 40 27 91
5 1220 1034 221 27 90
4 1048 1089 454 28 -1
5 1048 1090 84 27 91
5 1146 1089 83 28 84
5 1243 1089 76 28 96
5 1332 1089 80 28 96
5 1424 1089 78 28 95
2 1034 1245 360 34 -1
3 1034 1245 360 34 -1
4 1034 1245 360 34 -1
5 1034 1245 81 27 91
5 1129 1245 265 34 63
2 1033 1294 394 72 -1
3 1033 1294 394 72 -1
4 1033 1294 251 33 -1
5 1033 1294 251 33 69
4 1035 1337 392 29 -1
5 1035 1338 107 26 91
5 1156 1337 122 29 39
5 1294 1338 59 28 96
5 1365 1337 62 27 96
2 318 1673 1347 57 -1
3 318 1673 1347 57 -1
4 318 1673 1347 57 -1
5 318 1673 424 47 91
5 761 1686 72 44 96
5 850 1674 66 46 95
5 930 1673 78 57 93
5 1026 1674 144 46 93
5 1190 1674 153 53 90
5 1361 1673 304 53 90
2 323 1806 633 520 -1
3 323 1806 633 515 -1
4 323 1806 633 32 -1
5 323 1807 157 31 96
5 492 1807 39 31 93
5 543 1806 125 32 91
5 823 1807 133 31 85
4 323 1947 554 49 -1
5 323 1947 175 49 91
5 825 1951 52 31 96
4 326 2116 514 32 -1
5 326 2116 304 32 92
5 827 2116 13 30 96
4 327 2276 545 50 -1
5 327 2276 401 50 91
5 827 2281 45 32 97
2 1174 1802 1006 351 -1
3 1174 1802 1006 351 -1
4 1176 1802 1001 49 -1
5 1176 1802 83 49 96
5 1523 1806 189 40 92
5 1985 1806 192 39 91
4 1174 1950 1005 39 -1
5 1174 1951 24 32 93
5 1209 1951 100 38 96
5 2018 1950 24 32 93
5 2055 1950 124 38 96
4 1175 2115 1005 38 -1
5 1175 2116 116 37 92
5 2063 2115 23 31 93
5 2098 2115 82 37 96
2 1176 2280 1005 38 -1
3 1176 2280 1005 38 -1
4 1176 2280 1005 38 -1
5 1176 2281 116 37 91
5 2067 2280 24 31 93
5 2102 2280 79 38 96
2 2259 35 162 58 -1
3 2259 35 162 58 -1
4 2259 35 162 58 -1
5 2259 43 59 42 67
5 2328 35 93 58 0

In [30]:
image = inv_img.copy()

In [34]:
from cv2 import rectangle
from cv2 import putText
from cv2 import FONT_HERSHEY_PLAIN
from cv2 import resize

In [42]:

level ='word'

for l, x, y, w, h, c, txt in df[['level', 'left', 'top', 'width', 'height', 'conf','text']].values:
    print(l,x,y,w,h,c)
    
    if level == 'page':
        if l == 1:
            rectangle(img=image, pt1=(x,y),pt2=(x+w,y+h), color=(0,0,0),thickness=2)
        else:
            continue
    elif level == 'block':
        if l == 2:
            rectangle(img=image, pt1=(x,y),pt2=(x+w,y+h), color=(255,0,0),thickness=2)
        else:
             continue
    elif level == 'para':
        if l == 3:
            rectangle(img=image, pt1=(x,y),pt2=(x+w,y+h), color=(0,255,0),thickness=2)
        else:
             continue
    elif level == 'line':
        if l == 4:
            rectangle(img=image, pt1=(x,y),pt2=(x+w,y+h), color=(0,0,255),thickness=2)
        else:
             continue
    elif level == 'word':
        if l == 5:
            rectangle(img=image, pt1=(x,y),pt2=(x+w,y+h), color=(0,255,255),thickness=2)
            putText(image,txt,(x,y),FONT_HERSHEY_PLAIN,2,(255, 0, 0),2)
        else:
             continue
imgg = resize(image, (1000, 1100))
imshow("Bounding Box", imgg)
waitKey()
destroyAllWindows()

1 0 0 2483 3510 -1
2 313 828 551 289 -1
3 314 828 444 71 -1
4 314 828 444 34 -1
5 314 829 42 27 90
5 371 836 137 26 90
5 522 828 62 28 91
5 596 829 40 33 95
5 647 829 111 27 96
4 314 873 141 26 -1
5 314 873 141 26 96
3 313 916 245 27 -1
4 313 916 245 27 -1
5 313 916 18 27 92
5 344 916 214 26 90
3 314 959 246 30 -1
4 314 959 246 30 -1
5 314 959 154 30 92
5 482 959 78 27 96
3 316 1002 101 34 -1
4 316 1002 101 34 -1
5 316 1002 101 34 84
3 314 1045 550 72 -1
4 315 1045 549 34 -1
5 315 1046 59 26 89
5 381 1045 483 34 89
4 314 1089 388 28 -1
5 314 1089 158 28 90
5 485 1089 217 28 96
2 316 1243 362 258 -1
3 317 1243 246 34 -1
4 317 1243 246 34 -1
5 317 1243 153 34 91
5 484 1251 79 20 96
3 317 1294 56 26 -1
4 317 1294 56 26 -1
5 317 1294 56 26 56
3 316 1337 362 116 -1
4 317 1337 361 27 -1
5 317 1337 99 27 94
5 429 1337 69 26 96
5 510 1337 106 26 96
5 632 1337 46 26 96
4 316 1380 305 33 -1
5 316 1380 267 33 92
5 593 1380 28 26 96
4 318 1423 224 30 -1
5 318 1423 130 30 95
5 461 1423 81 27 96
3 319 1466 100 35 -1
4 319 1466 100 35 -1
5 319 1466 100 35 92
2 1569 520 603 47 -1
3 1569 520 603 47 -1
4 1569 520 603 47 -1
5 1569 521 285 46 91
5 1871 520 301 47 96
2 1754 629 420 87 -1
3 1754 629 420 87 -1
4 1754 629 420 34 -1
5 1754 629 235 34 81
5 2002 629 34 27 96
5 2046 629 35 33 94
5 2094 629 80 27 96
4 1778 681 396 35 -1
5 1778 681 209 27 91
5 2000 682 10 26 93
5 2025 689 55 27 93
5 2094 681 80 27 96
2 1047 1034 455 83 -1
3 1047 1034 455 83 -1
4 1047 1034 394 27 -1
5 1047 1034 107 27 91
5 1169 1034 40 27 91
5 1220 1034 221 27 90
4 1048 1089 454 28 -1
5 1048 1090 84 27 91
5 1146 1089 83 28 84
5 1243 1089 76 28 96
5 1332 1089 80 28 96
5 1424 1089 78 28 95
2 1034 1245 360 34 -1
3 1034 1245 360 34 -1
4 1034 1245 360 34 -1
5 1034 1245 81 27 91
5 1129 1245 265 34 63
2 1033 1294 394 72 -1
3 1033 1294 394 72 -1
4 1033 1294 251 33 -1
5 1033 1294 251 33 69
4 1035 1337 392 29 -1
5 1035 1338 107 26 91
5 1156 1337 122 29 39
5 1294 1338 59 28 96
5 1365 1337 62 27 96
2 318 1673 1347 57 -1
3 318 1673 1347 57 -1
4 318 1673 1347 57 -1
5 318 1673 424 47 91
5 761 1686 72 44 96
5 850 1674 66 46 95
5 930 1673 78 57 93
5 1026 1674 144 46 93
5 1190 1674 153 53 90
5 1361 1673 304 53 90
2 323 1806 633 520 -1
3 323 1806 633 515 -1
4 323 1806 633 32 -1
5 323 1807 157 31 96
5 492 1807 39 31 93
5 543 1806 125 32 91
5 823 1807 133 31 85
4 323 1947 554 49 -1
5 323 1947 175 49 91
5 825 1951 52 31 96
4 326 2116 514 32 -1
5 326 2116 304 32 92
5 827 2116 13 30 96
4 327 2276 545 50 -1
5 327 2276 401 50 91
5 827 2281 45 32 97
2 1174 1802 1006 351 -1
3 1174 1802 1006 351 -1
4 1176 1802 1001 49 -1
5 1176 1802 83 49 96
5 1523 1806 189 40 92
5 1985 1806 192 39 91
4 1174 1950 1005 39 -1
5 1174 1951 24 32 93
5 1209 1951 100 38 96
5 2018 1950 24 32 93
5 2055 1950 124 38 96
4 1175 2115 1005 38 -1
5 1175 2116 116 37 92
5 2063 2115 23 31 93
5 2098 2115 82 37 96
2 1176 2280 1005 38 -1
3 1176 2280 1005 38 -1
4 1176 2280 1005 38 -1
5 1176 2281 116 37 91
5 2067 2280 24 31 93
5 2102 2280 79 38 96
2 2259 35 162 58 -1
3 2259 35 162 58 -1
4 2259 35 162 58 -1
5 2259 43 59 42 67
5 2328 35 93 58 0