In [4]:
import cv2
import re
import string
import spacy
import pytesseract

import numpy as np
import pandas as pd

from glob import glob
from string import whitespace

In [5]:


def clean_text(txt):
    white_space = whitespace
    punch = '!"#$%&\'()*+,:;<=>?[\\]^_`{|}~'
    
    table_white_space = str.maketrans('','', white_space)
    table_puncuation = str.maketrans('','',punch)

    text = str(txt)
    text = text.lower()

    remove_whitespace = text.translate(table_white_space)
    remove_punctation = remove_whitespace.translate(table_puncuation)

    return str(remove_punctation)

#### Need for step to complete 

1. Load Image
2. Extract data using Pytessract
3. convert dat into content
4. get predicition for NER model

In [6]:
### Load NER model
model_ner = spacy.load('./output/model-best/')
model_ner

In [7]:
## Load Image
# image = cv2.imread('./BusinessCardData/Selected/006.jpeg')
image = cv2.imread('./data/Pradeep.jpeg')

# cv2.imshow("Businesscard", image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [8]:
# Extract data using Pytesseract
test_data = pytesseract.image_to_data(image)
test_data

'level\tpage_num\tblock_num\tpar_num\tline_num\tword_num\tleft\ttop\twidth\theight\tconf\ttext\n1\t1\t0\t0\t0\t0\t0\t0\t1024\t594\t-1\t\n2\t1\t1\t0\t0\t0\t524\t41\t407\t71\t-1\t\n3\t1\t1\t1\t0\t0\t39\t41\t892\t93\t-1\t\n4\t1\t1\t1\t1\t0\t654\t41\t277\t29\t-1\t\n5\t1\t1\t1\t1\t1\t654\t42\t80\t27\t88.081161\tMob.:\n5\t1\t1\t1\t1\t2\t747\t41\t184\t29\t96.767883\t9289548853\n4\t1\t1\t1\t2\t0\t524\t81\t404\t31\t-1\t\n5\t1\t1\t1\t2\t1\t524\t82\t81\t25\t93.044182\tE-mail\n5\t1\t1\t1\t2\t2\t616\t89\t5\t17\t91.642731\t:\n5\t1\t1\t1\t2\t3\t632\t81\t296\t31\t84.705475\tpkvksk2010@yahoo.in\n2\t1\t2\t0\t0\t0\t292\t237\t383\t43\t-1\t\n3\t1\t2\t1\t0\t0\t292\t237\t383\t43\t-1\t\n4\t1\t2\t1\t1\t0\t292\t237\t383\t43\t-1\t\n5\t1\t2\t1\t1\t1\t292\t237\t205\t43\t96.698212\tPRADEEP\n5\t1\t2\t1\t1\t2\t512\t245\t163\t33\t96.270096\tKUMAR\n2\t1\t3\t0\t0\t0\t348\t292\t267\t31\t-1\t\n3\t1\t3\t1\t0\t0\t348\t292\t267\t31\t-1\t\n4\t1\t3\t1\t1\t0\t348\t292\t267\t31\t-1\t\n5\t1\t3\t1\t1\t1\t348\t292\t142\t31\t96.261925\tInsurance\n5\t1\t3\t1\t1\t2\t498\t293\t117\t24\t96.827217\tAdvisor\n2\t1\t4\t0\t0\t0\t39\t461\t880\t46\t-1\t\n3\t1\t4\t1\t0\t0\t39\t461\t880\t46\t-1\t\n4\t1\t4\t1\t1\t0\t39\t461\t880\t46\t-1\t\n5\t1\t4\t1\t1\t1\t39\t461\t88\t37\t96.272491\tLIFE\n5\t1\t4\t1\t1\t2\t142\t461\t247\t46\t96.265411\tINSURANCE\n5\t1\t4\t1\t1\t3\t404\t464\t315\t38\t96.668419\tCORPORATION\n5\t1\t4\t1\t1\t4\t735\t467\t57\t36\t95.995728\tOF\n5\t1\t4\t1\t1\t5\t807\t468\t112\t34\t96.640053\tINDIA\n2\t1\t5\t0\t0\t0\t43\t516\t872\t28\t-1\t\n3\t1\t5\t1\t0\t0\t43\t516\t872\t28\t-1\t\n4\t1\t5\t1\t1\t0\t43\t516\t872\t28\t-1\t\n5\t1\t5\t1\t1\t1\t43\t516\t91\t23\t96.851410\tBranch\n5\t1\t5\t1\t1\t2\t145\t516\t66\t22\t93.299141\tUnit\n5\t1\t5\t1\t1\t3\t203\t512\t14\t38\t92.454399\t:\n5\t1\t5\t1\t1\t4\t224\t516\t54\t26\t91.143379\t11A,\n5\t1\t5\t1\t1\t5\t286\t517\t94\t26\t91.812805\tA-3/24,\n5\t1\t5\t1\t1\t6\t392\t517\t30\t23\t96.720245\tIst\n5\t1\t5\t1\t1\t7\t432\t518\t70\t26\t93.279152\tFloor,\n5\t1\t5\t1\t1\t8\t514\t519\t78\t22\t93.127548\tJanak\n5\t1\t5\t1\t1\t9\t604\t520\t56\t24\t96.819962\tPuri,\n5\t1\t5\t1\t1\t10\t674\t521\t58\t21\t93.296158\tNew\n5\t1\t5\t1\t1\t11\t743\t521\t172\t21\t88.683929\tDelhi-110058\n2\t1\t6\t0\t0\t0\t0\t580\t1024\t14\t-1\t\n3\t1\t6\t1\t0\t0\t0\t580\t1024\t14\t-1\t\n4\t1\t6\t1\t1\t0\t0\t580\t1024\t14\t-1\t\n5\t1\t6\t1\t1\t1\t0\t580\t1024\t14\t95.000000\t \n'

In [9]:
# Convert into data frame
test_list = list(map(lambda x:x.split('\t'), test_data.split('\n')))

df = pd.DataFrame(test_list[1:], columns=test_list[0])
df

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,1024,594,-1,
1,2,1,1,0,0,0,524,41,407,71,-1,
2,3,1,1,1,0,0,39,41,892,93,-1,
3,4,1,1,1,1,0,654,41,277,29,-1,
4,5,1,1,1,1,1,654,42,80,27,88.081161,Mob.:
5,5,1,1,1,1,2,747,41,184,29,96.767883,9289548853
6,4,1,1,1,2,0,524,81,404,31,-1,
7,5,1,1,1,2,1,524,82,81,25,93.044182,E-mail
8,5,1,1,1,2,2,616,89,5,17,91.642731,:
9,5,1,1,1,2,3,632,81,296,31,84.705475,pkvksk2010@yahoo.in
10,2,1,2,0,0,0,292,237,383,43,-1,
11,3,1,2,1,0,0,292,237,383,43,-1,
12,4,1,2,1,1,0,292,237,383,43,-1,
13,5,1,2,1,1,1,292,237,205,43,96.698212,PRADEEP
14,5,1,2,1,1,2,512,245,163,33,96.270096,KUMAR
15,2,1,3,0,0,0,348,292,267,31,-1,
16,3,1,3,1,0,0,348,292,267,31,-1,
17,4,1,3,1,1,0,348,292,267,31,-1,
18,5,1,3,1,1,1,348,292,142,31,96.261925,Insurance
19,5,1,3,1,1,2,498,293,117,24,96.827217,Advisor
20,2,1,4,0,0,0,39,461,880,46,-1,
21,3,1,4,1,0,0,39,461,880,46,-1,
22,4,1,4,1,1,0,39,461,880,46,-1,
23,5,1,4,1,1,1,39,461,88,37,96.272491,LIFE
24,5,1,4,1,1,2,142,461,247,46,96.265411,INSURANCE
25,5,1,4,1,1,3,404,464,315,38,96.668419,CORPORATION
26,5,1,4,1,1,4,735,467,57,36,95.995728,OF
27,5,1,4,1,1,5,807,468,112,34,96.640053,INDIA
28,2,1,5,0,0,0,43,516,872,28,-1,
29,3,1,5,1,0,0,43,516,872,28,-1,
30,4,1,5,1,1,0,43,516,872,28,-1,
31,5,1,5,1,1,1,43,516,91,23,96.851410,Branch
32,5,1,5,1,1,2,145,516,66,22,93.299141,Unit
33,5,1,5,1,1,3,203,512,14,38,92.454399,:
34,5,1,5,1,1,4,224,516,54,26,91.143379,"11A,"
35,5,1,5,1,1,5,286,517,94,26,91.812805,"A-3/24,"
36,5,1,5,1,1,6,392,517,30,23,96.720245,Ist
37,5,1,5,1,1,7,432,518,70,26,93.279152,"Floor,"
38,5,1,5,1,1,8,514,519,78,22,93.127548,Janak
39,5,1,5,1,1,9,604,520,56,24,96.819962,"Puri,"
40,5,1,5,1,1,10,674,521,58,21,93.296158,New
41,5,1,5,1,1,11,743,521,172,21,88.683929,Delhi-110058
42,2,1,6,0,0,0,0,580,1024,14,-1,
43,3,1,6,1,0,0,0,580,1024,14,-1,
44,4,1,6,1,1,0,0,580,1024,14,-1,
45,5,1,6,1,1,1,0,580,1024,14,95.000000,
46,,None,None,None,None,None,None,None,None,None,None,None

In [10]:
df = df.dropna()

In [11]:
df['text'] = df['text'].apply(clean_text)
df['text']

C:\Users\Bindra\AppData\Local\Temp\ipykernel_3524\64179834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['text'].apply(clean_text)

0
1
2
3
4                    mob.
5              9289548853
6
7                  e-mail
8
9     pkvksk2010@yahoo.in
10
11
12
13                pradeep
14                  kumar
15
16
17
18              insurance
19                advisor
20
21
22
23                   life
24              insurance
25            corporation
26                     of
27                  india
28
29
30
31                 branch
32                   unit
33
34                    11a
35                 a-3/24
36                    ist
37                  floor
38                  janak
39                   puri
40                    new
41           delhi-110058
42
43
44
45
Name: text, dtype: object

In [12]:
# Covert data into content
df_clean = df.query("text != '' ")

content = " ".join([w for w in df_clean['text']])
print(content)

mob. 9289548853 e-mail pkvksk2010@yahoo.in pradeep kumar insurance advisor life insurance corporation of india branch unit 11a a-3/24 ist floor janak puri new delhi-110058

In [13]:
# Get prediction from NER model
doc = model_ner(content)

In [14]:
# spacy displacy
from spacy import displacy

In [15]:
displacy.serve(doc, style = 'ent')

C:\Users\Bindra\Desktop\TODO\python_data_science\Spacy_entity\entity\Lib\site-packages\spacy\displacy\__init__.py:106: UserWarning: [W011] It looks like you're calling displacy.serve from within a Jupyter notebook or a similar environment. This likely means you're already running a local web server, so there's no need to make displaCy start another one. Instead, you should be able to replace displacy.serve with displacy.render to show the visualization.
  warnings.warn(Warnings.W011)

Using the 'ent' visualizer
Serving on http://0.0.0.0:5000 ...

Shutting down server on port 5000.

In [16]:
displacy.render(doc, style = 'ent')

#### Tagging

In [17]:
doc.to_json()

{'text': 'mob. 9289548853 e-mail pkvksk2010@yahoo.in pradeep kumar insurance advisor life insurance corporation of india branch unit 11a a-3/24 ist floor janak puri new delhi-110058',
 'ents': [{'start': 5, 'end': 15, 'label': 'B-PHONE'},
  {'start': 23, 'end': 42, 'label': 'B-EMAIL'},
  {'start': 43, 'end': 50, 'label': 'B-NAME'},
  {'start': 51, 'end': 56, 'label': 'I-NAME'},
  {'start': 57, 'end': 66, 'label': 'B-DES'},
  {'start': 67, 'end': 74, 'label': 'I-DES'},
  {'start': 75, 'end': 79, 'label': 'B-ORG'},
  {'start': 80, 'end': 89, 'label': 'I-ORG'},
  {'start': 90, 'end': 101, 'label': 'I-ORG'},
  {'start': 102, 'end': 104, 'label': 'I-ORG'},
  {'start': 105, 'end': 110, 'label': 'I-ORG'},
  {'start': 144, 'end': 149, 'label': 'B-NAME'}],
 'tokens': [{'id': 0, 'start': 0, 'end': 3},
  {'id': 1, 'start': 3, 'end': 4},
  {'id': 2, 'start': 5, 'end': 15},
  {'id': 3, 'start': 16, 'end': 17},
  {'id': 4, 'start': 17, 'end': 18},
  {'id': 5, 'start': 18, 'end': 22},
  {'id': 6, 'start': 23, 'end': 42},
  {'id': 7, 'start': 43, 'end': 50},
  {'id': 8, 'start': 51, 'end': 56},
  {'id': 9, 'start': 57, 'end': 66},
  {'id': 10, 'start': 67, 'end': 74},
  {'id': 11, 'start': 75, 'end': 79},
  {'id': 12, 'start': 80, 'end': 89},
  {'id': 13, 'start': 90, 'end': 101},
  {'id': 14, 'start': 102, 'end': 104},
  {'id': 15, 'start': 105, 'end': 110},
  {'id': 16, 'start': 111, 'end': 117},
  {'id': 17, 'start': 118, 'end': 122},
  {'id': 18, 'start': 123, 'end': 126},
  {'id': 19, 'start': 127, 'end': 133},
  {'id': 20, 'start': 134, 'end': 137},
  {'id': 21, 'start': 138, 'end': 143},
  {'id': 22, 'start': 144, 'end': 149},
  {'id': 23, 'start': 150, 'end': 154},
  {'id': 24, 'start': 155, 'end': 158},
  {'id': 25, 'start': 159, 'end': 171}]}

In [20]:
doc_json = doc.to_json()
doc_json.keys()

dict_keys(['text', 'ents', 'tokens'])

In [21]:
doc_json['text']

'mob. 9289548853 e-mail pkvksk2010@yahoo.in pradeep kumar insurance advisor life insurance corporation of india branch unit 11a a-3/24 ist floor janak puri new delhi-110058'

In [22]:
doc_json['ents']

[{'start': 5, 'end': 15, 'label': 'B-PHONE'},
 {'start': 23, 'end': 42, 'label': 'B-EMAIL'},
 {'start': 43, 'end': 50, 'label': 'B-NAME'},
 {'start': 51, 'end': 56, 'label': 'I-NAME'},
 {'start': 57, 'end': 66, 'label': 'B-DES'},
 {'start': 67, 'end': 74, 'label': 'I-DES'},
 {'start': 75, 'end': 79, 'label': 'B-ORG'},
 {'start': 80, 'end': 89, 'label': 'I-ORG'},
 {'start': 90, 'end': 101, 'label': 'I-ORG'},
 {'start': 102, 'end': 104, 'label': 'I-ORG'},
 {'start': 105, 'end': 110, 'label': 'I-ORG'},
 {'start': 144, 'end': 149, 'label': 'B-NAME'}]

In [23]:
doc_json['tokens']

[{'id': 0, 'start': 0, 'end': 3},
 {'id': 1, 'start': 3, 'end': 4},
 {'id': 2, 'start': 5, 'end': 15},
 {'id': 3, 'start': 16, 'end': 17},
 {'id': 4, 'start': 17, 'end': 18},
 {'id': 5, 'start': 18, 'end': 22},
 {'id': 6, 'start': 23, 'end': 42},
 {'id': 7, 'start': 43, 'end': 50},
 {'id': 8, 'start': 51, 'end': 56},
 {'id': 9, 'start': 57, 'end': 66},
 {'id': 10, 'start': 67, 'end': 74},
 {'id': 11, 'start': 75, 'end': 79},
 {'id': 12, 'start': 80, 'end': 89},
 {'id': 13, 'start': 90, 'end': 101},
 {'id': 14, 'start': 102, 'end': 104},
 {'id': 15, 'start': 105, 'end': 110},
 {'id': 16, 'start': 111, 'end': 117},
 {'id': 17, 'start': 118, 'end': 122},
 {'id': 18, 'start': 123, 'end': 126},
 {'id': 19, 'start': 127, 'end': 133},
 {'id': 20, 'start': 134, 'end': 137},
 {'id': 21, 'start': 138, 'end': 143},
 {'id': 22, 'start': 144, 'end': 149},
 {'id': 23, 'start': 150, 'end': 154},
 {'id': 24, 'start': 155, 'end': 158},
 {'id': 25, 'start': 159, 'end': 171}]

In [24]:
doc_text = doc_json['text']

In [26]:
df_token = pd.DataFrame(doc_json['tokens'])
df_token.head()

   id  start  end
0   0      0    3
1   1      3    4
2   2      5   15
3   3     16   17
4   4     17   18