In [ ]:
Assing 1,0

In [6]:
import pandas as pd

df = pd.read_csv("homeprices.csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

So in our dataframe category column is town

In [3]:
dummies = pd.get_dummies(df.town)
dummies

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

### concatinate dummies to orignal cloumn

In [4]:
merged = pd.concat([df,dummies],axis='columns')
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

we need orignal text categorcal column town and also drop one dummies variable
- multicorinality coause of dummy variable trap

In [5]:
final = merged.drop(['town','west windsor'], axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

### Create a linear model

In [6]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

NOW Give X,Y

In [7]:
X = final.drop('price', axis='columns') # price is depenent variable
X

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [9]:
Y= final.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [10]:
model.fit(X,Y)

LinearRegression()

In [13]:
model.predict([[3200,1,0]])

C:\Users\Bindra\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([615848.20468716])

In [15]:
model.predict([[3500,0,0]])

C:\Users\Bindra\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([693931.41259943])

In [16]:
model.score(X,Y)

0.9573929037221871

SKlearn one hot encoder

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [8]:
X = dfle[['town', 'area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [9]:
Y = dfle.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [10]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(categorical_features=[0])

X = ohe.fit_transform(X).toarray()
X = X[:,1:]
X

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'categorical_features'

In [16]:

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Initialize the OneHotEncoder
ohe = OneHotEncoder(drop='first')  # drop='first' drops the first column of the one-hot encoded result

# Apply OneHotEncoder to the first column (index 0) using ColumnTransformer
transformer = ColumnTransformer(
    transformers=[('cat', ohe, [0])],  # Apply OneHotEncoder to the first column
    remainder='passthrough'  # Keep other columns as they are
)

# Fit and transform the data
X = transformer.fit_transform(X)

# Output the transformed result
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [17]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [18]:
model.score(X,Y)

0.9573929037221873

In [19]:
model.predict([[1,0,2800]])

array([590775.63964739])